- common.pri
- libs/librepcbcommon/graphics/graphicsview.cpp
- libs/librepcbprojecteditor/boardeditor/boardeditor.cpp
- libs/librepcbprojecteditor/projecteditor.cpp
- libs/librepcbprojecteditor/schematiceditor/schematiceditor.cpp
> downgraded to qt version 5.2

- dev/docker/build_container.sh
- dev/docker/run_container.sh
- The flag "--privileged" seems to fix parts of #50 
- Splitting up "docker run" into "docker create" and "docker start" allows to make changes in the container persistent between sessions
@0xB767B What do you think about this?
> Fix GDB issues in docker container

- libs/librepcbcommon/librepcbcommon.pro
- libs/librepcbcommon/scopeguard.h
- libs/librepcbcommon/scopeguardlist.h
- tests/common/scopeguardtest.cpp
- tests/tests.pro
Inspired by
https://channel9.msdn.com/Shows/Going+Deep/C-and-Beyond-2012-Andrei-Alexandrescu-Systematic-Error-Handling-in-C
> Add ScopeGuard implementation

- libs/librepcbcommon/scopeguard.h
- libs/librepcbcommon/scopeguardlist.h
- tests/common/scopeguardtest.cpp
The entries should get executed in reverse order.
> ScopeGuardList: Added unit tests and fix bug

- libs/librepcbcommon/undocommandgroup.cpp
- libs/librepcbproject/boards/board.cpp
- libs/librepcbproject/boards/items/bi_device.cpp
- libs/librepcbproject/boards/items/bi_footprint.cpp
- libs/librepcbproject/circuit/componentinstance.cpp
- libs/librepcbproject/circuit/componentsignalinstance.cpp
- libs/librepcbproject/schematics/cmd/cmdschematicnetpointedit.cpp
- libs/librepcbproject/schematics/items/si_netlabel.cpp
- libs/librepcbproject/schematics/items/si_netline.cpp
- libs/librepcbproject/schematics/items/si_netpoint.cpp
- libs/librepcbproject/schematics/items/si_symbol.cpp
- libs/librepcbproject/schematics/schematic.cpp
- libs/librepcbprojecteditor/cmd/cmdcombineallnetsignalsunderschematicnetpoint.cpp
- libs/librepcbprojecteditor/cmd/cmdcombineallnetsignalsunderschematicnetpoint.h
- libs/librepcbprojecteditor/cmd/cmdcombinenetsignals.cpp
- libs/librepcbprojecteditor/cmd/cmdcombinenetsignals.h
- libs/librepcbprojecteditor/cmd/cmdcombineschematicnetpoints.cpp
- libs/librepcbprojecteditor/cmd/cmdcombineschematicnetpoints.h
- libs/librepcbprojecteditor/cmd/cmdplaceschematicnetpoint.cpp
- libs/librepcbprojecteditor/cmd/cmdremoveselectedboarditems.cpp
- libs/librepcbprojecteditor/cmd/cmdremoveselectedboarditems.h
- libs/librepcbprojecteditor/cmd/cmdremoveselectedschematicitems.cpp
- libs/librepcbprojecteditor/cmd/cmdremoveselectedschematicitems.h
@rnestler It seems that the new classes work great! Thanks to these classes I was able to remove lot of code which is no longer required :smiley:
> Use the new ScopeGuard/ScopeGuardList classes

- .travis.yml
> Travis-CI: Try to fix broken mac builds

- .travis.yml
Uses a custom Qt bottle (binary package) built by me for my own project (qutebrowser).
> travis: Fix OS X builds

- README.md
> README: Add note about the demo workspace

- .travis.yml
This could speed up the build. Fixes #90
> Use ccache in travis

- common.pri
- librepcb/controlpanel/controlpanel.cpp
> Show git revision in about dialog

- dev/diagrams/README.md
- dev/diagrams/convert.sh
- dev/diagrams/readme.txt
- dev/diagrams/schematic_editor/activity_add_component.dia
- dev/diagrams/schematic_editor/activity_add_netlabel.dia
- dev/diagrams/schematic_editor/activity_draw_wire.dia
- dev/diagrams/schematic_editor/activity_overview.dia
- dev/diagrams/svg/schematic_editor/activity_add_component.svg
- dev/diagrams/svg/schematic_editor/activity_add_netlabel.svg
- dev/diagrams/svg/schematic_editor/activity_draw_wire.svg
- dev/diagrams/svg/schematic_editor/activity_overview.svg
@0xB767B Is this the type of diagram you want to have?
> Add schematic editor activity diagrams

- libs/librepcbproject/erc/ercmsglist.cpp
- libs/librepcbproject/erc/ercmsglist.h
See #93
While looking through the code base to get familiar with it I will fix some of those.
> Cleanup ErcMsgList

- librepcb/controlpanel/controlpanel.cpp
- libs/librepcbcommon/fileio/xmldomelement.cpp
- libs/librepcbcommon/fileio/xmldomelement.h
- libs/librepcbprojecteditor/boardeditor/boardeditor.cpp
- libs/librepcbprojecteditor/projecteditor.cpp
- libs/librepcbprojecteditor/schematiceditor/schematiceditor.cpp
- libs/librepcbworkspace/favoriteprojectsmodel.cpp
- libs/librepcbworkspace/favoriteprojectsmodel.h
- libs/librepcbworkspace/recentprojectsmodel.cpp
- libs/librepcbworkspace/recentprojectsmodel.h
- libs/librepcbworkspace/settings/items/wsi_appdefaultmeasurementunits.cpp
- libs/librepcbworkspace/settings/items/wsi_appdefaultmeasurementunits.h
- libs/librepcbworkspace/settings/items/wsi_appearance.cpp
- libs/librepcbworkspace/settings/items/wsi_appearance.h
- libs/librepcbworkspace/settings/items/wsi_applocale.cpp
- libs/librepcbworkspace/settings/items/wsi_applocale.h
- libs/librepcbworkspace/settings/items/wsi_base.cpp
- libs/librepcbworkspace/settings/items/wsi_base.h
- libs/librepcbworkspace/settings/items/wsi_debugtools.cpp
- libs/librepcbworkspace/settings/items/wsi_debugtools.h
- libs/librepcbworkspace/settings/items/wsi_librarylocaleorder.cpp
- libs/librepcbworkspace/settings/items/wsi_librarylocaleorder.h
- libs/librepcbworkspace/settings/items/wsi_librarynormorder.cpp
- libs/librepcbworkspace/settings/items/wsi_librarynormorder.h
- libs/librepcbworkspace/settings/items/wsi_projectautosaveinterval.cpp
- libs/librepcbworkspace/settings/items/wsi_projectautosaveinterval.h
- libs/librepcbworkspace/settings/workspacesettings.cpp
- libs/librepcbworkspace/settings/workspacesettings.h
- libs/librepcbworkspace/settings/workspacesettingsdialog.cpp
Description: See commit messages ;)
Fixes #11
> Refactor workspace settings

- README.md
Because [cloudscale.ch](https://www.cloudscale.ch/) is our first sponsor, I think we should now add a "credits" section to the readme.
> Add credits section to readme

- libs/librepcbcommon/uuid.cpp
- libs/librepcbcommon/uuid.h
- tests/common/uuidtest.cpp
- tests/tests.pro
Because the class `Uuid` is very important for LibrePCB, here are some unit tests for it. And I have already fixed some small issues which were found by these tests ;)
> Add Uuid unit tests

- dev/build_each_commit.sh
This script allows to automatically build each single commit of the current branch (up to the master branch).
> Add bash script to build each commit of a branch

- CONTRIBUTING.md
- README.md
@dbrgn The IRC<->Telegram bridge is now working properly, isn't it?
So I would say it's time to mention the new chat in README and CONTRIBUTING :)
> README/CONTRIBUTING: Add links to IRC chat

- share/applications/librepcb.desktop
https://travis-ci.org/AppImage/AppImageHub/builds/264135008#L533-L535
> Make it pass desktop-file-validate

- dev/travis/install.sh
> Travis: Update to latest linuxdeployqt

- appveyor.yml
- common.pri
- dev/travis/build.sh
- libs/librepcb/common/fileio/sexpression.h
- libs/librepcb/library/pkg/footprintpadpreviewgraphicsitem.cpp
- libs/librepcb/library/pkg/footprintpadpreviewgraphicsitem.h
- libs/librepcb/library/pkg/footprintpreviewgraphicsitem.cpp
- libs/librepcb/library/pkg/footprintpreviewgraphicsitem.h
- libs/librepcb/library/sym/symbolpinpreviewgraphicsitem.cpp
- libs/librepcb/library/sym/symbolpinpreviewgraphicsitem.h
- libs/librepcb/library/sym/symbolpreviewgraphicsitem.cpp
- libs/librepcb/library/sym/symbolpreviewgraphicsitem.h
- tests/common/attributes/attributeproviderdummy.h
- tests/common/fileio/serializableobjectlisttest.cpp
This ensures that pull requests do not create new compiler warnings.
> Travis/AppVeyor: Compile with "-Werror" flag

- libs/librepcb/common/toolbox.cpp
- libs/librepcb/common/toolbox.h
- libs/librepcb/libraryeditor/dev/padsignalmapeditorwidget.cpp
- tests/common/toolboxtest.cpp
- tests/tests.pro
I have no idea what I'm doing 😂 
Fixes #210
> Device editor: Sort pad names numerically, then alphanumerically

- appveyor.yml
- libs/librepcb/common/fileio/serializableobjectlist.h
> Support Qt 5.10

- libs/librepcb/common/toolbox.cpp
This fix makes the code compilable on the openpandora again.
> Fix compile error on single precision FPUs

- libs/librepcb/libraryeditor/common/categorylisteditorwidget.cpp
> LibraryEditor: Fix fetching of package categories

- apps/librepcb/main.cpp
Previously the application settings were stored in different formats, depending on the operating system. But this is a bit cumbersome, especially the Windows Registry is a pain. So now the INI file format is used on all platforms.
In addition, the location of the INI file can be specified with the environment variable `LIBREPCB_CONFIG_DIR` (useful for functional tests).
Already existing settings should seamlessly be migrated to the new INI format.
Extracted from #287.
> Use INI for application settings on all platforms

- libs/librepcb/libraryeditor/libraryeditor.cpp
> Library Editor: Make "Close Library Editor" menu item working

- dev/doxygen/pages/project.md
- dev/doxygen/pages/workspace.md
See #185. Not that much documentation, but at least better than nothing ;) And I think I'll not implement anything of the upgrade procedure before the first release. Instead, I just hope it will work as intended - no risk, no fun :grin: If we implement #172 soon after the first release, the upgrade procedure may even become easier to implement.
> Doxygen: Add documentation about file format upgrade

- libs/librepcb/project/project.cpp
- libs/librepcb/project/project.h
- libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp
- libs/librepcb/projecteditor/schematiceditor/schematiceditor.h
- libs/librepcb/projecteditor/schematiceditor/schematiceditor.ui
Adds initial print support for the schematic editor. As usual, only very basic functionality, but better than nothing ;)
> SchematicEditor: Add print support

- libs/librepcb/common/units/length.cpp
- libs/librepcb/common/units/length.h
- tests/unittests/common/lengthtest.cpp
- tests/unittests/common/units/lengthtest.cpp
- tests/unittests/unittests.pro
If tests should be extended or there are some style issues, or anything else, please, say so.
> Length: Implement mmStringToNm() to use only integer operations

- CONTRIBUTING.md
I think with the first release ahead it is important to be able to easily contribute to the library eco-system.
> Document how to contribute to the part libraries

- libs/librepcb/common/fileio/sexpression.cpp
- libs/librepcb/library/pkg/footprintpreviewgraphicsitem.cpp
- libs/librepcb/library/sym/symbolpreviewgraphicsitem.cpp
- libs/librepcb/project/library/projectlibrary.cpp
- libs/librepcb/projecteditor/cmd/cmdremoveselectedschematicitems.cpp
Reported by static code analysis, see #394. Only fixes in our own code, not in 3rd-party libraries.
> Fix some code issues reported by PVS-Studio

- dev/format_code.sh
Fixes the issues reported by the shellcheck utility.
> Improve format code script

- apps/WorkspaceLibraryUpdater/mainwindow.cpp
- libs/librepcb/common/cam/excellongenerator.cpp
- libs/librepcb/common/cam/gerbergenerator.cpp
- libs/librepcb/common/common.pro
- libs/librepcb/common/fileio/sexpression.cpp
- libs/librepcb/common/fileio/sexpression.h
- libs/librepcb/common/fileio/smartsexprfile.cpp
- libs/librepcb/common/fileio/smartversionfile.cpp
- libs/librepcb/common/fileio/smartversionfile.h
- libs/librepcb/common/fileio/versionfile.cpp
- libs/librepcb/common/fileio/versionfile.h
- libs/librepcb/projecteditor/newprojectwizard/newprojectwizard.cpp
- libs/librepcb/workspace/favoriteprojectsmodel.cpp
- libs/librepcb/workspace/favoriteprojectsmodel.h
- libs/librepcb/workspace/library/workspacelibrarydb.cpp
- libs/librepcb/workspace/recentprojectsmodel.cpp
- libs/librepcb/workspace/recentprojectsmodel.h
- libs/librepcb/workspace/settings/workspacesettings.cpp
- libs/librepcb/workspace/workspace.cpp
- tests/unittests/project/boards/boardplanefragmentsbuildertest.cpp
- tests/unittests/workspace/workspacetest.cpp
Some preparations for #172. No functional changes, just code refactoring.
> Slightly simplify file handling

- libs/librepcb/common/geometry/path.cpp
- libs/librepcb/common/geometry/vertex.cpp
- libs/librepcb/common/geometry/vertex.h
- tests/unittests/common/geometry/pathtest.cpp
- tests/unittests/unittests.pro
Fixes #424. I also fixed another small bug in the `Path` class, but that one didn't have any consequences so far.
> Fix possible wrong orientation of obround pads

- libs/librepcb/common/widgets/attributelisteditorwidget.cpp
- libs/librepcb/common/widgets/patheditorwidget.cpp
- libs/librepcb/libraryeditor/cmp/componentsignallisteditorwidget.cpp
- libs/librepcb/libraryeditor/cmp/componentsymbolvariantitemlisteditorwidget.cpp
- libs/librepcb/libraryeditor/cmp/componentsymbolvariantlistwidget.cpp
- libs/librepcb/libraryeditor/pkg/footprintlisteditorwidget.cpp
- libs/librepcb/libraryeditor/pkg/packagepadlisteditorwidget.cpp
I hope this fixes #399 by stop using hardcoded table cell heights, but I can't test it as I don't have a high DPI display. Testers welcome ;)
Fixes #399 (hopefully)
> Fix cell height issues of several tables on high DPI displays

- apps/librepcb-cli/commandlineinterface.cpp
- apps/librepcb-cli/commandlineinterface.h
Add CLI command `open-library` to open and save libraries. This is useful to check libraries on CI.
> CLI: Add "open-library" command

- libs/librepcb/common/graphics/graphicslayer.cpp
Still untested, I hope it compiles :slightly_smiling_face: 
Fixes #406.
> Update default layer colors

- dev/format_code.sh
This allows to run docker with sudo for users which are not in the
docker group on their system.
> Add a --sudo option to format_code.sh

- libs/librepcb/project/boards/boardgerberexport.cpp
> Gerber export: Fix possibly wrong position of circles in footprints

- tests/unittests/common/alignmenttest.cpp
- tests/unittests/unittests.pro
Tests for "mirrored()" function. 
I want to extend it. ¿Some ideas or other tests files to look for inspiration? :smile:
Related #121
> Alignment: Add basic unit tests

- libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawtextbase.cpp
- libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawtextbase.cpp
> Library editor: Remove underscore from placeholders

- libs/librepcb/library/pkg/footprintgraphicsitem.cpp
- libs/librepcb/library/pkg/footprintgraphicsitem.h
- libs/librepcb/library/pkg/footprintpad.cpp
- libs/librepcb/library/pkg/footprintpadgraphicsitem.cpp
- libs/librepcb/library/pkg/footprintpadgraphicsitem.h
- libs/librepcb/libraryeditor/pkg/footprintclipboarddata.cpp
- libs/librepcb/libraryeditor/pkg/fsm/packageeditorfsm.cpp
> Package editor: Show footprint pad names

- libs/librepcb/common/fileio/transactionalfilesystem.cpp
- libs/librepcb/common/toolbox.h
- libs/librepcb/project/boards/board.cpp
- libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp
- libs/librepcb/projecteditor/boardeditor/unplacedcomponentsdock.cpp
- libs/librepcb/projecteditor/cmd/cmdflipselectedboarditems.cpp
- libs/librepcb/projecteditor/cmd/cmdremoveboarditems.cpp
- libs/librepcb/projecteditor/cmd/cmdremoveselectedschematicitems.cpp
- libs/librepcb/projecteditor/dialogs/editnetclassesdialog.cpp
- libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.cpp
- libs/librepcb/workspace/library/workspacelibraryscanner.cpp
- tests/unittests/common/fileio/transactionalfilesystemtest.cpp
It seems that on Azure Pipelines the macOS image was updated from Qt 5.13 to 5.14, now CI fails because of some deprecation warnings.
> Fix Qt 5.14 deprecation warnings

- libs/librepcb/projecteditor/boardeditor/fsm/bes_drawpolygon.cpp
> Board editor: Fix duplicate vertices when drawing polygons

- libs/librepcb/projecteditor/boardeditor/boardeditor.cpp
- libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp
- libs/librepcb/workspace/settings/workspacesettings.cpp
- libs/librepcb/workspace/settings/workspacesettings.h
- libs/librepcb/workspace/settings/workspacesettingsdialog.cpp
- libs/librepcb/workspace/settings/workspacesettingsdialog.ui
> Support configuring PDF viewer in workspace settings

- libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp
> When placing a via, allow its placement at the start Point

- libs/librepcb/projecteditor/cmd/cmdreplacedevice.cpp
- Fixes #616 
- Replace pad with NetPoints, one for each used layer, when more than one NetLine is connected
- Remove unused includes
> Board editor: Don't remove complete trace when changing device

- libs/librepcb/project/boards/graphicsitems/bgi_plane.cpp
- libs/librepcb/project/boards/graphicsitems/bgi_plane.h
- libs/librepcb/project/boards/items/bi_plane.h
- libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate_select.cpp
- libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate_select.h
Just like #773, but for planes instead of polygons.
Based on #773, so #773 needs to be merged first.
> Board editor: Allow to modify planes graphically

- img/README.md
Clarify licensing data for icons.
Unfortunately most files don't have matches.
> Document license of icons

- tests/funq/libraryeditor/test_overview_tab.py
As usual, one more test which is flaky only on Windows. Hopefully now it is more reliable...
> Try to fix flaky functional test test_overview_tab.py

- AUTHORS.md
- apps/librepcb/main.cpp
- dev/doxygen/pages/developers.md
Please give lots of feedback on coding style etc :)
> Add workspace override environment variable

- tests/unittests/common/fileio/asynccopyoperationtest.cpp
This unittest used QSignalSpy to check the emitted signals, but QSignalSpy is not threadsafe which sometimes caused a crash (segfault) and thus made CI flaky.
See Qt bug report: https://bugreports.qt.io/browse/QTBUG-40616
Now the signals are manually connected with Qt::QueuedConnection for thread safety, not using QSignalSpy anymore.
> Unit tests: Stop using QSignalSpy in AsyncCopyOperationTest

- img/README.md
Compared images with the contents of open_icon_library-standard-0.11.tar.bz2
> Update image licenses

- apps/librepcb/main.cpp
- libs/librepcb/core/CMakeLists.txt
- libs/librepcb/core/workspace/workspacesettings.cpp
- libs/librepcb/core/workspace/workspacesettings.h
- libs/librepcb/core/workspace/workspacesettingsitem_keyboardshortcuts.cpp
- libs/librepcb/core/workspace/workspacesettingsitem_keyboardshortcuts.h
- libs/librepcb/editor/CMakeLists.txt
- libs/librepcb/editor/modelview/keyboardshortcutsmodel.cpp
- libs/librepcb/editor/modelview/keyboardshortcutsmodel.h
- libs/librepcb/editor/modelview/keysequencedelegate.cpp
- libs/librepcb/editor/modelview/keysequencedelegate.h
- libs/librepcb/editor/utils/editortoolbox.cpp
- libs/librepcb/editor/utils/editortoolbox.h
- libs/librepcb/editor/widgets/keysequenceseditorwidget.cpp
- libs/librepcb/editor/widgets/keysequenceseditorwidget.h
- libs/librepcb/editor/workspace/workspacesettingsdialog.cpp
- libs/librepcb/editor/workspace/workspacesettingsdialog.ui
> Make keyboard shortcuts configurable in workspace settings

- libs/librepcb/editor/workspace/librarymanager/librarymanager.ui
Just a small visual improvement.
> Library manager: Remove borders around library list widget

- libs/librepcb/core/CMakeLists.txt
- libs/librepcb/core/serialization/fileformatmigration.cpp
- libs/librepcb/core/serialization/fileformatmigrationunstable.cpp
- libs/librepcb/core/serialization/fileformatmigrationunstable.h
- libs/librepcb/core/serialization/fileformatmigrationv01.cpp
Allow partially upgrading the previous unstable file format if the `LIBREPCB_UPGRADE_UNSTABLE` environment variable is set to `1`. This allows to upgrade our test data files and thus heavily simplifies developing file format changes.
> Support partially upgrading from the previous unstable file format

- apps/librepcb-cli/commandlineinterface.cpp
- libs/librepcb/core/export/bom.cpp
- libs/librepcb/core/export/bom.h
- libs/librepcb/core/export/pickplacedata.cpp
- libs/librepcb/core/library/msg/libraryelementcheckmessage.cpp
- libs/librepcb/core/library/msg/libraryelementcheckmessage.h
- libs/librepcb/core/library/sym/msg/msgoverlappingsymbolpins.cpp
- libs/librepcb/core/serialization/serializableobjectlist.h
- libs/librepcb/core/utils/toolbox.h
- libs/librepcb/eagleimport/eaglelibraryimport.cpp
- libs/librepcb/editor/dialogs/graphicsexportdialog.cpp
- libs/librepcb/editor/library/cmd/cmdpastesymbolitems.cpp
- libs/librepcb/editor/library/libraryelementchecklistwidget.cpp
- libs/librepcb/editor/modelview/comboboxdelegate.cpp
- libs/librepcb/editor/modelview/comboboxdelegate.h
- libs/librepcb/editor/project/boardeditor/boardeditor.cpp
- libs/librepcb/editor/project/boardeditor/boardplanepropertiesdialog.cpp
- libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_addvia.cpp
- libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawplane.cpp
- libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_select.cpp
- libs/librepcb/editor/project/boardeditor/unplacedcomponentsdock.cpp
- libs/librepcb/editor/project/schematiceditor/renamenetsegmentdialog.cpp
- libs/librepcb/editor/project/schematiceditor/schematiceditor.cpp
- libs/librepcb/editor/widgets/searchtoolbar.cpp
- libs/librepcb/editor/workspace/categorytreemodel.cpp
There were various places in the code where numeric string sorting would make sense but wasn't used, this PR fixes that. Also factored out the corresponding code into a shared function to avoid duplicate code.
> Fix missing numeric sort at various places

- libs/librepcb/editor/project/addcomponentdialog.cpp
- libs/librepcb/editor/project/addcomponentdialog.h
- libs/librepcb/editor/project/addcomponentdialog.ui
...and implement some smaller usability improvements in that dialog (keyboard navigation & error handling).
Closes #1059
> Add component dialog: Automatically select first search result

- libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_select.cpp
Open the context menu of the device when right-clicking on a footprint pad in the board editor. I think this was the actual problem reported in #1060.
Fixes #1060.
> Board editor: Fix context menu of selected devices

- tests/cli/open_library/test_check.py
- tests/unittests/CMakeLists.txt
- tests/unittests/core/library/cmp/componenttest.cpp
- tests/unittests/core/library/cmpcat/componentcategorytest.cpp
- tests/unittests/core/library/dev/devicetest.cpp
- tests/unittests/core/library/librarytest.cpp
- tests/unittests/core/library/pkg/packagetest.cpp
- tests/unittests/core/library/pkgcat/packagecategorytest.cpp
- tests/unittests/core/library/sym/symboltest.cpp
- tests/unittests/core/project/projecttest.cpp
> Add more tests for file format related features

- libs/librepcb/editor/workspace/desktopservices.cpp
I wanted to update our Snap package from `core18` to `core20` or `core22`, but opening files/folders from within LibrePCB does not work anymore after the update. Seems to be a known issue:
- https://bugreports.qt.io/browse/QTBUG-81597
- https://bugreports.qt.io/browse/QTBUG-83939
- https://forum.snapcraft.io/t/xdg-open-or-gvfs-open-qdesktopservices-openurl-file-somelocation-file-txt-wont-open-the-file/16824
Therefore this PR allows to set an environment variable `LIBREPCB_OPEN_URL_HANDLER=/bin/xdg-open` which can be specified in the Snap runtime environment. It causes to call the specified command (with the URL as parameter) instead of using `QDesktopServices::openUrl()`. Confirmed that this works properly within a Snap package.
> DesktopServices: Support using (custom) xdg-open command

- ci/azure-jobs-linux.yml
- ci/azure-jobs-windows.yml
Updating OpenCascade to v7.7.2.
Closes #1220
> CI: Update to latest Docker images

- tests/unittests/CMakeLists.txt
- tests/unittests/core/fileio/versionfiletest.cpp
This test isn't failing, it can move forward faster than failing #1233 that needs supporting PR solving found issue.
> Add unit test for VersionFile

- libs/librepcb/core/project/board/items/bi_stroketext.cpp
> Fix part attributes not substituted in board editor

- libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate.cpp
> Board editor: Fix layer change when starting trace on THT pad

- libs/librepcb/editor/workspace/controlpanel/controlpanel.ui
> Control Panel: Fix unreadable list view colors for dark themes

- libs/librepcb/editor/library/newelementwizard/newelementwizardpage_componentsymbols.cpp
- libs/librepcb/editor/library/newelementwizard/newelementwizardpage_componentsymbols.h
> Library editor: Fix suggested signals when duplicating component

- .reuse/dep5
- libs/librepcb/eagleimport/eaglelibraryconverter.cpp
- libs/librepcb/eagleimport/eaglelibraryconverter.h
- libs/librepcb/eagleimport/eaglelibraryimport.cpp
- libs/librepcb/eagleimport/eagleprojectimport.cpp
- libs/librepcb/eagleimport/eagleprojectimport.h
- tests/unittests/eagleimport/eagleprojectimporttest.cpp
Found Eagle projects with strange embedded libraries which failed to import...
> Eagle import: Fix possible project library import error

- libs/librepcb/editor/library/libraryeditor.cpp
- libs/librepcb/editor/project/boardeditor/boardeditor.cpp
Didn't find a clean solution for the problem, but this workaround seems to work...
Fixes #1363
> Fix temporarily closing windows when opening 3D viewer (Qt6)

- libs/librepcb/core/workspace/theme.cpp
- libs/librepcb/core/workspace/theme.h
- libs/librepcb/core/workspace/themecolor.cpp
- libs/librepcb/core/workspace/themecolor.h
These translations were performed before the language was loaded so it was unknown at this time.
Fixes #1357
> Fix possibly wrong language of theme color names

- libs/librepcb/core/3d/stepexport.cpp
For consistent behavior with the integrated 3D viewer, export all board outlines to the STEP file.
Fixes #1364
> STEP export: Include all PCB outlines, if multiple

- apps/librepcb/main.cpp
> Implement automatic dark theme for Windows

- libs/librepcb/core/3d/occmodel.cpp
See comment in source code and discussion in #1387.
Fixes #1387.
> STEP export: Fix possibly wrong placement of devices

- .reuse/dep5
> Update REUSE copyright metadata

- libs/librepcb/editor/project/schematiceditor/symbolinstancepropertiesdialog.cpp
Sometimes one wants to explicitly set the name of a component, for example to have components with consecutive numbers close to each other (R1, R2, R3) for readability reasons or to make assembly easier.
However, when renaming a component and the new name already exists in the schematic, an error was shown and one had to rename the other component first to "release" its name. This was very cumbersome.
Now a message box asks to simply swap the components name in this case so LibrePCB doesn't prevent you from renaming a component anymore -> much better user experience.
> Schematic editor: Ask for swapping component names

- libs/librepcb/editor/project/cmd/cmdpasteschematicitems.cpp
> Schematic editor: Fix random names after paste

- libs/librepcb/core/export/graphicspainter.cpp
- libs/librepcb/core/geometry/path.cpp
- libs/librepcb/core/geometry/path.h
- libs/librepcb/editor/project/boardeditor/graphicsitems/bgi_netline.cpp
- libs/librepcb/editor/project/schematiceditor/graphicsitems/sgi_netline.cpp
- tests/unittests/core/geometry/pathtest.cpp
> Fix zero-length traces/lines not being rendered

- libs/librepcb/core/project/board/drc/boarddesignrulecheck.cpp
> DRC: Fix false-positive board<->copper clearance errors

- libs/librepcb/editor/project/schematiceditor/graphicsitems/sgi_netlabel.cpp
> SGI_NetLabel: Fix missing pointer check

- libs/librepcb/rust-core/src/ffi/zip_writer_ffi.rs
- tests/unittests/CMakeLists.txt
- tests/unittests/core/fileio/zipwriterziparchivetest.cpp
> ZipWriter: Fix writing large files and to nonexistent directory

- .gitignore
- .tx/config
- ci/azure-jobs-stylecheck.yml
- dev/i18n.py
Some translation related tasks are currently implemented only on our server (not public), but it makes more sense to have this implemented in this repository so I wrote a Python script for that. The server shall then just call this script.
To be extended as soon as we have the Slint UI.
> Add script dev/i18n.py to perform translation tasks

- libs/librepcb/editor/3d/openglobject.h
- libs/librepcb/editor/3d/openglscenebuilder.cpp
- libs/librepcb/editor/3d/openglscenebuilder.h
- libs/librepcb/editor/3d/opengltriangleobject.cpp
- libs/librepcb/editor/3d/opengltriangleobject.h
- libs/librepcb/editor/3d/slintopenglview.cpp
- libs/librepcb/editor/3d/slintopenglview.h
- libs/librepcb/editor/project/board/board3dtab.cpp
- libs/librepcb/editor/project/board/board3dtab.h
- libs/librepcb/editor/ui/api/data.slint
- libs/librepcb/editor/ui/api/types.slint
- libs/librepcb/editor/ui/project/board/board3dtab.slint
- libs/librepcb/editor/ui/project/schematic/schematictab.slint
- libs/librepcb/editor/ui/widgets.slint
- libs/librepcb/editor/ui/widgets/scenebutton.slint
- libs/librepcb/editor/ui/widgets/slider.slint
- libs/librepcb/editor/widgets/openglview.cpp
> 3D view: Add sliders to change transparency of objects

- libs/librepcb/core/project/board/drc/boarddesignrulecheckmessages.cpp
- libs/librepcb/core/serialization/fileformatmigrationv1.cpp
- libs/librepcb/core/serialization/fileformatmigrationv1.h
- tests/unittests/core/project/board/boarddesignrulechecktest.cpp
> DRC: Rename approval keys useless_via and antennae_via

- libs/librepcb/editor/ui/appwindow.slint
- libs/librepcb/editor/ui/tab.slint
> Update submodule "libs/slint"

- libs/librepcb/core/project/board/board.h
- libs/librepcb/core/project/project.cpp
- libs/librepcb/core/project/project.h
- libs/librepcb/core/project/projectloader.cpp
- libs/librepcb/core/project/projectloader.h
- libs/librepcb/core/project/schematic/schematic.cpp
- libs/librepcb/core/project/schematic/schematic.h
> Introduce settings.user.lp for projects & schematics
