libs/librepcbcommon/graphics/graphicsview.cpp
On scroll-wheels the ``event->delta()`` always returns +-120. On touch-pads the
events arise faster and have different values.
=> graphics: Fix zooming on touch-pads

README.md
Here's the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=librepcb-git) and the [.install file](https://aur.archlinux.org/cgit/aur.git/tree/librepcb-git.install?h=librepcb-git).
Btw, is it possible that libglu is not actually needed?
=> Added AUR link to README

libs/librepcbproject/circuit/circuit.cpp, libs/librepcbproject/circuit/circuit.h, libs/librepcbproject/circuit/netsignal.cpp, libs/librepcbproject/circuit/netsignal.h, libs/librepcbproject/schematics/graphicsitems/sgi_netlabel.cpp, libs/librepcbproject/schematics/graphicsitems/sgi_netline.cpp, libs/librepcbproject/schematics/graphicsitems/sgi_netpoint.cpp, libs/librepcbproject/schematics/graphicsitems/sgi_symbolpin.cpp, libs/librepcbproject/schematics/items/si_netlabel.cpp, libs/librepcbproject/schematics/items/si_netlabel.h, libs/librepcbproject/schematics/items/si_netline.cpp, libs/librepcbproject/schematics/items/si_netline.h, libs/librepcbproject/schematics/items/si_netpoint.cpp, libs/librepcbproject/schematics/items/si_netpoint.h, libs/librepcbproject/schematics/items/si_symbolpin.cpp, libs/librepcbproject/schematics/items/si_symbolpin.h, libs/librepcbprojecteditor/schematiceditor/fsm/ses_drawwire.cpp
When drawing a wire in the schematic editor, all other lines/pins of the same net signal will now be highlighted.
=> Add possibility to highlight all items of a specific net signal

appveyor.yml
Windows has linked to the wrong Qt DLLs. With adding the directory of the correct Qt DLLs to the *front* of the PATH variable, the correct DLLs will now be loaded.
Fixes #68 (hopefully)
=> Fix broken AppVeyor builds

libs/librepcbcommon/systeminfo.cpp
Use `getpwuid()` function instead of doing shell execution and parsing.
Fixes #76.
=> Fix detection of full username on Unix/Linux

.gitmodules, .travis.yml, 3rdparty/3rdparty.pro, 3rdparty/gmock/gmock.pro, README.md, appveyor.yml, dev/docker/Dockerfile, librepcb/controlpanel/controlpanel.cpp, librepcb/controlpanel/controlpanel.h, librepcb/controlpanel/controlpanel.ui, librepcb/librepcb.pro, librepcb/markdown/markdownconverter.cpp, librepcb/markdown/markdownconverter.h, libs/librepcbproject/cmd/cmdprojectsetmetadata.cpp, libs/librepcbproject/cmd/cmdprojectsetmetadata.h, libs/librepcbproject/project.cpp, libs/librepcbproject/project.h, libs/librepcbprojecteditor/dialogs/projectpropertieseditordialog.cpp, libs/librepcbprojecteditor/dialogs/projectpropertieseditordialog.ui, tools/EagleImport/EagleImport.pro, tools/ProjectLibraryUpdater/ProjectLibraryUpdater.pro, tools/WorkspaceLibraryUpdater/WorkspaceLibraryUpdater.pro
- [Hoedown](https://github.com/hoedown/hoedown) is used to convert the README.md into HTML
- [QTextBrowser](http://doc.qt.io/qt-5/qtextbrowser.html) is used to display the HTML in the ControlPanel
Fixes #72 and #79.
=> Use markdown for project descriptions (instead of HTML)

libs/librepcbprojecteditor/cmd/cmddetachboardnetpointfromviaorpad.cpp, libs/librepcbprojecteditor/cmd/cmddetachboardnetpointfromviaorpad.h, libs/librepcbprojecteditor/cmd/cmdremovedevicefromboard.cpp, libs/librepcbprojecteditor/cmd/cmdremovedevicefromboard.h, libs/librepcbprojecteditor/cmd/cmdremoveselectedboarditems.cpp, libs/librepcbprojecteditor/cmd/cmdremoveviafromboard.cpp, libs/librepcbprojecteditor/cmd/cmdremoveviafromboard.h, libs/librepcbprojecteditor/librepcbprojecteditor.pro
- Add high-level undo command CmdRemoveViaFromBoard
- Add high-level undo command CmdRemoveDeviceFromBoard
- Add high-level undo command CmdDetachBoardNetPointFromViaOrPad
- Removing vias should now work properly in all cases (did not work when
netlines were connected to them)
Can be merged after #89 was merged, because I already used the new license header in all new source files.
=> Cleanup/Improve CmdRemoveSelectedBoardItems

libs/librepcblibrary/library.cpp, libs/librepcblibrary/library.h
When the SQLite database does not exist and the user adds a component to
a schematic, an SQL error appears and the whole application crashes.
The thrown exception is caused by non-existing tables in the database.
The crash is caused by the method Library::getElementFilePathsFromDb()
which is mistakenly marked with the "noexcept" keyword although it can
thow exceptions.
This commit does:
- Avoid the thrown exception by creating all non-existing tables right
after opening the database (ctor of Library).
- Fix the application crash by correcting the exception specifier of
Library::getElementFilePathsFromDb().
Fixes #78
=> Library: Fix application crash caused by SQL error

.travis.yml
- Reduce count of jobs (8 --> 4)
- Run all linux builds on Ubuntu Trusty (instead of Ubuntu Precise)
- Build only with minimal and maximal supported Qt versions (versions
between them are no longer tested)
Fixes #95, #96, #99
=> Travis: Simplify build matrix

libs/librepcbprojecteditor/projecteditor.cpp, libs/librepcbprojecteditor/projecteditor.h
When opened a project which has no schematics and boards, neither the schematic editor nor the board editor were shown and the whole project was invisible for the user.
This commit ensures that the schematic editor will be shown anyway in this special case.
=> Fix invisible project editor when no schematics/boards exist

README.md
This adds a Flattr and a Bitcoin donation button to the README. The Bitcoin button is just a link to [blockchain.info](https://blockchain.info/address/1FiXZxoXe3px1nNuNygRb1NwcYr6U8AvG8), where our Bitcoin address and a QR code is shown. In future we may create a donation section on our [website](http://librepcb.org) and link to there, but at the moment this is the easiest solution ;)
=> README: Add donation buttons

.gitattributes
Just tried to open a LibrePCB project on windows and got following error:
```
The suffix of the project file must be "lpp"! {C:/LibrePCB/LibrePCB/dev/demo-workspace/projects/Demo Brushless Controller/Demo Brushless Controller.lpp
} 
```
Note the line break before the closing curly bracket - it's a ```\r``` character :scream:
Git has a configuration called ```core.autocrlf``` to automatically convert line endings between LF and CRLF when checkout and/or commit files. On some *incredible crappy operating systems* this (anti-)feature is often activated (either by default, by accident or because of suggestions in the internet). **This is completely bullshit because LibrePCB does not work properly with CRLF line endings!**
All files created with LibrePCB **must be platform independent**, so we …
=> Add .gitattributes to avoid automatic EOL conversion

common.pri, librepcb/controlpanel/controlpanel.cpp, librepcb/main.cpp, libs/librepcbcommon/application.cpp, libs/librepcbcommon/application.h, libs/librepcbcommon/librepcbcommon.pro, libs/librepcbcommon/version.cpp, libs/librepcbcommon/version.h, libs/librepcblibrary/librarybaseelement.cpp, libs/librepcbprojecteditor/newprojectwizard/newprojectwizard.cpp, libs/librepcbprojecteditor/newprojectwizard/newprojectwizardpage_metadata.cpp, libs/librepcbworkspace/workspace.cpp, tests/common/applicationtest.cpp, tests/common/versiontest.cpp, tests/main.cpp, tests/tests.pro
Some general improvements in the versioning system. Parts of this are required for #114.
This pull request changes the file version type from Integer to a semantic version string. So a workspace/library/project can now have version ```0.1``` or ```1.2.3``` instead of only ```0```, ```1```, and so on. This is required to allow making multiple file format upgrades **before** version ```1``` (which indicates a stable version) while keeping the file format version equal to the application version. The file format version needs to be a prefix of the application version, e.g. format version ```0.1``` is used by application version ```0.1.x``` and format version ```1``` is used by application version ```1.x```.
=> Improve versioning system

libs/librepcbcommon/systeminfo.cpp, tests/common/systeminfotest.cpp
The Windows API function `GetModuleFileNameExW()` seems to be a crappy nightmare :scream: Hopefully `QueryFullProcessImageNameW()` is more reliable. At least an ugly workaround in the unit tests seems to be needless now...
See https://blogs.msdn.microsoft.com/oldnewthing/20150716-00/?p=45131/ (very interesting!)
Windows... :sob:
P.S. LibrePCB will no longer run on Windows XP after this change (if it ever run on XP :wink:) because `QueryFullProcessImageNameW()` was introduced with Windows Vista.
=> SystemInfo: Make getProcessNameByPid() more reliable on Windows

.gitmodules, .travis.yml, 3rdparty/3rdparty.pro, README.md, appveyor.yml, common.pri, librepcb/librepcb.pro, librepcb/main.cpp, libs/librepcbcommon/application.cpp, libs/librepcbcommon/debug.cpp, libs/librepcbcommon/debug.h, libs/librepcbcommon/fileio/filepath.h, libs/librepcbcommon/librepcbcommon.pro, libs/librepcbcommon/network/filedownload.cpp, libs/librepcbcommon/network/filedownload.h, libs/librepcbcommon/network/networkaccessmanager.cpp, libs/librepcbcommon/network/networkaccessmanager.h, libs/librepcbcommon/network/networkrequest.cpp, libs/librepcbcommon/network/networkrequest.h, libs/librepcbcommon/network/networkrequestbase.cpp, libs/librepcbcommon/network/networkrequestbase.h, tests/common/filedownloadtest.cpp, tests/common/networkrequestbasesignalreceiver.h, tests/common/networkrequesttest.cpp, tests/tests.pro
We need this network access manager to download zipped libraries and more from the Internet. The main features of that manager are:
- Follow HTTP redirects (transparently for the user of the network access manager)
- Process requests asynchronously in a separate thread (avoids a blocked GUI thread)
- Process multiple requests in parallel
- Verify checksum of downloaded files
- Extract ZIP files after download with [QuaZIP](http://quazip.sourceforge.net/)
- Report progress, errors and finished event with Qt's signals/slots mechanism (thread-safe)
I have slightly modified the project files of QuaZIP to integrate the library in LibrePCB. The modified project is now hosted here: https://github.com/LibrePCB/quazip
=> Add network access manager

apps/EagleImport/EagleImport.pro, apps/ProjectLibraryUpdater/ProjectLibraryUpdater.pro, apps/WorkspaceLibraryUpdater/WorkspaceLibraryUpdater.pro, apps/librepcb/librepcb.pro, dev/sort_qmake_file_entries.py, libs/librepcb/common/common.pro, libs/librepcb/library/library.pro, libs/librepcb/libraryeditor/libraryeditor.pro, libs/librepcb/librarymanager/librarymanager.pro, libs/librepcb/project/project.pro, libs/librepcb/projecteditor/projecteditor.pro, libs/librepcb/workspace/workspace.pro
The new script `sort_qmake_file_entries.py` sorts the entries of HEADERS, SOURCES and FORMS variables in all qmake project files (*.pro) in alphabetical order (except those in submodules). This reduces the risk of conflicts when merging or rebasing commits which modify *.pro files and makes those files cleaner and thus easier to read.
It may even be used as a pre-commit hook.
See also https://bugreports.qt.io/browse/QTCREATORBUG-553.
=> Sort entries of HEADERS, SOURCES and FORMS in *.pro files

libs/librepcb/common/graphics/graphicsview.cpp, libs/librepcb/common/graphics/graphicsview.h, libs/librepcb/projecteditor/boardeditor/fsm/bes_fsm.cpp, libs/librepcb/projecteditor/boardeditor/fsm/bes_select.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/ses_fsm.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/ses_select.cpp
Panning with right mouse button is quite annoying as it conflicts with context menus :sob: Now the middle mouse button is used instead. Was really hard to implement... :smile:
See also #4.
=> GraphicsView: Pan with middle mouse button instead of right button

.travis.yml, dev/travis/build.sh, dev/travis/install.sh, dev/travis/run_tests.sh, dev/travis/update_doxygen.sh
- Move logic into separate shell scripts to make the whole configuration more clear.
- Remove secure variable from `.travis.yml`, store it in the web interface instead.
=> Travis-CI: Cleanup configuration

apps/librepcb/controlpanel/controlpanel.cpp, libs/librepcb/common/sqlitedatabase.cpp, libs/librepcb/common/sqlitedatabase.h, tests/common/sqlitedatabasetest.cpp, tests/tests.pro
Until now, the SQLite database of the workspace library is [put under version control](https://github.com/LibrePCB/demo-workspace/blob/36974bc36e875a28fb5affa3b291b699d5123dc1/v0.1/metadata/library_cache.sqlite) because it was not automatically generated.
This PR will force to (re)scan the workspace library on every program startup to ensure that it is always up to date. Because this is done completely asynchronously in a separate thread and can be interrupted at any time (e.g. on program exit), it should not have any negative impact on user experience (except maybe little decreased performance due to higher CPU load for a few seconds).
Thanks to this change I could [remove the SQLite database from version control](https://github.com/LibrePCB/demo-workspace/commit/eee0d43904412292418758c12 …
=> Scan workspace library on every program startup

appveyor.yml
Surprisingly, uploading build artifacts is quite easy with AppVeyor ;) So I started to use this feature to provide nightly builds for Windows. They can now be downloaded [here](https://ci.appveyor.com/api/projects/librepcb/librepcb/artifacts/build/librepcb-nightly.zip?branch=appveyor_nightly_builds). 
Just extract the downloaded ZIP archive and execute `bin\librepcb.exe`. Isn't this awesome?! :smiley: 
@nemofisch Maybe you would like to try if it works properly on your machine?
The only thing which is not yet working is to load runtime resources of LibrePCB (e.g. license template files). I think the resource system needs to be adjusted slightly...
=> AppVeyor: Provide nightly builds for Windows

appveyor.yml
This fixes runtime errors because of missing DLLs (e.g. msvcr120.dll) on
Windows without the Visual C++ Redistributable Package. See also
https://msdn.microsoft.com/en-us/library/dd293565(v=vs.110).aspx
=> AppVeyor: Ship MS Visual C++ DLLs with nightly builds

dev/travis/build.sh, dev/travis/install.sh
Build times of the first run (caches for clang and osx not yet available):
Build times after triggering a rebuild (caches from the first run are now available):
Fixes #90
=> Travis: Make ccache also working with clang and OS X

.travis.yml, README.md, dev/travis/bintray.json, dev/travis/build_appimage.sh, dev/travis/install.sh
Having [AppImage](http://appimage.org/) for nightly builds but also for stable releases would be pretty nice. With this PR I try to let them build on Travis-CI and upload to [Bintray](https://bintray.com/librepcb).
Basically it already works, but there are still some issues:
=> Build and deploy nightly AppImage

libs/librepcb/common/common.pro, libs/librepcb/common/undocommandgroup.cpp, libs/librepcb/common/undostack.cpp, libs/librepcb/common/undostack.h, libs/librepcb/common/utils/undostackactiongroup.cpp, libs/librepcb/common/utils/undostackactiongroup.h, libs/librepcb/projecteditor/boardeditor/boardeditor.cpp, libs/librepcb/projecteditor/boardeditor/boardeditor.h, libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.h
These changes are already used in the `add_library_editor` branch, but as this is a separate feature I will already merge this into `master`.
Especially the new class `UndoStackTransaction` is pretty cool as it allows to use RAII when working on the undo stack :wink:
=> Improve undo stack (cleaner code, improved exception safety, ...)

libs/librepcb/common/fileio/filepath.cpp, libs/librepcb/common/fileio/filepath.h, tests/common/filepathtest.cpp
- Spaces were replaced even if CleanFileNameOption::KeepSpaces was used
- Simplify regex: use character ranges, remove escaping for minus sign
- Add CleanFileNameOption::ToUpperCase
- Improve comments
- Add test
=> FilePath: Fix/improve method cleanFileName()

libs/librepcb/common/fileio/xmldomdocument.cpp, libs/librepcb/common/fileio/xmldomdocument.h, libs/librepcb/common/fileio/xmldomelement.cpp, libs/librepcb/common/fileio/xmldomelement.h, libs/librepcb/library/dev/device.h, libs/librepcb/project/circuit/componentinstance.h, libs/librepcb/project/project.cpp, libs/librepcb/project/project.h, tests/project/projecttest.cpp
`QDomDocument` was not able to produce deterministic XML output because it stores attributes in a `QHash` and thus [their order is random](https://geidav.wordpress.com/2013/02/27/deterministic-attribute-order-in-xml-documents-in-qt-5/). This is very bad for version control systems because the diffs on these XML files is unnecessary large.
After some experiments with other XML libraries I noticed that `QXmlStreamWriter` does not have this issue and thus the generated XML files are deterministic. So I changed our serialization to use `QXmlStreamWriter` instead of `QDomDocument`.
Even if this PR does not introduce canonical XML as requested by #2, I think it should solve the issues with version control systems and thus #2 can be closed anyway.
=> Fix non-deterministic content in XML files

libs/librepcb/common/boarddesignrules.cpp, libs/librepcb/common/boarddesignrules.h, libs/librepcb/common/common.pro, libs/librepcb/common/dialogs/boarddesignrulesdialog.cpp, libs/librepcb/common/fileio/xmldomelement.cpp, libs/librepcb/common/fileio/xmldomelement.h, libs/librepcb/common/units/all_length_units.h, libs/librepcb/common/units/ratio.cpp, libs/librepcb/common/units/ratio.h, tests/common/ratiotest.cpp, tests/tests.pro
Until now, `qreal` floating point numbers were used to represent ratios (e.g. 25%) in the board design rules (for example to specify clearances). Unfortunately there were two issues with that concept:
- The precision of a `qreal` depends on the available FPU (either single precision or double precision). So the design rules were slightly platform dependent.
- The serialization and deserialization of a `qreal` in the class `XmlDomElement` was implemented only for double precision FPUs. Compiling for single precision FPUs was explicitly prevented by a static assert. 
This PR adds a new class `Ratio` which is used to represent, serialize and deserialize ratios in a platform independent way (the underlaying type is `qint32` instead of `qreal`). The precision is always 1ppm.
Thanks to this …
=> Add Ratio class to enable support for single precision FPUs

.gitmodules, tests/common/filedownloadtest.cpp, tests/common/networkrequesttest.cpp, tests/tests.pro
Some unit tests downloaded files from the Internet on every run. This was error prone (e.g. network timeouts, SSL certificate errors, ...) and also not really a good design because these tests were (more or less) non-deterministic.
So according to #126 I created the new repository [librepcb-test-data](https://github.com/LibrePCB/librepcb-test-data) where we can store all data required to run the unit tests. That repository is then added as a submodule to `./tests/data` of this repository.
Now the unit tests "download" their data from the submodule and thus an Internet connection is no longer required to run the tests.
The only drawback is that the unit tests do no longer really download files over HTTP/HTTPS. But I think this could be fixed some time by running a local webserver which …
=> Tests: Use test data from submodule instead of downloading them from the Internet

libs/librepcb/common/graphics/graphicslayer.cpp, libs/librepcb/common/graphics/graphicslayer.h, libs/librepcb/libraryeditor/libraryeditor.cpp, libs/librepcb/libraryeditor/libraryeditor.h, libs/librepcb/project/boards/boardlayerstack.cpp, libs/librepcb/project/boards/boardlayerstack.h, libs/librepcb/project/schematics/schematiclayerprovider.cpp
This adds new layers which can be used to draw hidden grab areas (e.g. polygons) in symbols and footprints. These layers are only visible in the library editor (to make them editable), but not in the schematic and board editors.
Details are described in https://github.com/LibrePCB/LibrePCB/issues/131#issuecomment-260089487.
Fixes #131
=> Add hidden grab area layers

.gitbugtraq
With this [Git Bugtraq](https://github.com/mstrap/bugtraq) configuration, Git clients like [SmartGit](http://www.syntevo.com/smartgit/) are able to display issue and pull request numbers in commit messages as hyperlinks:
=> Add Git Bugtraq Config

libs/librepcb/common/common.pro, libs/librepcb/common/graphics/defaultgraphicslayerprovider.cpp, libs/librepcb/common/graphics/defaultgraphicslayerprovider.h, libs/librepcb/project/circuit/cmd/cmdcomponentinstanceadd.cpp, libs/librepcb/project/circuit/cmd/cmdcomponentinstanceadd.h, libs/librepcb/project/circuit/componentinstance.cpp, libs/librepcb/project/circuit/componentinstance.h, libs/librepcb/projecteditor/boardeditor/unplacedcomponentsdock.cpp, libs/librepcb/projecteditor/cmd/cmdaddcomponenttocircuit.cpp, libs/librepcb/projecteditor/cmd/cmdaddcomponenttocircuit.h, libs/librepcb/projecteditor/dialogs/addcomponentdialog.cpp, libs/librepcb/projecteditor/dialogs/addcomponentdialog.h, libs/librepcb/projecteditor/dialogs/addcomponentdialog.ui, libs/librepcb/projecteditor/schematiceditor/fsm/ses_addcomponent.cpp, libs/librepcb/workspace/library/workspacelibrarydb.cpp, libs/librepcb/workspace/library/workspacelibrarydb.h
When adding a component to the schematic, it was not yet possible to choose a specific device. Devices were not even displayed in the dialog, so the user had no idea which devices (resp. packages) are available for the chosen component.
With this PR, all devices (and their packages) of every listed component are now also shown in the dialog. The user can now even choose a specific device (instead of a component), which is then automatically used when adding the component to the board later. But this is optional, the user can still only choose a component and then choose the exact device some time later.
In addition, this PR also adds a very powerful search field to the dialog, which allows to search in the whole workspace library for components and devices! This way the user is able to …
=> Add more functionality to the component chooser dialog

CONTRIBUTING.md, README.md
As there is now documentation for users available at docs.librepcb.org, I replaced the installation instructions with a link to the documentation. In addition, the demo workspace is no longer required for users, so I removed the corresponding note.
See also: #199, #205
=> Update/improve Readme and Contributing Guidelines

libs/librepcb/libraryeditor/cmp/componentsignallisteditorwidget.cpp, libs/librepcb/libraryeditor/cmp/componentsignallisteditorwidget.h, libs/librepcb/projecteditor/boardeditor/boardeditor.ui, libs/librepcb/projecteditor/boardeditor/boardlayerstacksetupdialog.ui, libs/librepcb/projecteditor/dialogs/projectsettingsdialog.ui, libs/librepcb/projecteditor/schematiceditor/schematiceditor.ui, libs/librepcb/projecteditor/schematiceditor/schematicpagesdock.ui, libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.ui
Fixes #189 
Also makes the board layer stack setup dialog in the board editor resizeable on all platforms by explicitly enabling the size grip
=> Disable unimplemented menu items and icons in the schematic and board editor

libs/librepcb/library/cmp/componentsymbolvariant.cpp, libs/librepcb/library/cmp/componentsymbolvariantitem.h, libs/librepcb/project/schematics/items/si_symbol.cpp
A component (resp. a symbol variant of it) consists of one or more independent symbols (for example an OpAmp could have one power symbol and one amplifier symbol). Such a symbol is currently called `ComponentSymbolVariantItem` in the source code, and `item` in files (resp. `lib_item` in schematic files).
But actually I wonder why I didn't name it `gate`, like other tools do :thinking:
I think `gate` is more expressive than `item` (?), so I would just rename that now...
=> Rename "item" to "gate" in components and schematics

apps/EagleImport/polygonsimplifier.cpp, libs/librepcb/common/geometry/ellipse.cpp, libs/librepcb/common/geometry/ellipse.h, libs/librepcb/common/geometry/hole.cpp, libs/librepcb/common/geometry/hole.h, libs/librepcb/common/geometry/polygon.cpp, libs/librepcb/common/geometry/polygon.h, libs/librepcb/common/geometry/text.cpp, libs/librepcb/common/geometry/text.h, libs/librepcb/eagleimport/packageconverter.cpp, libs/librepcb/eagleimport/symbolconverter.cpp, libs/librepcb/library/librarybaseelement.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_addholes.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawellipse.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawpolygonbase.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawtextbase.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawellipse.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawpolygonbase.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawtextbase.cpp, libs/librepcb/project/boards/board.cpp, libs/librepcb/project/boards/items/bi_polygon.cpp, libs/librepcb/project/boards/items/bi_polygon.h, libs/librepcb/project/metadata/projectmetadata.cpp, libs/librepcb/project/metadata/projectmetadata.h, libs/librepcb/project/schematics/schematic.cpp, libs/librepcb/projecteditor/boardeditor/fsm/bes_drawpolygon.cpp
The handling of UUIDs was not really consistent until now. This PR should fix this with following changes:
Old root node of a symbol: 
```lisp
(librepcb_symbol
(uuid 2da144df-507b-4c51-8f16-174229e04572)
(name "Trimmer Resistor")
```
New root node of a symbol: 
```lisp
(librepcb_symbol 2da144df-507b-4c51-8f16-174229e04572
(name "Trimmer Resistor")
```
This is now consistent with other S-Expression nodes, like a component gate which looks like this:
```lisp
(gate 426e2b17-da88-400b-b1fb-248b24f9c541
(symbol 9b75d0ce-ac4e-4a52-a88a-8777f66d3241)
(pos 0.0 0.0) (rot 0.0) (required true) (suffix "")
```
These objects had no UUID at all until now. But for some planned features, they will also need a UUID.
In addition, I made some other small adjustments of some S-Expression nodes. You can take …
=> Make UUID handling consistent in all files

dev/docker/Dockerfile
this fixes SystemInfoTest.testGetUsername in the docker container
fixes #241 
inspired by https://vsupalov.com/docker-build-time-env-values/
=> Docker: set USER env var

dev/docker/README.md
added some steps I had to perform to get the container working on my system.  May be helpful for other docker newbies
=> Docker: Add "troubleshooting" section to instructions

README.md
add link to doxygen
rename "documentation" -> "user manual"
see LibrePCB/LibrePCB-rfcs#7
=> README: Clarify links to documentation / user manual

libs/librepcb/projecteditor/boardeditor/deviceinstancepropertiesdialog.cpp, libs/librepcb/projecteditor/boardeditor/deviceinstancepropertiesdialog.h
The class was missing an `accept` override.
=> BoardEditor: Save device properties on enter

libs/librepcb/project/boards/board.cpp, libs/librepcb/project/boards/board.h, libs/librepcb/project/boards/boardfabricationoutputsettings.cpp, libs/librepcb/project/boards/boardfabricationoutputsettings.h, libs/librepcb/project/boards/boardgerberexport.cpp, libs/librepcb/project/boards/boardgerberexport.h, libs/librepcb/project/boards/items/bi_footprint.h, libs/librepcb/project/boards/items/bi_polygon.cpp, libs/librepcb/project/boards/items/bi_polygon.h, libs/librepcb/project/boards/items/bi_stroketext.cpp, libs/librepcb/project/boards/items/bi_stroketext.h, libs/librepcb/project/project.pro, libs/librepcb/projecteditor/boardeditor/fabricationoutputdialog.cpp, libs/librepcb/projecteditor/boardeditor/fabricationoutputdialog.h, libs/librepcb/projecteditor/boardeditor/fabricationoutputdialog.ui
~~*Note: Depends on #254, so this one must not yet be merged.*~~
- Make Gerber/Excellon export settings configurable (output path, file suffixes, ...)
- Save these settings in board files
- Add support for inner copper layers
- Allow to generate separate drill files for NPTH and PTH
- Fix wrong export of NPTH drills (they appeared on all layers)
- Make output files reproducible by sorting all objects by their UUID
- Add link to official reference Gerber viewer
This is how the fabrication output generator dialog now looks like:
Fixes #73, #215.
=> Improve PCB fabrication output generator

libs/librepcb/libraryeditor/libraryeditor.ui, libs/librepcb/projecteditor/boardeditor/boardeditor.ui, libs/librepcb/projecteditor/schematiceditor/schematiceditor.ui
I used plain plus and minus for zoom in / out but what is troubling me is that designer did put "&amp;" in every menu. Why is that?
=> Zooming shortcuts for libraryeditor, boardeditor and schematiceditor

.travis.yml, appveyor.yml, ci/build.sh, ci/install_dependencies.sh, ci/qtifw-installer-noninteractive.qs, dist/installer/.gitignore, dist/installer/config/config.xml, dist/installer/packages/librepcb.common/meta/installscript.qs, dist/installer/packages/librepcb.common/meta/package.xml, dist/installer/packages/librepcb.nightly.app/meta/installscript.qs, dist/installer/packages/librepcb.nightly.app/meta/package.xml, dist/installer/packages/librepcb.nightly/meta/package.xml, dist/installer/packages/librepcb.registerfileextensions/meta/installscript.qs, dist/installer/packages/librepcb.registerfileextensions/meta/package.xml, dist/installer/update_metadata.sh, share/mimelnk/application/x-librepcb-project.desktop
With this PR the CI now also builds an installer for Linux, Mac and Windows. The installer can be used to install and even to update LibrePCB to the latest version. This is especially useful for Windows which doesn't have a package manager.
The installers are built with the [Qt Installer Framework](https://doc.qt.io/qtinstallerframework/index.html) which is pretty cool. On Windows the installer also (optionally) registers LibrePCB as handler for *.lpp files, so project files can be opened with a double click in the explorer. For Linux and Mac I did not (yet) implement it, maybe I'll also give it a try...
The installers can currently be downloaded from here: https://download.librepcb.org/nightly_builds/installer/
Updates are hosted separately, the installer fetches them automatically from …
=> Provide installer for nightly builds

libs/librepcb/projecteditor/boardeditor/fsm/bes_drawplane.cpp, libs/librepcb/projecteditor/boardeditor/fsm/bes_drawpolygon.cpp, libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/ses_drawwire.cpp
Fixes a lot of `warning: catching polymorphic type ‘class
librepcb::Exception’ by value [-Wcatch-value=]` warnings.
=> Fix catch by value of polymorphic exceptions

ci/build.sh, libs/librepcb/common/application.cpp
Adds the "share" directory to the macOS application bundle to make runtime resources available.
Hopefully fixes #274.
=> Fix macOS deployment issue causing a crash

libs/librepcb/common/network/networkrequestbase.cpp, libs/librepcb/common/network/repository.cpp, libs/librepcb/librarymanager/repositorylibrarylistwidgetitem.cpp
We have updated the API to fetch the list of available libraries because the old API did not allow to fetch only libraries which have a compatible file format.
Now the request contains the file format version number in the URL, so the server is able to deliver only libraries which are compatible with the client's application version. For file format 0.1 the URL is now https://api.librepcb.org/api/v1/libraries/v0.1 instead of https://api.librepcb.org/api/v1/libraries.
Links:
- Motivation/discussion about this change: https://github.com/LibrePCB/librepcb-api/issues/5
- Documentation of new API: https://docs.librepcb.org/_branches/add_api_documentation/#api
- Pull request for documentation: https://github.com/LibrePCB/librepcb-doc/pull/16
=> Update to new API for fetching libraries

.gitmodules, libs/librepcb/common/application.cpp, libs/librepcb/common/application.h, libs/librepcb/common/graphics/primitivetextgraphicsitem.cpp, libs/librepcb/library/pkg/footprintpadpreviewgraphicsitem.cpp, libs/librepcb/library/sym/symbolpinpreviewgraphicsitem.cpp, libs/librepcb/library/sym/symbolpreviewgraphicsitem.cpp, libs/librepcb/project/boards/graphicsitems/bgi_footprintpad.cpp, libs/librepcb/project/boards/graphicsitems/bgi_via.cpp, libs/librepcb/project/schematics/graphicsitems/sgi_netlabel.cpp, libs/librepcb/project/schematics/graphicsitems/sgi_netline.cpp, libs/librepcb/project/schematics/graphicsitems/sgi_symbol.cpp, libs/librepcb/project/schematics/graphicsitems/sgi_symbolpin.cpp
This makes LibrePCB using [Noto Fonts](https://www.google.com/get/noto/) for schematics. To ensure consistent look over all platforms, the fonts are bundled together with LibrePCB. So the look of schematics no longer depends on the available system fonts.
Preview:
Fixes #153.
=> Bundle fonts used in schematics together with LibrePCB

dev/doxygen/pages/project.md, libs/librepcb/project/boards/board.h, libs/librepcb/project/boards/boardusersettings.cpp, libs/librepcb/project/boards/boardusersettings.h, libs/librepcb/project/circuit/circuit.cpp, libs/librepcb/project/circuit/circuit.h, libs/librepcb/project/erc/ercmsglist.cpp, libs/librepcb/project/erc/ercmsglist.h, libs/librepcb/project/metadata/projectmetadata.cpp, libs/librepcb/project/metadata/projectmetadata.h, libs/librepcb/project/project.cpp, libs/librepcb/project/settings/projectsettings.cpp, libs/librepcb/project/settings/projectsettings.h, share/librepcb/project/gitignore_template, tests/project/projecttest.cpp
As discussed and decided in https://github.com/LibrePCB/librepcb-rfcs/issues/17.
Changes project directory structure from this:
```
MyProject
├── MyProject.lpp
├── boards
│   ├── MyBoard1.lp
│   └── MyBoard2.lp
├── core
│   ├── boards.lp
│   ├── circuit.lp
│   ├── erc.lp
│   ├── metadata.lp
│   ├── schematics.lp
│   └── settings.lp
├── library
│   └── <<< all library elements used in the project >>>
├── output
│   └── <<< all generated files, e.g. Gerber files, PDF, ... >>>
├── resources
│   └── <<< various resources used in the project, e.g. fonts >>>
├── schematics
│   ├── MySchematicPage1.lp
│   └── MySchematicPage2.lp
└── user
└── boards
├── MyBoard1.lp
└── MyBoard2.lp
```
to this:
```
MyProject
├── MyProject.lpp
├── boards
│   ├── boards.lp
│   ├── MyBoard1
│   │   ├── board.lp
│   │ …
```
=> Update project directory structure

apps/librepcb/controlpanel/controlpanel.cpp, apps/librepcb/controlpanel/controlpanel.h, libs/librepcb/common/application.cpp, libs/librepcb/common/application.h, libs/librepcb/common/common.pro, libs/librepcb/common/dialogs/aboutdialog.cpp, libs/librepcb/common/dialogs/aboutdialog.h, libs/librepcb/common/dialogs/aboutdialog.ui, libs/librepcb/libraryeditor/libraryeditor.cpp, libs/librepcb/projecteditor/boardeditor/boardeditor.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp
This is a new about dialog for LibrePCB. Fixes most of #17.
Checklist from that issue:
Here's a screenshot:
(The missing window decorations are due to my window manager.)
@ubruhin do you think we should add tabs, for things like "contributing" and the author list?b
=> About Dialog

libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_addpads.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_addpads.h, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawtextbase.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawtextbase.h, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_addpins.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_addpins.h, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawtextbase.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawtextbase.h
=> Library Editor: Rotate pins, pads and texts with right-click

apps/apps.pro, apps/librepcb-cli/commandlineinterface.cpp, apps/librepcb-cli/commandlineinterface.h, apps/librepcb-cli/librepcb-cli.pro, apps/librepcb-cli/main.cpp, apps/librepcb/controlpanel/controlpanel.cpp, apps/librepcb/projectlibraryupdater/projectlibraryupdater.cpp, ci/build.sh, ci/test.sh, libs/librepcb/project/boards/boardgerberexport.cpp, libs/librepcb/project/boards/boardgerberexport.h, libs/librepcb/project/project.cpp, libs/librepcb/project/project.h, libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp, tests/unittests/project/boards/boardplanefragmentsbuildertest.cpp, tests/unittests/project/projecttest.cpp
This adds a first version of a `librepcb-cli` application which is intended to automate some frequently used tasks. It's especially useful for Continuous Integration of LibrePCB projects (e.g. with Travis-CI).
Currently it supports to load a project and...
- Report ERC messages (report failure if there are non-approved messages)
- Export schematics as PDF
- Export boards as Gerber/Excellon
For usage instructions see documentation here: https://docs.librepcb.org/_branches/add-cli/#cli
=> Add command-line tool "librepcb-cli"

README.md
people who install recommended packages may not need to explicitely install this
=> README.md: debian: add dependency libqt5opengl5-dev

apps/EagleImport/mainwindow.ui, apps/WorkspaceLibraryUpdater/mainwindow.ui, apps/librepcb/firstrunwizard/firstrunwizardpage_workspacepath.ui, libs/librepcb/libraryeditor/cmp/componenteditorwidget.ui, libs/librepcb/libraryeditor/cmpcat/componentcategoryeditorwidget.ui, libs/librepcb/libraryeditor/common/componentchooserdialog.ui, libs/librepcb/libraryeditor/common/packagechooserdialog.ui, libs/librepcb/libraryeditor/common/symbolchooserdialog.ui, libs/librepcb/libraryeditor/dev/deviceeditorwidget.ui, libs/librepcb/libraryeditor/lib/libraryoverviewwidget.ui, libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_deviceproperties.ui, libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_entermetadata.ui, libs/librepcb/libraryeditor/pkg/packageeditorwidget.ui, libs/librepcb/libraryeditor/pkgcat/packagecategoryeditorwidget.ui, libs/librepcb/libraryeditor/sym/dialogs/symbolpinpropertiesdialog.ui, libs/librepcb/libraryeditor/sym/symboleditorwidget.ui, libs/librepcb/librarymanager/libraryinfowidget.ui, libs/librepcb/librarymanager/librarylistwidgetitem.ui, libs/librepcb/projecteditor/boardeditor/boardlayersdock.ui, libs/librepcb/projecteditor/boardeditor/boardplanepropertiesdialog.ui, libs/librepcb/projecteditor/boardeditor/boardviapropertiesdialog.ui, libs/librepcb/projecteditor/boardeditor/deviceinstancepropertiesdialog.ui, libs/librepcb/projecteditor/dialogs/projectpropertieseditordialog.ui, libs/librepcb/projecteditor/newprojectwizard/newprojectwizardpage_initialization.ui, libs/librepcb/projecteditor/newprojectwizard/newprojectwizardpage_metadata.ui, libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.ui
When creating a new dialog, please make sure to remove the "translatable" checkbox when necessary.
=> Mark many strings as non-translatable

README.md
A lot of times when pulling, compilation fails afterwards because the
submodules aren't up to date.
=> Add instructions about updating the repository

libs/librepcb/library/librarybaseelement.cpp, libs/librepcb/project/library/projectlibrary.cpp, libs/librepcb/project/library/projectlibrary.h, tests/unittests/library/librarybaseelementtest.cpp, tests/unittests/project/library/projectlibrarytest.cpp, tests/unittests/unittests.pro
- Add support for saving project libraries to backup directory "library~" instead of "library". Now the backup/restore feature of projects should also work properly for the project library. Fixes #47.
- Fix possible error when saving the project library after replacing a library element (remove element and add another one with same UUID). Fixes #312.
- Allow library elements to be saved into empty directories. Sometimes empty directories are not cleaned up properly (for example by Git), so we should handle empty directories just like non-existing directories to avoid possible failures.
- Added some unit tests to avoid regression.
=> Refactor ProjectLibrary to fix several issues

libs/librepcb/common/fileio/filepath.cpp, tests/unittests/common/filepathtest.cpp
`FilePath::isRoot()` did not work on Windows (it always returned `false`, even for a root path like "C:/"). The root cause of this is that `FilePath` strips trailing slashes, so "C:/" is converted to "C:", and it seems that `QDir::isRoot()` does not work without the trailing slash. This could even lead to an application crash (see #305).
- Make `FilePath` appending a slash on Windows drive paths (i.e. represent drives by "X:/" instead of "X:" where X is the drive letter). This automatically fixes the application crash.
- Add/update unit tests of `FilePath` to avoid regression.
Fixes #305
=> Fix broken FilePath::isRoot() on Windows, possibly causing application crash

libs/librepcb/libraryeditor/cmp/componentsignallisteditorwidget.cpp, libs/librepcb/projecteditor/dialogs/addcomponentdialog.cpp, libs/librepcb/projecteditor/dialogs/addcomponentdialog.ui
- Component Editor: Fix unreadable text in signals list
- Increasing the minimum row width to 17 pixels seems to fix the unreadable text on Windows.
- Fixes #304 
- AddComponentDialog: Fix size glitches on Windows
- Reorganize layout: Replace some HBox/VBoxLayouts by GridLayout.
- Always show (empty) device/package, even if no device selected.
- Fixes #307
=> Fix GUI issues on Windows

libs/librepcb/common/geometry/circle.cpp, libs/librepcb/common/geometry/hole.cpp, libs/librepcb/common/geometry/polygon.cpp, libs/librepcb/common/geometry/stroketext.cpp, libs/librepcb/common/geometry/text.cpp, libs/librepcb/common/geometry/vertex.cpp, libs/librepcb/library/cmp/componentpinsignalmap.cpp, libs/librepcb/library/cmp/componentsymbolvariantitem.cpp, libs/librepcb/library/dev/devicepadsignalmap.cpp, libs/librepcb/library/pkg/footprintpad.cpp, libs/librepcb/library/sym/symbolpin.cpp, libs/librepcb/project/boards/items/bi_device.cpp, libs/librepcb/project/boards/items/bi_netpoint.cpp, libs/librepcb/project/boards/items/bi_via.cpp, libs/librepcb/project/circuit/componentinstance.cpp, libs/librepcb/project/schematics/items/si_netlabel.cpp, libs/librepcb/project/schematics/items/si_netpoint.cpp, libs/librepcb/project/schematics/items/si_symbol.cpp
Some nodes in our S-Expression files were written as abbreviations (e.g. "pos" instead of "position"), while most aren't. For consistency and readability, these abbreviations are now also replaced with their long names.
Here is the corresponding diff on the demo workspace: https://github.com/LibrePCB/demo-workspace/commit/f25e364b975ca3a70bf34d60a1874531ff8a40cc
=> Stop using abbreviations in S-Expression files

apps/librepcb/firstrunwizard/firstrunwizard.cpp, apps/librepcb/firstrunwizard/firstrunwizardpage_workspacepath.cpp, apps/librepcb/firstrunwizard/firstrunwizardpage_workspacesettings.cpp, apps/librepcb/firstrunwizard/firstrunwizardpage_workspacesettings.h, apps/librepcb/firstrunwizard/firstrunwizardpage_workspacesettings.ui, apps/librepcb/librepcb.pro, apps/librepcb/main.cpp, libs/librepcb/libraryeditor/newelementwizard/newelementwizardcontext.cpp, libs/librepcb/librarymanager/addlibrarywidget.cpp, libs/librepcb/project/metadata/projectmetadata.cpp, libs/librepcb/projecteditor/newprojectwizard/newprojectwizard.cpp, libs/librepcb/projecteditor/newprojectwizard/newprojectwizardpage_metadata.cpp, libs/librepcb/projecteditor/newprojectwizard/newprojectwizardpage_metadata.h, libs/librepcb/workspace/settings/items/wsi_user.cpp, libs/librepcb/workspace/settings/items/wsi_user.h, libs/librepcb/workspace/settings/workspacesettings.cpp, libs/librepcb/workspace/settings/workspacesettings.h, libs/librepcb/workspace/settings/workspacesettingsdialog.cpp, libs/librepcb/workspace/workspace.pro, tests/unittests/project/projecttest.cpp
See #322 and https://github.com/LibrePCB/librepcb-rfcs/issues/22.
New page in first run wizard:
New entry in workspace settings dialog:
Fixes #322.
=> Store default author name in workspace settings

.gitmodules, README.md, dev/docker/Dockerfile, dev/docker/LibrePCB.conf
As the file format is getting more and more stable, I think we don't need it anymore as a submodule. If still needed for testing purposes, it could be cloned separately.
=> Remove submodule "dev/demo-workspace"

appveyor.yml, ci/install_dependencies.sh
Unfortunately there are no official `ccache` binaries available, and building from source fails on Windows. Anyone interested in providing trustworthy binaries? If not, I'll use some random, unofficial binaries ;)
`ccache` reduces our AppVeyor build time from ~30min to ~10min!
=> AppVeyor: Use ccache to speed up builds

libs/librepcb/project/schematics/graphicsitems/sgi_symbol.cpp
I don't really know what I'm doing, but this seems to do the trick.
Fixes #311.
@ubruhin does the `mBoundingRect` need to be updated too? Do you have some high-level documentation on how all this code works, or what it does?
=> Allow dragging symbols by circular grab areas

apps/librepcb/controlpanel/controlpanel.cpp, apps/librepcb/firstrunwizard/firstrunwizardpage_workspacepath.cpp, ci/install_dependencies.sh, ci/test.sh, libs/librepcb/common/common.pro, libs/librepcb/common/dialogs/filedialog.cpp, libs/librepcb/common/dialogs/filedialog.h, libs/librepcb/libraryeditor/lib/libraryoverviewwidget.cpp, libs/librepcb/projecteditor/boardeditor/boardeditor.cpp, libs/librepcb/projecteditor/newprojectwizard/newprojectwizardpage_metadata.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp, libs/librepcb/workspace/workspace.cpp, tests/README.md, tests/funq/.gitignore, tests/funq/README.md, tests/funq/aliases, tests/funq/conftest.py, tests/funq/controlpanel/test_create_project.py, tests/funq/controlpanel/test_open_librarymanager.py, tests/funq/controlpanel/test_open_project.py, tests/funq/libraryeditor/conftest.py, tests/funq/libraryeditor/test_open.py, tests/funq/librarymanager/test_create_local_library.py, tests/funq/librarymanager/test_install_remote_libraries.py, tests/funq/requirements.txt, tests/funq/setup.cfg
This adds an initial setup to perform automated functional tests ("GUI tests") using [funq](https://github.com/parkouss/funq) and [pytest](https://docs.pytest.org/en/latest/index.html). I think such tests are very useful to keep the quality and stability of LibrePCB as high as possible. So it would be great to add more and more tests in future.
There were some small changes required in the source code of LibrePCB to make `funq` working properly:
Tests require to control local application settings (`~/.config/LibrePCB/` on Linux). On Windows, Qt uses the Registry for these settings, but this is a mess for testing. I think the Registry is bullshit anyway, so let's use INI instead. Now settings have the same format on all platforms.
This is required to make `libFunq` initializing as early as …
=> Add initial setup for automated functional tests

libs/librepcb/project/schematics/cmd/cmdsymbolinstanceedit.cpp, libs/librepcb/project/schematics/cmd/cmdsymbolinstanceedit.h, libs/librepcb/project/schematics/graphicsitems/sgi_symbol.cpp, libs/librepcb/project/schematics/graphicsitems/sgi_symbolpin.cpp, libs/librepcb/project/schematics/graphicsitems/sgi_symbolpin.h, libs/librepcb/project/schematics/items/si_symbol.cpp, libs/librepcb/project/schematics/items/si_symbol.h, libs/librepcb/project/schematics/items/si_symbolpin.cpp, libs/librepcb/project/schematics/items/si_symbolpin.h, libs/librepcb/projecteditor/cmd/cmdmirrorselectedschematicitems.cpp, libs/librepcb/projecteditor/cmd/cmdmirrorselectedschematicitems.h, libs/librepcb/projecteditor/projecteditor.pro, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorevent.h, libs/librepcb/projecteditor/schematiceditor/fsm/ses_select.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/ses_select.h, libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.ui, libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.cpp, libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.ui
This enables flipping around symbol instances in the schematic editor.
(note: vertical flipping = horizontal flip + 180° rotate)
=> Mirror support for schematic

libs/librepcb/projecteditor/dialogs/addcomponentdialog.ui
To place a symbol from the 'Add Component' dialog, the user currently
has to select the desired symbol from the list and click 'OK'. This
change allows users to place a symbol by double-clicking the symbol in
the list without clicking the 'OK' button.
Fixes #344
=> AddComponentDialog: place a component by double-clicking list item

libs/librepcb/common/attributes/attrtypecapacitance.cpp, libs/librepcb/common/attributes/attrtypefrequency.cpp, libs/librepcb/common/attributes/attrtypeinductance.cpp, libs/librepcb/common/attributes/attrtyperesistance.cpp, libs/librepcb/common/attributes/attrtypevoltage.cpp, libs/librepcb/common/dialogs/boarddesignrulesdialog.ui, libs/librepcb/common/dialogs/stroketextpropertiesdialog.ui, libs/librepcb/common/units/lengthunit.cpp, libs/librepcb/projecteditor/boardeditor/boardviapropertiesdialog.ui, libs/librepcb/projecteditor/boardeditor/deviceinstancepropertiesdialog.ui, libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.ui
Please remove the "translatable" flag for units and unit-suffixes when creating new dialogs - saves time for the translators :slightly_smiling_face:
=> Mark many strings as nontranslatable

libs/librepcb/common/units/length.cpp, libs/librepcb/common/units/length.h, tests/unittests/common/lengthsnaptest.cpp, tests/unittests/common/lengthtest.cpp, tests/unittests/unittests.pro
Maybe its worth defining `LengthBaseU_t` outside the functions?
Regarding tests, I don't know how to pass different test data to different test methods from the same class.
=> Length: Reimplement mapNmToGrid() without using floating point

dev/clang-format/Dockerfile, dev/doxygen/pages/code_style_guide.md, dev/format_code.sh
Are you interested in this?
It's a bit of a hack but seems to work nicely. Simply run the formatting script with `--docker`.
=> Allow running clang-format in Docker container

.clang-format, apps/UuidGenerator/main.cpp, apps/UuidGenerator/mainwindow.cpp, apps/UuidGenerator/mainwindow.h, apps/WorkspaceLibraryUpdater/mainwindow.h, apps/librepcb/controlpanel/controlpanel.cpp, apps/librepcb/firstrunwizard/firstrunwizard.cpp, apps/librepcb/firstrunwizard/firstrunwizardpage_welcome.cpp, apps/librepcb/firstrunwizard/firstrunwizardpage_welcome.h, apps/librepcb/firstrunwizard/firstrunwizardpage_workspacepath.cpp, apps/librepcb/firstrunwizard/firstrunwizardpage_workspacepath.h, apps/librepcb/firstrunwizard/firstrunwizardpage_workspacesettings.cpp, apps/librepcb/firstrunwizard/firstrunwizardpage_workspacesettings.h, dev/clang-format/Dockerfile, dev/format_code.sh, libs/librepcb/common/dialogs/aboutdialog.cpp, libs/librepcb/common/dialogs/filedialog.cpp, libs/librepcb/common/dialogs/filedialog.h, libs/librepcb/common/geometry/path.cpp, libs/librepcb/common/toolbox.h, libs/librepcb/common/units/angle.cpp, libs/librepcb/common/units/length.cpp, libs/librepcb/common/units/ratio.cpp, libs/librepcb/projecteditor/boardeditor/boardeditor.cpp, libs/librepcb/projecteditor/newprojectwizard/newprojectwizardpage_versioncontrol.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp, tests/unittests/main.cpp
I noticed inconsistent handling of pointer alignment in #388 which clang-format did not fix. This PR makes clang-format fixing it:
- `.clang-format`: Disable `DerivePointerAlignment` to enforce pointer alignment style for all files.
- Add parameter "--all" to `dev/format_code.sh` to format all files, not only modified ones.
- Also format *.pro files with `dev/format_code.sh` to avoid inconsistent project files.
- Reformat whole code base with clang-format to fix all inconsistencies.
@dbrgn Would be good to merge this before #388, then you can run `dev/format_code.sh` again on your branch to fix the style issues :)
=> Fix inconsistent coding style

libs/librepcb/common/common.pro, libs/librepcb/common/widgets/tabwidget.cpp, libs/librepcb/common/widgets/tabwidget.h, libs/librepcb/libraryeditor/libraryeditor.cpp, libs/librepcb/libraryeditor/libraryeditor.h, libs/librepcb/libraryeditor/libraryeditor.ui
This has bugged me for a while :slightly_smiling_face: 
Code is loosely based on https://github.com/mbunkus/mkvtoolnix/commit/4c05f4263372153539535bd6bd401045c8f2ed61.
=> Make tabs closable with middle mouse button

libs/librepcb/libraryeditor/cmp/componentsignallisteditorwidget.cpp
componentSignalListedEditorWidget: Fix wrong behaviour when name of
signal contains forbidden characters.
Updating signal table when name and name without forbidden characters are
the same.
Fixes #392
=> Library Editor: Fix possibly outdated information in component signal editor

libs/librepcb/workspace/library/workspacelibrarydb.cpp, libs/librepcb/workspace/library/workspacelibrarydb.h, libs/librepcb/workspace/library/workspacelibraryscanner.cpp, libs/librepcb/workspace/library/workspacelibraryscanner.h
Until now, the workspace library database is stored in the file
"cache.sqlite" in the workspace. And the database itself contains a
version number which is intended to be incremented if we change the
database layout.
But if you use two different LibrePCB application versions on the same
workspace, this doesn't work well in every case. The newer application
would upgrade the database on the first application start, but the older
application may no longer be able to work with that database version. So
generally we must introduce database format changes only with new major
versions of the application, which decreases our flexibility in minor
releases.
This change puts the database version number into the filename of the
database, i.e. the file "cache.sqlite" will be renamed to …
=> Use separate *.sqlite files for each database version

apps/librepcb/controlpanel/controlpanel.cpp, apps/librepcb/controlpanel/controlpanel.h, libs/librepcb/libraryeditor/lib/librarylisteditorwidget.cpp, libs/librepcb/libraryeditor/lib/librarylisteditorwidget.h, libs/librepcb/libraryeditor/lib/libraryoverviewwidget.cpp, libs/librepcb/libraryeditor/libraryeditor.cpp, libs/librepcb/librarymanager/addlibrarywidget.cpp, libs/librepcb/librarymanager/addlibrarywidget.h, libs/librepcb/librarymanager/libraryinfowidget.cpp, libs/librepcb/librarymanager/libraryinfowidget.h, libs/librepcb/librarymanager/librarylistwidgetitem.cpp, libs/librepcb/librarymanager/librarylistwidgetitem.h, libs/librepcb/librarymanager/librarymanager.cpp, libs/librepcb/librarymanager/librarymanager.h, libs/librepcb/librarymanager/repositorylibrarylistwidgetitem.cpp, libs/librepcb/librarymanager/repositorylibrarylistwidgetitem.h, libs/librepcb/projecteditor/boardeditor/boardeditor.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp, libs/librepcb/workspace/library/workspacelibrarydb.cpp, libs/librepcb/workspace/library/workspacelibrarydb.h, libs/librepcb/workspace/library/workspacelibraryscanner.cpp, libs/librepcb/workspace/library/workspacelibraryscanner.h, libs/librepcb/workspace/workspace.cpp, libs/librepcb/workspace/workspace.h, tests/funq/librarymanager/test_install_remote_libraries.py
- Store PNG icon of libraries in database. Used to get library icons without loading the libraries (useful for the library manager).
- Use "ON DELETE CASCADE" for foreign keys. Required to allow removing single libraries from the database without generating a foreign key error. Used to speed-up scanning of installed libraries.
Add support for reading more data from the database, especially library metadata.
WorkspaceLibraryScanner now also scans which libraries are installed instead of using the libraries loaded by the Workspace object. This allows to add/remove/update workspace libraries without notifying the Workspace object about the exact changes. To get faster feedback of the changes (e.g. to update the widgets of the library manager), the scanner now emits a signal after the library …
=> Refactor workspace libraries handling

libs/librepcb/librarymanager/addlibrarywidget.ui, libs/librepcb/librarymanager/librarylistwidgetitem.cpp, libs/librepcb/librarymanager/librarylistwidgetitem.ui, libs/librepcb/librarymanager/librarymanager.cpp, libs/librepcb/librarymanager/librarymanager.ui, libs/librepcb/librarymanager/repositorylibrarylistwidgetitem.cpp, libs/librepcb/librarymanager/repositorylibrarylistwidgetitem.ui, tests/funq/librarymanager/test_install_remote_libraries.py
- Make it better usable on small screens (required to create nice looking screenshots for website and documentation :wink:)
- Crop long texts to avoid strange looking layouts by ignoring widget
size hint and/or enabling word wrap in labels
- Various other small improvements
- Save/restore window position and size
Before:
After:
=> LibraryManager: Various small layout improvements

libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawpolygonbase.cpp
As per https://github.com/LibrePCB/librepcb-doc/pull/35
=> Package editor: Change default line width to 0.2mm

libs/librepcb/librarymanager/addlibrarywidget.cpp, libs/librepcb/librarymanager/addlibrarywidget.ui
As there are more and more libraries, a "select all" checkbox is handy to save time :)
=> Library manager: Add "select all" checkbox

libs/librepcb/libraryeditor/libraryeditor.cpp, libs/librepcb/libraryeditor/libraryeditor.ui
Instead of always naming the action "Save element", show the actual element name in the action's title, e.g. "Save 'NE555'".
This is the last change needed to close #384.
Fixes #384.
=> Library Editor: Display element name in "save" action

libs/librepcb/workspace/library/cat/categorytreeitem.cpp, libs/librepcb/workspace/library/cat/categorytreeitem.h
All the information needed to build category tree views (e.g. in the "Add Component" dialog) is available in the workspace library database, which is much faster than loading the categories from the file system. So let's use the database ;)
=> Load category tree from database instead of file system

libs/librepcb/libraryeditor/lib/libraryoverviewwidget.cpp, libs/librepcb/libraryeditor/lib/libraryoverviewwidget.h, libs/librepcb/libraryeditor/lib/libraryoverviewwidget.ui, libs/librepcb/libraryeditor/libraryeditor.cpp, libs/librepcb/libraryeditor/libraryeditor.h, libs/librepcb/libraryeditor/newelementwizard/newelementwizard.cpp, libs/librepcb/libraryeditor/newelementwizard/newelementwizard.h, libs/librepcb/libraryeditor/newelementwizard/newelementwizardcontext.cpp, libs/librepcb/libraryeditor/newelementwizard/newelementwizardcontext.h, libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_choosetype.cpp, libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_copyfrom.cpp, libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_copyfrom.h, tests/funq/aliases, tests/funq/libraryeditor/test_overview_tab.py
- Allow multi selection in lists (to edit or remove multiple elements at once)
- Enable "delete" shortcut to remove elements with the keyboard shortcut
- Add new context menu items to the library editor overview tab:
- "Edit": Same as double click
- "Copy": To open the "New Library Element" dialog, prefilled with the values of the selected element (disabled if multiple elements are selected)
- Add some more functional tests
Fixes #347
=> Library Editor: Extend functionality of overview lists

libs/librepcb/common/sqlitedatabase.cpp, libs/librepcb/common/sqlitedatabase.h, libs/librepcb/libraryeditor/common/categorychooserdialog.cpp, libs/librepcb/libraryeditor/common/componentchooserdialog.cpp, libs/librepcb/libraryeditor/common/packagechooserdialog.cpp, libs/librepcb/libraryeditor/common/symbolchooserdialog.cpp, libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_copyfrom.cpp, libs/librepcb/projecteditor/dialogs/addcomponentdialog.cpp, libs/librepcb/workspace/library/cat/categorytreeitem.cpp, libs/librepcb/workspace/library/cat/categorytreeitem.h, libs/librepcb/workspace/library/cat/categorytreemodel.cpp, libs/librepcb/workspace/library/cat/categorytreemodel.h, libs/librepcb/workspace/library/workspacelibrarydb.cpp, libs/librepcb/workspace/library/workspacelibrarydb.h, tests/funq/libraryeditor/test_copy_package.py
See #378. In addition to the "Add component"-dialog in the schematic editor, empty categories are also hidden in the library editor, depending on the use-case of the category tree. For example when selecting a device, you will now only see categories which actually contain devices.
Fixes #378.
=> Filter all category trees to show only relevant entries

libs/librepcb/libraryeditor/dev/padsignalmapeditorwidget.cpp
=> Device editor: Sort component signal dropdown by name

libs/librepcb/library/cmp/component.cpp, libs/librepcb/library/cmp/component.h, libs/librepcb/projecteditor/boardeditor/boardeditor.ui, libs/librepcb/projecteditor/dialogs/addcomponentdialog.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.ui
- Enable project settings menu item in board/schematic editors (I guess they were hidden by accident).
- `AddComponentDialog`: Pre-select symbol variant by project norms
Now you can set your preferred norm in the project settings dialog:
And then the "Add Component"-dialog automatically pre-selects the component symbol variant according the specified norm:
Fixes #396
=> AddComponentDialog: Pre-select symbol variant by project norms

libs/librepcb/projecteditor/boardeditor/boardeditor.cpp, libs/librepcb/projecteditor/boardeditor/boardeditor.h
=> Board editor: Fix empty view after removing a board

apps/librepcb-cli/commandlineinterface.cpp, apps/librepcb-cli/commandlineinterface.h, libs/librepcb/project/boards/boardgerberexport.cpp, libs/librepcb/project/boards/boardgerberexport.h, libs/librepcb/projecteditor/boardeditor/fabricationoutputdialog.cpp, tests/cli/open-project/test_export_pcb_fabrication_data.py
Adds the CLI argument `--pcb-fabrication-settings=<file>` to specify a *.lp file with custom fabrication output settings, overriding the settings stored in the board itself. This is useful for PCB manufacturers to generate Gerber files from LibrePCB projects with the settings they need ;)
=> CLI: Allow to specify custom fabrication output settings

libs/librepcb/projecteditor/docks/ercmsgdock.ui
With Qt 5.12 the text in the ERC dock widget gets wrapped, but the height is not adjusted accordingly, thus the text is unreadable. Disabling word wrap fixes this.
Fixes #436
=> Schematic editor: Fix unreadable text in ERC dock with Qt 5.12

libs/librepcb/libraryeditor/common/componentchooserdialog.ui, libs/librepcb/libraryeditor/common/packagechooserdialog.ui, libs/librepcb/libraryeditor/common/symbolchooserdialog.ui
On Windows some dialogs were way too high which was very cumbersome. With this layout refactoring the issues seems to be fixed.
=> Library Editor: Fix height issues of various dialogs

libs/librepcb/libraryeditor/common/componentchooserdialog.cpp, libs/librepcb/libraryeditor/common/componentchooserdialog.h, libs/librepcb/libraryeditor/common/componentchooserdialog.ui, libs/librepcb/libraryeditor/common/packagechooserdialog.cpp, libs/librepcb/libraryeditor/common/packagechooserdialog.h, libs/librepcb/libraryeditor/common/packagechooserdialog.ui, libs/librepcb/libraryeditor/common/symbolchooserdialog.cpp, libs/librepcb/libraryeditor/common/symbolchooserdialog.h, libs/librepcb/libraryeditor/common/symbolchooserdialog.ui, libs/librepcb/workspace/library/workspacelibrarydb.cpp, libs/librepcb/workspace/library/workspacelibrarydb.h
In the library editor there are various locations where you need to choose a symbol, package or component with a dialog. This PR adds a search text field to these dialogs to help finding elements, basically just like we already have it in the "Add Component" dialog in the schematic editor.
=> Add search field to symbol/package/component chooser dialogs

libs/librepcb/projecteditor/dialogs/addcomponentdialog.cpp, libs/librepcb/projecteditor/dialogs/addcomponentdialog.h, libs/librepcb/workspace/library/workspacelibrarydb.cpp, libs/librepcb/workspace/library/workspacelibrarydb.h
Makes the search function in the "Add Component" dialog of the schematic editor much more powerful:
- Also find components which do not have devices (previously such components were not found).
- If the component doesn't match the search term:
- Only show its devices which match the term (previously, all devices were shown).
- Expand the tree item to directly show the matched devices (previously all tree items were collapsed)
=> AddComponentDialog: Refactor and improve search

libs/librepcb/libraryeditor/lib/libraryoverviewwidget.cpp, libs/librepcb/libraryeditor/lib/libraryoverviewwidget.h, libs/librepcb/libraryeditor/libraryeditor.cpp, libs/librepcb/libraryeditor/libraryeditor.h
The "copy" context menu action implies that there's a paste action.
However, there is no such thing. What really happens is a duplication, a
new library element is created from the current element.
=> Library editor overview: Rename "copy" to "duplicate"

libs/librepcb/libraryeditor/sym/dialogs/symbolpinpropertiesdialog.cpp
Preselecting the pin name improves the workflow when customizing pins: double-click pin, enter new name and finish with Enter. The deletion or manual selection of the previous name is no longer necessary.
=> Library Editor: Preselect pin name when opening the pin properties dialog

libs/librepcb/common/common.pro, libs/librepcb/common/norms.h, libs/librepcb/libraryeditor/cmp/componentsymbolvarianteditdialog.cpp, libs/librepcb/libraryeditor/cmp/componentsymbolvarianteditdialog.ui, libs/librepcb/projecteditor/dialogs/projectsettingsdialog.cpp, libs/librepcb/workspace/settings/items/wsi_librarynormorder.cpp
See discussion here: https://librepcb.discourse.group/t/how-do-i-add-ieee-315-to-my-preferences/88
I'm not completely happy with this solution, but it's for sure better than the current situation. IEC 60617 and IEEE 315 are the only two norms used in our official libraries so far, thus I think it makes sense to have these norms as suggestions in the workspace/project settings dialogs.
I also updated the component symbol variant editor dialog to use a combobox instead of a text field for specifying the norm, this way it should be more intuitive and easier to choose a norm.
=> Change predefined norms to "IEC 60617" + "IEEE 315"

libs/librepcb/projecteditor/boardeditor/fsm/bes_select.cpp
After double-clicking on a footprint in the board editor (which opens the properties dialog), the editor changed back to the last active tool, which is of course not intended. Reason was a wrong return value of the state machine...
=> BoardEditor: Fix unintended tool change after double click on footprint

libs/librepcb/common/graphics/graphicsview.cpp
Previously when pressing Ctrl it would always scroll vertically even
when scrolling horizontally.
=> Enable scrolling with both axis when pressing Ctrl

libs/librepcb/library/pkg/packagepadlistmodel.cpp, libs/librepcb/library/pkg/packagepadlistmodel.h
If no pad name is set search for the next free numerical one.
Fixes #469
=> Automatically choose next free numerical pad name

libs/librepcb/common/signalslot.h, tests/unittests/common/signalslottest.cpp, tests/unittests/unittests.pro
In some rare cases it was possible to crash the application because slots were detached from signals inside the callback of a slot, probably because following loop was not safe for modifying the `std::set` while iterating over it:
https://github.com/LibrePCB/LibrePCB/blob/7437d2898cb3453d86cdc246e04d9c0b8095da22/libs/librepcb/common/signalslot.h#L117-L119
Thus I changed the loop to this:
https://github.com/LibrePCB/LibrePCB/blob/c26c847961ea1745f7685b26cd56efd268b6c5c2/libs/librepcb/common/signalslot.h#L126-L128
@rnestler Do you know if this way it is safe to modify the container `mSlots` inside the callback? I'm not absolutely sure, but at least now I can't reproduce the crash I was experiencing before this chnge :wink:
=> Fix possible crash caused by low-level signal/slots

ci/azure-jobs-linux.yml, libs/librepcb/common/graphics/graphicsview.cpp, tests/unittests/common/attributes/attributesubstitutortest.cpp, tests/unittests/common/fileio/filepathtest.cpp, tests/unittests/common/fileio/transactionalfilesystemtest.cpp, tests/unittests/common/geometry/pathtest.cpp, tests/unittests/common/network/filedownloadtest.cpp, tests/unittests/common/network/networkrequesttest.cpp, tests/unittests/common/toolboxtest.cpp, tests/unittests/common/units/angletest.cpp, tests/unittests/common/units/lengthsnaptest.cpp, tests/unittests/common/units/lengthtest.cpp, tests/unittests/common/units/pointtest.cpp, tests/unittests/common/units/ratiotest.cpp, tests/unittests/common/uuidtest.cpp
Updating the submodules `quazip`, `googletest`, `optional` and `type_safe`.
Since this fixes various compile warnings, I was now able to add a CI job which compiles with GCC9 on Ubuntu 19.04. So from now on we can "guarantee" that LibrePCB also compiles on a very recent build environment. Maybe this makes @rnestler happy :grin:
Fixes #460
=> Update dependencies and CI jobs

apps/librepcb-cli/commandlineinterface.cpp, libs/librepcb/common/attributes/attributelistmodel.cpp, libs/librepcb/common/fileio/serializableobjectlist.h, libs/librepcb/common/toolbox.h, libs/librepcb/library/cmp/componentpinsignalmapmodel.cpp, libs/librepcb/library/dev/devicepadsignalmapmodel.cpp, libs/librepcb/library/sym/msg/msgoverlappingsymbolpins.cpp, libs/librepcb/libraryeditor/common/libraryelementchecklistwidget.cpp, libs/librepcb/librarymanager/addlibrarywidget.cpp, libs/librepcb/librarymanager/librarymanager.cpp, libs/librepcb/project/boards/board.cpp, libs/librepcb/project/boards/boardgerberexport.h, libs/librepcb/projecteditor/boardeditor/boardlayersdock.cpp, libs/librepcb/workspace/library/cat/categorytreeitem.cpp, libs/librepcb/workspace/settings/items/wsi_librarylocaleorder.cpp, libs/librepcb/workspace/workspace.cpp, tests/unittests/common/fileio/transactionalfilesystemtest.cpp, tests/unittests/common/geometry/pathtest.cpp
CI on MacOS is currently broken because homebrew always installs the latest version of Qt, which is now Qt 5.13 and throws some deprecation warnings. This PR fixes the deprecation warnings to make CI successful again:
- Replace `qSort()` by `std::sort()`
- Replace `QListWidgetItem::setBackgroundColor()` by `QListWidgetItem::setBackground()`
=> Fix deprecation warnings when compiling with Qt 5.13

libs/librepcb/common/graphics/polygongraphicsitem.cpp, libs/librepcb/library/pkg/footprintpreviewgraphicsitem.cpp, libs/librepcb/library/pkg/packagecheck.cpp, libs/librepcb/library/sym/symbolpreviewgraphicsitem.cpp, libs/librepcb/project/boards/boardgerberexport.cpp, libs/librepcb/project/boards/graphicsitems/bgi_footprint.cpp, libs/librepcb/project/schematics/graphicsitems/sgi_symbol.cpp
- Only fill polygons if they are closed (filled but non-closed polygons look strange -> avoid them).
- Fix missing area of filled polygons in Gerber export (filled polygons were drawn correctly in editors, but wrong in Gerber export).
Fixes #473 
#478 must be merged first since CI is currently broken for MacOS.
=> Fix inconsistent appearance of polygons between editor and Gerber export

libs/librepcb/common/dialogs/aboutdialog.ui
As reported on Transifex by _Ed.
=> About dialog: Mark TEXT_CONTRIBUTE_CODE as nontranslatable

libs/librepcb/librarymanager/librarymanager.ui
This property in `librarymanager.ui` is invalid. Modality should be set with the `windowModality` property, but it defaults to `Qt::NonModal`.
The removed lines caused this warning on startup:
`[ WARNING ] librepcb::library::manager::LibraryManager::setProperty: Property "modal" invalid, read-only or does not exist (kernel/qobject.cpp:3953)`
=> Remove invalid 'modal' property that causes warning

libs/librepcb/common/graphics/graphicsview.cpp, libs/librepcb/common/graphics/graphicsview.h, libs/librepcb/librarymanager/librarymanager.ui
This pull request is addresses #474.
The code in the initial pull request should not be merged, but is an initial example. I'd like to figure out how to make it work across platforms and with a mouse.
=> GraphicsView: Implement pinch to zoom

libs/librepcb/projecteditor/boardeditor/boardeditor.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp
Prior to this commit, it is impossible to restore dock widgets that were accidentally closed, except by deleting the QSettings storage.
=> Add toggle in the menu bar for dock widgets

libs/librepcb/common/attributes/attributelistmodel.cpp, libs/librepcb/common/attributes/attributetype.cpp, libs/librepcb/common/attributes/attributetype.h, libs/librepcb/common/attributes/attributeunit.cpp, libs/librepcb/common/attributes/attributeunit.h, libs/librepcb/common/attributes/attrtypecapacitance.cpp, libs/librepcb/common/attributes/attrtypecurrent.cpp, libs/librepcb/common/attributes/attrtypefrequency.cpp, libs/librepcb/common/attributes/attrtypeinductance.cpp, libs/librepcb/common/attributes/attrtypepower.cpp, libs/librepcb/common/attributes/attrtyperesistance.cpp, libs/librepcb/common/attributes/attrtypevoltage.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/ses_addcomponent.cpp
Select the proper unit automatically when entering suffixes like "u", "k" or "meg".
Fixes #465.
=> Auto-select attribute unit when entering unit in value field

libs/librepcb/project/boards/boardplanefragmentsbuilder.cpp
=> Fix missing plane cut-out for board outlines in footprints

libs/librepcb/project/boards/graphicsitems/bgi_footprint.cpp
Circles and polygons with zero width were not shown until now, but they should be visible independent of their width. I guess this is just a leftover from a long time ago when polygons were implemented quite different than now...
=> Board editor: Fix invisible zero-width circles/polygons

libs/librepcb/common/graphics/graphicsview.cpp, tests/funq/aliases, tests/funq/conftest.py, tests/funq/projecteditor/test_window_settings.py, tests/funq/requirements.txt
- Use `QOpenGLWidget` instead of `QGLWidget` fixes possibly broken client settings
- Add functional tests for window state save/restore
See discussion in #488.
=> Fix broken window settings when closing windows with OpenGL enabled

libs/librepcb/common/cam/gerbergenerator.cpp, libs/librepcb/common/cam/gerbergenerator.h
@ubruhin here's a first attempt at fixing this issue.
The spec says:
> Another option is not to use very small arcs, e.g. by replacing them with
draws - the error is very small and draws are stable.
Right now I'm replacing arcs shorter than 0.01mm (point-to-point) with straight lines. 
We probably need to handle some special cases, right? A full circle has start==end with angle=360, right? We should probably still draw arcs if start and end are identical.
I guess we can ignore cases where the two points are closer together than 0.01mm with a lage angle, right?
Fixes #247.
=> Gerber: Always use multi-quadrant mode

libs/librepcb/common/cam/gerberaperturelist.cpp, libs/librepcb/common/cam/gerberaperturelist.h, libs/librepcb/common/cam/gerbergenerator.cpp, libs/librepcb/common/cam/gerbergenerator.h, libs/librepcb/project/boards/boardgerberexport.cpp
Octagon footprint pads with width!=height were not supported until now (error during Gerber export). This fixes the error and exports the pads properly.
=> Gerber export: Add support for non-square octagon pads

libs/librepcb/project/boards/items/bi_footprintpad.cpp
Pads from mirrored footprints in boards were cut out with wrong rotation from planes:
=> Fix wrong rotation of mirrored pads in plane cut-outs

libs/librepcb/common/application.cpp, libs/librepcb/common/common.pro, libs/librepcb/common/dialogs/polygonpropertiesdialog.ui, libs/librepcb/common/geometry/pathmodel.cpp, libs/librepcb/common/model/angledelegate.cpp, libs/librepcb/common/model/angledelegate.h, libs/librepcb/common/model/lengthdelegate.cpp, libs/librepcb/common/model/lengthdelegate.h, libs/librepcb/common/toolbox.h, libs/librepcb/common/units/angle.h, libs/librepcb/common/units/length.h, libs/librepcb/common/units/lengthunit.cpp, libs/librepcb/common/units/lengthunit.h, libs/librepcb/common/widgets/angleedit.cpp, libs/librepcb/common/widgets/angleedit.h, libs/librepcb/common/widgets/doublespinbox.cpp, libs/librepcb/common/widgets/doublespinbox.h, libs/librepcb/common/widgets/lengthedit.cpp, libs/librepcb/common/widgets/lengthedit.h, libs/librepcb/common/widgets/numbereditbase.cpp, libs/librepcb/common/widgets/numbereditbase.h, libs/librepcb/common/widgets/patheditorwidget.cpp, tests/unittests/common/geometry/pathmodeltest.cpp, tests/unittests/common/toolboxtest.cpp, tests/unittests/unittests.pro
This adds the custom widgets `LengthEdit` and `AngleEdit` which are similar to `QLineEdit`, but specifically designed to enter `Length` resp. `Angle` values. Those are now used in `PathEditorWidget` (in the polygon properties dialog) to edit vertices. 
This leads to following improvements:
- Providing proper count of decimal places (fixes #512)
- Displaying numbers with locale-aware decimal separator (fixes #506)
- Displaying "mm" resp. "°" suffix to make clear what unit the numbers have
- Preparation to allow displaying/editing numbers in units other than Millimeters (see #362)
With locale "de_DE" (comma as decimal separator):
=> Fix too few decimal places in polygon editor dialog

libs/librepcb/common/widgets/graphicslayercombobox.cpp, libs/librepcb/common/widgets/graphicslayercombobox.h, libs/librepcb/eagleimport/packageconverter.cpp, libs/librepcb/eagleimport/symbolconverter.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawcircle.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawcircle.h, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawpolygonbase.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawpolygonbase.h, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawtextbase.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawtextbase.h, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawcircle.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawcircle.h, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawpolygonbase.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawpolygonbase.h, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawtextbase.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawtextbase.h, libs/librepcb/project/boards/board.cpp, libs/librepcb/project/schematics/schematic.cpp, libs/librepcb/projecteditor/boardeditor/fsm/bes_addstroketext.cpp, libs/librepcb/projecteditor/boardeditor/fsm/bes_addstroketext.h, libs/librepcb/projecteditor/boardeditor/fsm/bes_drawplane.cpp, libs/librepcb/projecteditor/boardeditor/fsm/bes_drawplane.h, libs/librepcb/projecteditor/boardeditor/fsm/bes_drawpolygon.cpp, libs/librepcb/projecteditor/boardeditor/fsm/bes_drawpolygon.h
At some locations, the assignment operator of `type_safe::constrained_type` which implicitly converts a value to the corresponding constrained type is used. For example the member `mLastLayerName`:
```cpp
void PackageEditorState_DrawTextBase::layerComboBoxValueChanged(
const QString& layerName) noexcept {
mLastLayerName = layerName;  // <-- this can throw!
if (mEditCmd) {
mEditCmd->setLayerName(mLastLayerName, true);
}
}
```
IMHO an assignment operator should not throw exceptions because it's not obvious when looking at the code. Thus I made a patch to the `constrained_type` class which removes the value assignment operator (to get compile errors if used) and fixed all compile errors, e.g. by making the casts explicit.
=> Stop using value assignment operator of type_safe::constrained_type

libs/librepcb/eagleimport/symbolconverter.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_addholes.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_addpads.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawcircle.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawpolygonbase.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawtextbase.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_addpins.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawcircle.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawpolygonbase.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawtextbase.cpp
When creating symbols or packages, some properties were initialized with default values which aren't reasonable IMHO. Thus I reviewed and documented (in code) all default values and adjusted some of them.
To comply with our [library conventions](https://docs.librepcb.org/#libraryconventions):
- Footprint circle line width changed from 0.254mm to 0.2mm
To avoid unnecessary grab areas "by accident":
- Footprint circle/polygon grab area disabled
To avoid inch-based numbers with many decimal places where metric numbers could be used instead (most spinboxes have an interval of 0.1mm, thus it's more reasonable to use default numbers which are a multiple of 0.1mm):
- Footprint THT pad size changed from 1.27mm x 0.635mm to 1.5mm x 0.7mm
- Footprint SMT pad size changed from 2.54mm x 1.27mm to …
=> Library editor: Adjust default values of sym/pkg elements

libs/librepcb/projecteditor/projecteditor.cpp
In the "Export project to *.lppz" dialog the filename was initialized with an empty string, so the user had to manually specify the filename. Now the filename gets initialized with the project's filename, e.g. "my-project.lppz" if the project is named "my-project.lpp".
=> Initialize *.lppz export filename with default value

libs/librepcb/projecteditor/boardeditor/fsm/bes_select.cpp
This menu item is only shown on devices which are located outside the current grid interval. When clicking on it, the device is moved to the nearest multiple of the grid interval.
Of course that's not the solution for our "grid issue" (see discussions [here](https://librepcb.discourse.group/t/grid-with-subdivision/122) and [here](https://librepcb.discourse.group/t/snap-grid-issue/33)), but at least these few lines of code provide the ability to easily fix off-the-grid positions ;)
=> Board editor: Add device context menu item "Snap to grid"

libs/librepcb/projecteditor/projecteditor.pro, libs/librepcb/projecteditor/schematiceditor/fsm/ses_select.cpp, libs/librepcb/projecteditor/schematiceditor/renamenetsegmentdialog.cpp, libs/librepcb/projecteditor/schematiceditor/renamenetsegmentdialog.h, libs/librepcb/projecteditor/schematiceditor/renamenetsegmentdialog.ui
When double-clicking on a netlabel, currently the only option was to move the net segment to a different net. But often one wants to rename a whole net (not only a segment), thus I added that option to the dialog:
Depending on whether there is already a net with the specified name or not, a net will be either just renamed, or merged into another net. To avoid surprises, the label at the bottom of the dialog explains what will happen exactly.
=> Schematic editor: Provide more options when renaming net segments

dev/format_code.sh
Fixes #557, probably replaces #558.
=> If clang-format fails, show hint about the --docker flag

libs/librepcb/projecteditor/schematiceditor/fsm/ses_addcomponent.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/ses_addcomponent.h
When adding a component with a pre-selected device multiple times to a schematic, the device was set only on the first component placed. All successive components didn't have a device selected.
Fixes #547
=> Schematic editor: Fix device when adding component multiple times

libs/librepcb/libraryeditor/libraryeditor.cpp
When closing a tab in the library editor while some property (like name,
description, ...) was just modified, the "save changes?" message box did
not appear. Now the focus is explicitly moved out from the editor widget
to ensure the "dirty" state of editors gets updated when closing a tab.
Fixes #492.
=> LibraryEditor: Fix missing message box when closing tab

libs/librepcb/project/circuit/cmd/cmdcomponentinstanceedit.cpp, libs/librepcb/project/circuit/cmd/cmdcomponentinstanceedit.h, libs/librepcb/project/circuit/componentinstance.cpp, libs/librepcb/project/circuit/componentinstance.h, libs/librepcb/projecteditor/schematiceditor/fsm/ses_select.cpp, libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.cpp, libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.h, libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.ui
Adding a dropdown to the symbol/component properties dialog:
Fixes #529
=> Schematic editor: Allow changing pre-selected device of components

apps/EagleImport/EagleImport.pro, apps/WorkspaceLibraryUpdater/WorkspaceLibraryUpdater.pro, libs/librepcb/common/common.pro, libs/librepcb/common/graphics/holegraphicsitem.cpp, libs/librepcb/common/graphics/origincrossgraphicsitem.cpp, libs/librepcb/common/graphics/origincrossgraphicsitem.h, libs/librepcb/common/graphics/primitivecirclegraphicsitem.cpp, libs/librepcb/common/graphics/primitivepathgraphicsitem.cpp, libs/librepcb/project/boards/board.cpp, libs/librepcb/project/boards/board.h, libs/librepcb/project/boards/graphicsitems/bgi_plane.cpp, libs/librepcb/projecteditor/boardeditor/boardeditor.cpp, libs/librepcb/projecteditor/boardeditor/boardeditor.h, libs/librepcb/projecteditor/boardeditor/boardeditor.ui
Adding initial support for PDF export and printing boards. It's not perfect, but much better than nothing :wink: Since only the currently visible layers are printed, it can be used for different use cases, depending on layer selection. For example one could print an assembly plan like this:
=> Board editor: Add PDF export and print support

libs/librepcb/common/model/angledelegate.cpp, libs/librepcb/common/model/angledelegate.h, libs/librepcb/common/model/lengthdelegate.cpp, libs/librepcb/common/model/lengthdelegate.h
Fixing two issues when modifying table cells in the polygon editor dialog:
- If a cell lost focus while modifying, the modification was not committed. For example when pressing the "OK" button while the focus was in a table cell, the dialog was closed but without applying the modification.
- When pressing enter, the whole dialog closed instead of only exiting the edit state.
=> Fix focus issue in polygon editor dialog

apps/librepcb/controlpanel/controlpanel.cpp
Because the `toUnique` call was missing, projects on a symlinked path
were not removed from the `mOpenProjectEditors` hash map. This in turn
would trigger a segfault when reopening a project due to a
use-after-free.
Fixes #432.
=> ControlPanel::projectEditorClosed: Use toUnique on file path

ci/azure-jobs-linux.yml, ci/build_linux_appimage.sh, ci/build_linux_archive.sh
Currently we provide two ways to install LibrePCB binaries on Linux: Installer and AppImage. But the installer is a pain for automated installation, and the AppImage does not work out-of-the-box in Docker containers (because FUSE is missing). To avoid these issues, I think it makes sense to also provide the binaries in a *.tar.gz archive for Linux. It's basically "for free", since we just need to bundle the already available binaries in a *.tar.gz.
Interestingly I also realized that the `librepcb-cli` currently doesn't work on Linux when installed with the installer, because that binary was not patched with `linuxdeployqt`. That's also fixed with this PR, so it should now work on Linux too.
=> CI: Create archive for deployment on Linux

libs/librepcb/common/toolbox.cpp, tests/unittests/common/toolboxtest.cpp
The shape was sometimes not calculated properly in `Toolbox::shapeFromPath()`, which lead to wrong grab areas of polygons and probably other graphics items, especially after modifying their properties.
Fixes #578
=> Fix possibly wrong grab area of various graphics items

apps/librepcb-cli/commandlineinterface.cpp, apps/librepcb-cli/commandlineinterface.h, libs/librepcb/common/fileio/transactionalfilesystem.cpp, libs/librepcb/common/fileio/transactionalfilesystem.h, tests/cli/open-project/test_save.py, tests/cli/open-project/test_strict.py, tests/unittests/common/fileio/transactionalfilesystemtest.cpp
With the `--strict` option, the CLI reports files which are not canonical, i.e. files which would be modified when saving the opened project or library element. Useful for continuous integration of libraries, mainly to check library elements which were generated (i.e. not made with LibrePCB).
Example:
```bash
$ librepcb-cli open-library LibrePCB_Connectors.lplib --all --strict
Open library 'LibrePCB_Connectors.lplib'...
- Non-canonical file: LibrePCB_Connectors.lplib/library.lp
Process 0 component categories...
Process 0 package categories...
Process 198 symbols...
Process 514 packages...
Process 198 components...
Process 514 devices...
- Non-canonical file: LibrePCB_Connectors.lplib/dev/0b53aefa-f8fb-4f31-bfa2-24325a58428b/.librepcb-dev
- Non-canonical file: …
```
=> CLI: Add "--strict" option

apps/librepcb/controlpanel/controlpanel.cpp, dev/doxygen/pages/architecture_overview.md, dev/doxygen/pages/code_style_guide.md, dev/doxygen/pages/project.md, dev/doxygen/pages/release_workflow.md, dev/doxygen/pages/workspace.md, libs/librepcb/common/debug.h, libs/librepcb/common/exceptions.h, libs/librepcb/common/network/networkrequestbase.cpp, libs/librepcb/common/undostack.h, libs/librepcb/common/units/point.h, libs/librepcb/project/circuit/circuit.cpp, libs/librepcb/project/project.cpp, libs/librepcb/project/project.h, libs/librepcb/workspace/settings/items/wsi_base.h
=> Fix typos in documentation and source comments 

ci/azure-jobs-doxygen.yml, dev/doxygen/Doxyfile, libs/librepcb/common/fileio/filepath.h, libs/librepcb/librarymanager/librarydownload.h, libs/librepcb/project/boards/boardlayerstack.h
Updating to Doxygen 1.8.13 and set `WARN_AS_ERROR=YES` in the Doxyfile, so from now on CI fails if there are invalid references in doxygen comments. This helps to keep the documentation up to date, avoiding issues like #43.
=> CI: Use Ubuntu 18.04 for the Doxygen job

libs/librepcb/common/attributes/attributekey.h, libs/librepcb/common/circuitidentifier.h, libs/librepcb/common/graphics/graphicslayername.h, libs/librepcb/common/uuid.cpp, libs/librepcb/library/cmp/componentprefix.h, libs/librepcb/library/cmp/componentsymbolvariantitemsuffix.h, tests/unittests/common/attributes/attributekeytest.cpp, tests/unittests/common/circuitidentifiertest.cpp, tests/unittests/common/graphics/graphicslayernametest.cpp, tests/unittests/common/uuidtest.cpp, tests/unittests/library/cmp/componentprefixtest.cpp, tests/unittests/library/cmp/componentsymbolvariantitemsuffixtest.cpp, tests/unittests/unittests.pro
The regex to check following constrained strings allowed a trailing newline by accident (see #603):
- AttributeKey
- CircuitIdentifier
- ComponentPrefix
- ComponentSymbolVariantItemSuffix
- GraphicsLayerName
- Uuid
Fixed the regex by using "\A" instead of "^" and "\z" instead of "$".
Also added some unit tests to check for correct behavior.
Fixes #603.
=> Fix regex of various constrained strings

libs/librepcb/project/project.pro, libs/librepcb/project/schematics/cmd/cmdschematicedit.cpp, libs/librepcb/project/schematics/cmd/cmdschematicedit.h, libs/librepcb/project/schematics/schematic.cpp, libs/librepcb/project/schematics/schematic.h, libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.h, libs/librepcb/projecteditor/schematiceditor/schematiceditor.ui, libs/librepcb/projecteditor/schematiceditor/schematicpagesdock.cpp, libs/librepcb/projecteditor/schematiceditor/schematicpagesdock.h
Renaming schematic pages was not possible at all until now. This PR adds a menu item "Schematic->Rename Sheet" to the schematic editor, and the keyboard shortcut "F2" to the schematic pages dock widget. An input dialog then asks for the new sheet name.
Discussion: https://librepcb.discourse.group/t/how-to-change-the-name-of-a-schematic-page/150
=> Schematic Editor: Add support for renaming sheets

apps/EagleImport/EagleImport.pro, apps/UuidGenerator/UuidGenerator.pro, apps/librepcb-cli/librepcb-cli.pro, apps/librepcb/controlpanel/controlpanel.ui, apps/librepcb/firstrunwizard/firstrunwizard.ui, apps/librepcb/librepcb.pro, dev/sort_qmake_file_entries.py, libs/librepcb/common/common.pro, libs/librepcb/eagleimport/eagleimport.pro, libs/librepcb/library/library.pro, libs/librepcb/libraryeditor/cmpcat/componentcategoryeditorwidget.ui, libs/librepcb/libraryeditor/dev/deviceeditorwidget.ui, libs/librepcb/libraryeditor/lib/librarylisteditorwidget.ui, libs/librepcb/libraryeditor/libraryeditor.pro, libs/librepcb/libraryeditor/newelementwizard/newelementwizard.ui, libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_choosetype.ui, libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_entermetadata.ui, libs/librepcb/libraryeditor/pkgcat/packagecategoryeditorwidget.ui, libs/librepcb/librarymanager/librarymanager.pro, libs/librepcb/project/project.pro, libs/librepcb/projecteditor/dialogs/bomgeneratordialog.ui, libs/librepcb/projecteditor/dialogs/projectsettingsdialog.ui, libs/librepcb/projecteditor/docks/ercmsgdock.ui, libs/librepcb/projecteditor/newprojectwizard/newprojectwizardpage_metadata.ui, libs/librepcb/projecteditor/projecteditor.pro, libs/librepcb/projecteditor/schematiceditor/schematicpagesdock.ui, libs/librepcb/workspace/workspace.pro
With recent QtCreator releases, in some (or even all?) *.ui files it's no longer possible to choose images from our `images.qrc` resource file. I have no idea why (with older QtCreator releases it worked properly), but it seems to be fixed if every *.pro file links to the resource file...
In addition, older QtCreator versions sometimes(?) added the path to the resource file to *.ui files, but that doesn't fix the issue above and it seems to have no effect, thus I removed them (for consistency, since most *.ui files don't have it too).
I tested the nightly builds from this branch and all images are still there, so probably it doesn't break anything ;)
=> Fix missing resources in QtCreator designer

dist/installer/update_metadata.sh
Instead of `~/Applications/`, use the system-wide `/Applications/` directory.
Fixes #644.
I haven't tested this. Will opening a PR automatically result in the branch being built in CI, or do we have to merge to master in order for a nightly to be created?
(I can test this on a macOS machine next week, but don't have any build toolchain on there to build the installer manually.)
=> Change macOS default target directory

dev/doxygen/pages/project.md, libs/librepcb/common/fileio/directorylock.h, libs/librepcb/common/fileio/transactionalfilesystem.cpp, libs/librepcb/workspace/workspace.cpp
Crashing is an active verb, not a passive one.
=> Fix grammar: was crashed -> crashed

apps/librepcb/controlpanel/controlpanel.cpp, apps/librepcb/controlpanel/controlpanel.h, apps/librepcb/projectlibraryupdater/projectlibraryupdater.cpp, libs/librepcb/common/application.cpp, libs/librepcb/common/fileio/transactionalfilesystem.cpp, libs/librepcb/common/fileio/transactionalfilesystem.h, libs/librepcb/libraryeditor/common/editorwidgetbase.cpp, libs/librepcb/libraryeditor/common/editorwidgetbase.h, tests/unittests/common/fileio/transactionalfilesystemtest.cpp
Instead of passing an enum for choosing the restore mode (yes/no/ask/abort), a callback can now be passed. The callback then returns a bool to choose whether the backup should be restored or not. This way the message box has to be implemented in higher level classes, and thus can be more specific.
See https://github.com/LibrePCB/LibrePCB/pull/668#discussion_r379836306
=> TransactionalFileSystem: Use callback to ask for restoring

libs/librepcb/project/boards/items/bi_footprint.cpp, libs/librepcb/project/boards/items/bi_footprint.h, libs/librepcb/project/schematics/items/si_symbol.cpp, libs/librepcb/project/schematics/items/si_symbol.h, libs/librepcb/projecteditor/boardeditor/boardeditor.cpp, libs/librepcb/projecteditor/boardeditor/boardeditor.h, libs/librepcb/projecteditor/boardeditor/boardeditor.ui, libs/librepcb/projecteditor/projecteditor.pro, libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.h, libs/librepcb/projecteditor/schematiceditor/schematiceditor.ui, libs/librepcb/projecteditor/toolbars/searchtoolbar.cpp, libs/librepcb/projecteditor/toolbars/searchtoolbar.h
Allows searching symbols and devices by name and jumping to its graphics item:
Fixes #585
=> Add "search" toolbar to schematic- and board editor

libs/librepcb/libraryeditor/lib/libraryoverviewwidget.cpp, libs/librepcb/libraryeditor/lib/libraryoverviewwidget.h, libs/librepcb/libraryeditor/libraryeditor.cpp, libs/librepcb/libraryeditor/libraryeditor.ui
The filter applies to all lists at the same time, which is useful to find all elements related to some term (e.g. filtering for "stm32" shows all related categories, symbols, components, etc.).
Fixes #665.
=> Library editor: Add "filter" toolbar to filter element lists

apps/librepcb/controlpanel/controlpanel.cpp, apps/librepcb/controlpanel/controlpanel.h, apps/librepcb/controlpanel/controlpanel.ui, libs/librepcb/library/cmp/cmpsigpindisplaytype.cpp, libs/librepcb/libraryeditor/libraryeditor.cpp, libs/librepcb/libraryeditor/libraryeditor.ui, libs/librepcb/project/boards/board.cpp, libs/librepcb/project/boards/items/bi_device.cpp, libs/librepcb/project/boards/items/bi_footprint.cpp, libs/librepcb/project/boards/items/bi_netline.cpp, libs/librepcb/project/boards/items/bi_netpoint.cpp, libs/librepcb/project/boards/items/bi_netsegment.cpp, libs/librepcb/project/circuit/circuit.cpp, libs/librepcb/project/circuit/componentinstance.cpp, libs/librepcb/project/circuit/componentsignalinstance.cpp, libs/librepcb/project/circuit/netsignal.cpp, libs/librepcb/project/library/projectlibrary.cpp, libs/librepcb/project/project.cpp, libs/librepcb/project/schematics/items/si_netline.cpp, libs/librepcb/project/schematics/items/si_netsegment.cpp, libs/librepcb/project/schematics/items/si_symbol.cpp, libs/librepcb/project/schematics/schematic.cpp, libs/librepcb/projecteditor/boardeditor/boardeditor.ui, libs/librepcb/projecteditor/boardeditor/fsm/bes_select.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.ui
Fixing some of the translation issues reported at [Transifex](https://www.transifex.com/librepcb/):
- Fix inconsistent "rescan libraries" menu items
- Rename "Rescan Library" to "Rescan Libraries"
- Rename "Update Library Database" to "Rescan Libraries"
- Use consistent icon and keyboard shortcut
- Stop translating low-level error messages (see [discussion](https://librepcb.discourse.group/t/translation-for-low-level-error-messages/119)).
Open question: Should we stop translating keyboard shortcuts (like "Ctrl+S")? There are a lot of keyboard shortcuts in the translation files, but I'm not sure if that makes sense. Unfortunately I didn't find a good documentation how translation of keyboard shortcuts should be handled...
=> Fix various translation issues

libs/librepcb/common/uuid.cpp
When analyzing a callgrind profile of a full library rescan, I noticed
that there are a lot of CPU instructions coming from libpcre2, with the
call originating in the UUID validation code.
Previously, the regular expression used for UUID validation was parsed
from a string for every invocation of the validation function. This is
unnecessary. A library rescan will validate thousands of UUIDs (roughly
250k calls to `Uuid::isValid` with 200'000 instructions per call on my
laptop for a library rescan). By moving the code to a static class
member, I achieved a 15% speedup for a full library scan.
---
Library scan duration for five consecutive LibrePCB starts using the release build:
Before:
- 12'419 ms
- 12'239 ms
- 11'992 ms
- 12'377 ms
- 11'766 ms
Avg: 12'159 ms
After:
- 11'366 ms
- 9'975 ms …
=> Replace UUID validation RegEx with manual validation

libs/librepcb/projecteditor/boardeditor/fsm/bes_select.cpp, libs/librepcb/projecteditor/boardeditor/fsm/bes_select.h
Until now, the list of devices was in a random order, which made it difficult to find a specific device. In a sorted list it's much easier to find a device by its name. In addition, I added icons to these menu items (not that useful, but why not :grin:):
=> Board editor: Sort items in "Change Device" context menu

apps/librepcb-cli/commandlineinterface.cpp, libs/librepcb/common/bom/bomcsvwriter.cpp, libs/librepcb/common/bom/bomcsvwriter.h, libs/librepcb/projecteditor/dialogs/bomgeneratordialog.cpp
Beside the refactoring, this also switches from semicolon-separated values to comma-separated values.
Replaces #633.
Fixes #630.
=> BomCsvWriter: Refactor to use the new CsvFile class

libs/librepcb/library/dev/device.h, libs/librepcb/library/dev/devicecheck.cpp, libs/librepcb/library/dev/devicecheck.h, libs/librepcb/library/dev/msg/msgnopadsindeviceconnected.cpp, libs/librepcb/library/dev/msg/msgnopadsindeviceconnected.h, libs/librepcb/library/library.pro
Shows a warning in the device editor if there are package pads, but none of them is connected. As soon as one pad gets connected, the message disappears.
I used the severity "warning" instead of "error" because there are situations where this message is a false-positive: If the package has only pads for mechanical reasons, but does not provide an electrical functionality, this message needs to be ignored.
Fixes #412
=> Device editor: Show warning if no pads are connected

libs/librepcb/projecteditor/schematiceditor/schematicpagesdock.cpp
If there is not enough space available to display the schematic pages in a vertical layout, QListWidget was allowed to wrap pages to the right, i.e. using a horizontal layout. In some situations (depending on the width of the dock widget), the wrapped pages were not visible anymore, so it looked like some schematic pages disappeared. By disabling wrapping, QListWidget always uses a vertical layout.
Fixes #681
=> SchematicPagesDock: Disable wrapping of schematic pages

apps/librepcb/initializeworkspacewizard/initializeworkspacewizard_finalizeimport.cpp
The "back" and "cancel" buttons on the last page of the "initialize Workspace" wizard do not make any sense after the import was completed. Now they are disabled as soon as the import finished, so the only remaining enabled button is "finish".
This fixes #675 since the back button is now disabled :wink:
=> Workspace migration wizard: Disable useless buttons

libs/librepcb/common/algorithm/airwiresbuilder.cpp, libs/librepcb/common/algorithm/airwiresbuilder.h, libs/librepcb/common/common.pro, libs/librepcb/common/units/point.h, libs/librepcb/project/boards/boardairwiresbuilder.cpp, tests/unittests/common/algorithm/airwiresbuildertest.cpp, tests/unittests/common/units/pointtest.cpp, tests/unittests/unittests.pro
It's actually not a fix, but a workaround for issue #588. The Delaunay triangulation library is not able to handle colinear points in the input data (our net points) and silently ignores some of the input points, so there are edges (our airwires) missing in the output.
I spend quite some time on this issue, and I think it's not possible to actually fix this problem on our side, so the fix needs to be done in [delaunay-triangulation](https://github.com/Bl4ckb0ne/delaunay-triangulation). But actually I'm not sure if it's worth investigating and fixing the issue in that library - in my opinion the overall quality of that library is not acceptable for an EDA tool anyway. For long-term, we might switch to a different library, for example …
=> Fix possibly disappearing airwires

libs/librepcb/common/dialogs/gridsettingsdialog.cpp, libs/librepcb/common/dialogs/gridsettingsdialog.h, libs/librepcb/common/dialogs/gridsettingsdialog.ui, libs/librepcb/common/widgets/lengtheditbase.cpp, libs/librepcb/common/widgets/lengtheditbase.h, libs/librepcb/common/widgets/statusbar.cpp, libs/librepcb/libraryeditor/common/editorwidgetbase.cpp, libs/librepcb/libraryeditor/common/editorwidgetbase.h, libs/librepcb/libraryeditor/libraryeditor.cpp, libs/librepcb/libraryeditor/libraryeditor.h, libs/librepcb/libraryeditor/pkg/packageeditorwidget.cpp, libs/librepcb/libraryeditor/pkg/packageeditorwidget.h, libs/librepcb/libraryeditor/sym/symboleditorwidget.cpp, libs/librepcb/libraryeditor/sym/symboleditorwidget.h, libs/librepcb/projecteditor/boardeditor/boardeditor.cpp, libs/librepcb/projecteditor/boardeditor/boardeditor.h, libs/librepcb/projecteditor/schematiceditor/fsm/ses_addcomponent.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/ses_addnetlabel.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/ses_drawwire.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.h
In #684 I adjusted the editors to display the cursor position in the statusbar in the unit from workspace settings. But now while testing the 0.1.4 release candidate I realized that it probably makes even more sense to use the unit configured in the grid settings of the opened editor. So for example if you configure the schematics grid to 0.1 inches, the schematic editor will show the cursor position in inches too, while at the same time the board editor might show Millimeters if the board grid is set to e.g. 0.1mm.
In addition, I completely refactored and cleaned up the grid settings dialog. It is now also using the new length edit widget instead of using spinbox+buttons+combobox.
Old:
New:
Summary: Less and cleaner code, simpler UI and more functionality :grin:
=> Respect configured grid unit in statusbar

libs/librepcb/common/dialogs/boarddesignrulesdialog.cpp, libs/librepcb/common/dialogs/boarddesignrulesdialog.ui, libs/librepcb/common/dialogs/circlepropertiesdialog.ui, libs/librepcb/common/dialogs/holepropertiesdialog.cpp, libs/librepcb/common/dialogs/holepropertiesdialog.ui, libs/librepcb/common/dialogs/polygonpropertiesdialog.ui, libs/librepcb/common/dialogs/stroketextpropertiesdialog.cpp, libs/librepcb/common/dialogs/stroketextpropertiesdialog.ui, libs/librepcb/common/dialogs/textpropertiesdialog.cpp, libs/librepcb/common/dialogs/textpropertiesdialog.ui, libs/librepcb/libraryeditor/pkg/dialogs/footprintpadpropertiesdialog.ui, libs/librepcb/libraryeditor/sym/dialogs/symbolpinpropertiesdialog.ui, libs/librepcb/projecteditor/boardeditor/boarddesignrulecheckdialog.ui, libs/librepcb/projecteditor/boardeditor/boardplanepropertiesdialog.ui, libs/librepcb/projecteditor/boardeditor/boardviapropertiesdialog.ui, libs/librepcb/projecteditor/boardeditor/deviceinstancepropertiesdialog.ui, libs/librepcb/projecteditor/boardeditor/fabricationoutputdialog.ui, libs/librepcb/projecteditor/dialogs/projectpropertieseditordialog.cpp, libs/librepcb/projecteditor/dialogs/projectpropertieseditordialog.ui, libs/librepcb/projecteditor/schematiceditor/renamenetsegmentdialog.ui, libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.ui
During testing of the 0.1.4 release candidate, I realized that the keyboard navigation of most dialogs with input fields was not very user friendly. This PR improves following things:
- Adjust order of widgets to always have the most important input field at the top of the dialog.
- Pre-select the value of the most important input field so one can immediately start typing a new value after opening the dialog.
- In multiline text edit widgets, make tabulator key navigating to the next widget instead of inserting a tab.
- Set reasonable tab order (usually from top to bottom).
Might make @dbrgn more happy when using LibrePCB :grin:
=> Improve keyboard navigation in dialogs

ci/azure-jobs-linux.yml, ci/install_dependencies.sh
- Update Linux jobs to latest Docker images, and thus using the latest available Qt version for our official binary releases. It also fixes missing translations of Qt built-in strings, see https://github.com/LibrePCB/LibrePCB/pull/674#issuecomment-590505008.
- Update Qt installer framework on macOS
Notes:
- I can't update the Windows build environment at the moment because of two issues:
- ~~https://github.com/parkouss/funq/pull/71~~ Merged
- When switching the Qt version, ccache cannot restore the cache and then we hit the AppVeyor build time limit of 60 minutes :sob: I already asked the AppVeyor team to increase the limit for LibrePCB...
- I didn't update the macOS version from 10.14 to 10.15 because it might reduce binary compatibility of our releases(?). I don't know much about macOS, …
=> CI: Update Linux and macOS build environment

libs/librepcb/projecteditor/boardeditor/boardpickplacegeneratordialog.cpp, libs/librepcb/projecteditor/dialogs/bomgeneratordialog.cpp
There was an off-by-one index error (only in the GUI, not in the exported CSV) :(
I will merge this as soon as CI succeeds since it should be contained in the 0.1.4 release.
=> Fix empty table row in pick&place and BOM export dialogs

libs/librepcb/libraryeditor/lib/libraryoverviewwidget.cpp
If no local libraries are available, the context menu item "move to other library" did not contain children, which looks strange. Now the menu item is disabled if it doesn't contain children.
I will merge this as soon as CI succeeds since it should be contained in the 0.1.4 release.
=> Library editor: Disable "move to other library" if empty

dev/doxygen/Doxyfile
From the Doxygen docs[1]:
> Note that the TOC_INCLUDE_HEADINGS has to be set to a value > 0
> otherwise no table of contents is shown when using Markdown Headers.
I set the value to `2`, so that 2 levels of headings are included in
the table of contents.
[1] http://doxygen.nl/manual/markdown.html#md_toc
=> Doxygen: Show TOC on markdown pages

common.pri, tests/funq/librarymanager/test_create_local_library.py, tests/funq/librarymanager/test_download_manually.py, tests/funq/librarymanager/test_install_remote_libraries.py
In Qt 5.15, a lot of things were marked as deprecated (to help migrating to Qt6), without providing alternatives available in previous Qt versions. It would require a lot of preprocessor conditionals to avoid these deprecation warnings, so let's just disable them for now. We are using CI anyway to ensure LibrePCB compiles with the targeted Qt versions.
Updating the fontobene-qt5 submodule fixes a deprecation warning within that library.
This fixes the currently broken CI since the macOS runner suddenly switched to Qt 5.15.
=> Disable deprecation warnings when using Qt 5.15

libs/librepcb/common/fileio/fileutils.cpp
QDir::rename() fails if the parent directory does not yet exist.
Fixes #714.
=> Ensure that parent dir exists when moving files or directories

appveyor.yml
Work around CI failure:
error: could not open file /var/cache/pacman/pkg/libopenssl-1.1.1.g-2-x86_64.pkg.tar.zst: Child process exited with status 127
See https://github.com/msys2/MSYS2-packages/issues/1962.
=> CI: Work around MSYS2 error on AppVeyor

libs/libs.pro
=> Fix fontobene-qt5 config in libs.pro

README.md
- Fix outdated project status description
- Add link to our download page
- Move note about the "librepcb-git" AUR package from the "Installation & Usage" section to the "Development" section since is not the official way to install LibrePCB.
=> README: Update project status & installation instructions

CONTRIBUTING.md, dev/doxygen/pages/developers.md
We did not have any documentation about how we expect Pull Requests to be updated. So our contributors could not know that we like rebased branches before merging them :wink:
With this change, at least we have some official documentation how to work with Pull Requests. My intention is to let contributors, which are familiar with Git, know how they should update their branches. For those not familiar enough with Git, of course we can provide support.
Rendered preview: https://developers.librepcb.org/_branches/document-pull-request-guidelines/df/d30/doc_developers.html#doc_developers_pullrequests
=> Add developer guidelines for updating Pull Requests

libs/librepcb/project/circuit/componentsignalinstance.h, libs/librepcb/project/circuit/netsignal.cpp
Only components that are not schematic only are counted when determining if a NetSignal is connected to less than two pins.
- Fixes #739
=> ERC: Disregard schematic-only components in net pin count

libs/librepcb/common/units/point.cpp, libs/librepcb/common/units/point.h, libs/librepcb/projecteditor/boardeditor/fsm/bes_select.cpp, libs/librepcb/projecteditor/boardeditor/fsm/bes_select.h, libs/librepcb/projecteditor/cmd/cmddragselectedboarditems.cpp, libs/librepcb/projecteditor/cmd/cmddragselectedboarditems.h
Previously the menu was build and executed for each different item type separately. This resulted in duplicate code and increased effort when adding an already established action to an item. This PR mainly condenses duplicate code and creates an easy framework for new actions.
A range of standard actions are already implemented, that can be used for building the context menu (remove, rotate, flip, snap, ...).
If an item needs a custom action, it must be defined locally and a callback must be connected to the QAction::triggered signal.
- Extract and condense code for identical actions
- Add context menu for NetPoints
- Provide functions to create menu entries for some standard actions
- When holding Shift, while clicking on a position with multiple items, cycle through the available items …
=> Board editor: Refactor and improve context menu

libs/librepcb/projecteditor/boardeditor/boardeditor.cpp, libs/librepcb/projecteditor/boardeditor/boardeditor.h, libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.h, libs/librepcb/projecteditor/toolbars/searchtoolbar.cpp, libs/librepcb/projecteditor/toolbars/searchtoolbar.h
- Allow cycling through results beginning with the current search term
- Zoom depending on the symbol/device size, and showing the maximum dimension as 1/4 of the screen
=> Improve search behavior in board- and schematic editor

libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_select.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_select.h, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_select.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_select.h, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate_select.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate_select.h
Improve context menu handling for the symbol, package, and schematic editor.
- Implement improvements as done in #748
- Implement findItemsAtPosition function where necessary
- Allow cycling through items while holding the shift key
- Fixes #536
=> Editors: Improve context menu handling

libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp, libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.h
1. Construct a List of all available anchors at the target position
2. Connect the new trace as previously for each anchor
3. Connect skipped NetPoints due to combining NetSegments
- Fixes #750
- Fix error where finishing a trace at a Via or FootprintPad without NetLines was impossible
=> Draw Trace: Allow connection to multiple anchors

libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate_addcomponent.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate_addnetlabel.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate_drawwire.cpp
When pressing the right mouse button while moving the cursor, each schematic editor tool unintentionally exited because the event was not handled by the tool. So the event was handled by the state machine, which switches to the last active tool by the right mouse button click.
Now the event is accepted by the corresponding tools to avoid this issue.
Fixes #343.
=> Schematic editor: Fix leaving tool with right click + move

librepcb.pro
The message() causes the QtCreator (at least sometimes) to switch to a different output pane, which is quite annoying. And in colored console output it might be confusing too since it it the only output on stderr. Thus I'd say let's remove it.
@dbrgn is that fine for you? :slightly_smiling_face:
=> Remove linking output message in qmake project file

libs/librepcb/project/boards/board.cpp, libs/librepcb/project/boards/board.h, libs/librepcb/project/boards/items/bi_netsegment.cpp, libs/librepcb/project/boards/items/bi_netsegment.h, libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp, libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.h
When no anchor is found at the start location of drawing a trace, look in a radius of 1cm for other possible candidates.
Currently supports
- NetPoints
- Vias
- Pads
The search function looks for anchors in the radius of maxDistance around the specified position on a given layer. When a candidate is found, the radius is reduced to the distance between the position and the center point of the anchor.
The function searches for NetPoints, Vias, and Pads in the given order. It returns the last found anchor since it laid within the smallest search radius.
Currently (similar to the rendering of airwires) NetLines are not considered, even if a new NetPoint would result in a closer anchor.
- Merge #632 with current master
- Fixes #631
=> Board editor: Snap to nearest anchor when starting a trace

libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp, libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.h
Fix crash when trying to connect to a pad that is not part of a signal.
Fixes #762
=> BES_DrawTrace: Get rid of member variable mCurrentNetSignal

libs/librepcb/libraryeditor/newelementwizard/newelementwizardcontext.cpp, libs/librepcb/libraryeditor/newelementwizard/newelementwizardcontext.h, libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_entermetadata.cpp, libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_entermetadata.ui
Copy all categories to when duplicating a symbol/device/... in a library.
- NewElementWizardContext holds a list of all categories of the original item
- duplicate/new element wizard
- add "and x more" label to signify more "hidden" categories. 
- reset clears the complete list
- change replaces *all* categories with the newly selected one
- the wizard cannot assign multiple categories. This has to be done as usual in the editor
- fixes #696
=> Library Editor: Duplicate all categories

libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_select.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_select.cpp
Within symbol editor and package editor, allow rotate/mirror/flip while moving items.
Fixes #700
=> Library editor: Allow rotate/mirror/flip while moving items

libs/librepcb/project/boards/items/bi_device.cpp, libs/librepcb/project/boards/items/bi_stroketext.cpp, libs/librepcb/project/boards/items/bi_stroketext.h
Device texts like "{{NAME}}" or "{{VALUE}}" in boards were not updated after modifying these properties of a component (either in the schematic- or board editor). So the displayed texts were wrong after such modifications. Now they are updated immediately when changing component properties.
Fixes #730
=> Fix possibly outdated texts of devices in boards

libs/librepcb/project/boards/graphicsitems/bgi_footprintpad.cpp, libs/librepcb/project/boards/items/bi_footprintpad.cpp, libs/librepcb/project/boards/items/bi_footprintpad.h, libs/librepcb/project/boards/items/bi_netline.cpp, libs/librepcb/project/boards/items/bi_via.cpp, libs/librepcb/project/boards/items/bi_via.h
The displayed net names within vias and pads, and the net names within the hints of vias, pads and traces were not updated properly if a net signal was renamed. So the displayed net names in boards was wrong. Now the event of renaming a net signal is forwarded to vias, pads and traces to enforce updating the displayed texts and hints accordingly.
Fixes #712
=> Fix possibly outdated displayed net names in boards

libs/librepcb/project/boards/boardselectionquery.cpp, libs/librepcb/project/boards/boardselectionquery.h, libs/librepcb/projecteditor/boardeditor/boardclipboarddata.cpp, libs/librepcb/projecteditor/boardeditor/boardclipboarddata.h, libs/librepcb/projecteditor/boardeditor/boardclipboarddatabuilder.cpp, libs/librepcb/projecteditor/boardeditor/boardclipboarddatabuilder.h, libs/librepcb/projecteditor/boardeditor/boardeditor.ui, libs/librepcb/projecteditor/boardeditor/boardnetsegmentsplitter.cpp, libs/librepcb/projecteditor/boardeditor/boardnetsegmentsplitter.h, libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate_select.cpp, libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate_select.h, libs/librepcb/projecteditor/cmd/cmdpasteboarditems.cpp, libs/librepcb/projecteditor/cmd/cmdpasteboarditems.h, libs/librepcb/projecteditor/cmd/cmdpastefootprintitems.cpp, libs/librepcb/projecteditor/cmd/cmdpastefootprintitems.h, libs/librepcb/projecteditor/cmd/cmdremoveboarditems.cpp, libs/librepcb/projecteditor/cmd/cmdremoveboarditems.h, libs/librepcb/projecteditor/cmd/cmdremoveselectedboarditems.cpp, libs/librepcb/projecteditor/projecteditor.pro
Allows to copy&paste board items (even between different projects). In addition, it's even possible to copy graphical objects of a footprint from the library editor into a board.
Limitations:
- Device instances cannot be copied since they would affect the netlist which currently can only be edited by the schematic editor.
- Footprint pads cannot be copied from the library editor into a board since a board can't contain "naked" pads.
Implemented very similar to #724.
ToDo:
Fixes #13
=> Board editor: Implement clipboard cut/copy/paste

tests/funq/librarymanager/test_create_local_library.py, tests/funq/librarymanager/test_download_manually.py, tests/funq/librarymanager/test_install_remote_libraries.py
This reverts commit feea5c1ef115d83a8090132f7fbdf40c1a41db65 which was added in #716. It seems that the problem was "automatically" solved when macOS updated Qt to 5.15.1 :wink:
Fixes #718
=> Functional tests: Revert marking failed tests on macOS with xfail

libs/librepcb/common/graphics/polygongraphicsitem.cpp, libs/librepcb/common/graphics/polygongraphicsitem.h, libs/librepcb/common/graphics/primitivepathgraphicsitem.cpp, libs/librepcb/common/graphics/primitivepathgraphicsitem.h, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_select.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_select.h, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_select.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_select.h, libs/librepcb/project/boards/items/bi_polygon.h, libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate_select.cpp, libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate_select.h
Within the package-, symbol- and board editors, polygons can now be edited graphically:
- Dragging vertices of selected polygons
- Removing vertices by context menu on vertices
- Inserting vertices by context menu of line segments
=> Allow to modify polygons graphically

libs/librepcb/librarymanager/librarydownload.cpp, libs/librepcb/librarymanager/librarydownload.h, tests/unittests/librarymanager/librarydownloadtest.cpp, tests/unittests/unittests.pro
Affects downloading libraries with the library manager:
If the temporary ZIP file already exists before starting to download a library, the download failed with a "file already exists" error. This can happen for example when closing LibrePCB while a library download was in progress. Afterwards, it was not possible anymore to download the library with the library manager.
Now the ZIP file will be removed before starting the download.
Fixes #657.
=> LibraryDownload: Remove destination ZIP before starting download

CONTRIBUTING.md
The website repository was renamed, see https://github.com/LibrePCB/librepcb-website/issues/46.
=> CONTRIBUTING.md: Update link to website repository

apps/UuidGenerator/UuidGenerator.pro
This dependency was missing, which caused dynamically linked builds to fail when not unbundling quazip.
Part of the fix for #785.
Note: Dynamic builds still won't work until https://github.com/LibrePCB/quazip/pull/2 is merged and the quazip submodule is updated.
=> UuidGenerator: Add quazip build dependency

libs/librepcb/common/boarddesignrules.cpp, tests/unittests/common/boarddesignrulestest.cpp, tests/unittests/unittests.pro
The maximum stopmask drill diameter was not loaded properly from the settings file. Instead, the default parameter was restored.
Now I added a unit test which checks serializing/deserializing of the design rules.
=> BoardDesignRules: Fix loading max. stopmask drill diameter

libs/librepcb/projecteditor/boardeditor/fsm/boardeditorfsm.cpp, libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate.h, libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate_adddevice.cpp
After a device has been placed on the board, the "place device" tool was not left automatically. So the user had to manually click on the "select" tool button to be able to select and move items. Now the "select" tool is automatically entered after placing a device.
The bug was probably introduced by the last board editor FSM refactoring.
Fixes #787
=> Board editor: Fix staying in the "place device" tool

common.pri
It was accidentally set even for dynamic builds where the vendored quazip was being used (e.g. `UNBUNDLE+=polyclipping`).
=> Only set QUAZIP_STATIC for static builds

apps/librepcb-cli/librepcb-cli.pro, apps/librepcb/librepcb.pro, apps/librepcb/markdown/markdownconverter.cpp, ci/azure-jobs-linux.yml, libs/libs.pro
As discussed in the development chat: Instead of replacing hoedown with cmark (see #777), we can use Qt's built-in markdown support in Qt >=5.14. The rendering is slightly different than with hoedown (using the CommonMark standard), but since the binary releases are using a recent Qt version and up-to date distros should also ship a recent Qt version, most users will already be using the new rendering logic.
With this change, there will be one less vendored library for distro package maintainers to package (see #385).
Closes #777.
=> Use built-in markdown support when using Qt >=5.14

ci/install_dependencies.sh
MacOS builds on CI are broken since a few days (as usual every few months.... seems to be a damn unstable OS).
I applied the workaround as suggested in https://github.com/actions/virtual-environments/issues/1811#issuecomment-708480190 to fix the failure. But I suspect some day these new commands will suddenly fail when Apple and/or homebrew change the behavior again. So I applied Apple-style error handling for prevention: Just ignoring any error :wink:
I'm not sure, but I suspect someone even suddenly removed Python 2 from macOS?! Therefore I switched the functional tests to Python 3, fortunately that was an easy task...
=> CI: Work around broken macOS builds

libs/librepcb/common/graphics/holegraphicsitem.cpp, libs/librepcb/common/graphics/holegraphicsitem.h, libs/librepcb/library/pkg/footprintpreviewgraphicsitem.cpp, libs/librepcb/libraryeditor/pkg/fsm/cmd/cmddragselectedfootprintitems.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_select.cpp
At some places where footprint previews are shown (e.g. device editor, component chooser dialog, place devices dock), the holes of the footprint were not visible. Now the holes are shown properly.
Fixes #784
=> Fix missing holes in footprint previews

.gitmodules, apps/EagleImport/EagleImport.pro, apps/UuidGenerator/UuidGenerator.pro, apps/librepcb-cli/librepcb-cli.pro, apps/librepcb/librepcb.pro, libs/librepcb/common/common.pro, libs/librepcb/common/fileio/sexpression.cpp, libs/librepcb/common/fileio/sexpression.h, libs/libs.pro, tests/unittests/common/fileio/sexpressiontest.cpp, tests/unittests/unittests.pro
Replacing `sexpresso::parse()` with our own parser in the `SExpression` class. See #783 for the motivation behind this change.
Because we also used `sexpresso::escape()` to escape characters in strings to be serialized, I also had to replace this by our own implementation. Then I saw that `sexpresso::escape()` even replaced `?` by `\?`, `'` by `\'` and the _audible bell_ by `\a` (wtf?), which doesn't make sense to me :wink: So I removed these replacements, but only for LibrePCB 0.2.x to keep the 0.1.x file format as-is.
Positive side effect of the own implementation: It seems to be much faster than `sexpresso::parse()` :smiley: Not an accurate measurement, but on my computer the background library scan now takes ~25% less time than before (tested only in debug mode).
I just hope there are …
=> Replace sexpresso library with own implementation

libs/librepcb/common/systeminfo.cpp, tests/unittests/common/systeminfotest.cpp
See https://librepcb.discourse.group/t/building-on-openbsd/320.
Now it compiles successfully and all unittests are passing. Tested on OpenBSD 6.8.
=> SystemInfo: Add support for OpenBSD

libs/librepcb/eagleimport/packageconverter.cpp, libs/librepcb/library/pkg/cmd/cmdfootprintpadedit.cpp, libs/librepcb/library/pkg/cmd/cmdfootprintpadedit.h, libs/librepcb/library/pkg/footprintpad.cpp, libs/librepcb/library/pkg/footprintpad.h, libs/librepcb/library/pkg/footprintpadgraphicsitem.cpp, libs/librepcb/library/pkg/footprintpadgraphicsitem.h, libs/librepcb/library/pkg/footprintpreviewgraphicsitem.cpp, libs/librepcb/libraryeditor/newelementwizard/newelementwizardcontext.cpp, libs/librepcb/libraryeditor/pkg/dialogs/footprintpadpropertiesdialog.cpp, libs/librepcb/libraryeditor/pkg/dialogs/footprintpadpropertiesdialog.h, libs/librepcb/libraryeditor/pkg/fsm/cmd/cmdpastefootprintitems.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_addpads.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_addpads.h, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_select.cpp, libs/librepcb/libraryeditor/pkg/widgets/packagepadcombobox.cpp, libs/librepcb/libraryeditor/pkg/widgets/packagepadcombobox.h, libs/librepcb/project/boards/items/bi_footprint.cpp, libs/librepcb/project/boards/items/bi_footprintpad.cpp, libs/librepcb/project/boards/items/bi_footprintpad.h, tests/unittests/library/pkg/footprintpadtest.cpp, tests/unittests/libraryeditor/pkg/footprintclipboarddatatest.cpp, tests/unittests/unittests.pro
Let footprint pads have their own UUID instead of using the UUID of the connected package pad.
When upgrading v0.1 package files to v0.2, the key `package_pad` gets added. Then the `pad` and `package_pad` both have the same value:
```scheme
(pad af3ead15-37a6-474d-8698-e4a22bd117de (side top) (shape rect)
(position 1.4 0.0) (rotation 0.0) (size 1.6 1.8) (drill 0.0)
(package_pad af3ead15-37a6-474d-8698-e4a22bd117de)
)
```
This way the file format upgrade is deterministic. When creating entirely new packages in LibrePCB v0.2.x, the footprint pad UUID is random, while the `package_pad` UUID is either a package pad UUID or `none` for unconnected pads.
This file format change allowed some new features which are also implemented in this PR:
- Allow footprint pads to be unconnected, i.e. not …
=> Give footprint pads an UUID and allow unconnected pads

libs/librepcb/project/boards/board.cpp, libs/librepcb/project/boards/boardusersettings.cpp, libs/librepcb/project/boards/boardusersettings.h
The visibility of planes now gets stored in the board user settings file (`<PROJECT>/boards/<BOARD>/settings.user.lp`). Since this file usually is not put under version control, no noisy diff occurs when changing the visibility of planes.
Fixes #538
=> Save and restore board planes visibility

apps/librepcb-cli/main.cpp
These messages should always be visible on stderr, not just in the
logfile (which may not have been initialized properly if a fatal error
occurs).
=> librepcb-cli: Log fatal messages to stderr

libs/librepcb/project/boards/items/bi_footprintpad.cpp, libs/librepcb/project/boards/items/bi_footprintpad.h, libs/librepcb/project/schematics/items/si_symbolpin.cpp, libs/librepcb/project/schematics/items/si_symbolpin.h
If the pinout of a device or component was changed after adding such elements to a project, the project library updater might fail due to invalid connections when running the next time. This is expected behavior (thus a warning appears in the library editor), but now the user at least gets a much more expressive error message. This way it's easier to determine which library element caused the error.
Since these are still pretty low level error messages, I didn't made them translatable, as decided in https://librepcb.discourse.group/t/119.
Fixes https://librepcb.discourse.group/t/project-update-library-fail-error-source-identification/344.
=> Improve error messages when project library update fails

libs/librepcb/common/graphics/graphicslayer.cpp, libs/librepcb/common/graphics/graphicslayer.h, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate.h, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawcircle.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawpolygonbase.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawtextbase.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_select.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate.h, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawcircle.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawpolygonbase.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawtextbase.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_select.cpp, libs/librepcb/project/boards/boardlayerstack.cpp, libs/librepcb/project/boards/boardlayerstack.h, libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate.cpp, libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate.h, libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate_addstroketext.cpp, libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate_drawpolygon.cpp, libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate_select.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate.h, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate_addtext.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate_drawpolygon.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate_select.cpp
In all editors, the "Hidden Grab Areas" layers are removed from the dropdown lists where this layer makes no sense. See details in #808.
Fixes #808.
=> Don't provide "Hidden Grab Areas" layer when not reasonable

libs/librepcb/project/boards/items/bi_footprint.cpp, libs/librepcb/project/boards/items/bi_footprint.h
When adding a new device to a board failed (for example due to invalid library elements), some objects were not cleaned up properly which caused a segfault some time later (for example when saving the project). Now these objects are cleaned up to fix this issue.
Fixes #840
=> Fix crash after adding a device to a board failed

ci/azure-jobs-doxygen.yml, ci/azure-jobs-linux.yml, ci/azure-jobs-stylecheck.yml, ci/azure-jobs-windows.yml
To make sure LibrePCB compiles with the latest Qt version 5.15.2 (at least on Windows), and to have CMake available which we need for #798. On Ubuntu 16.04, Qt 5.15.2 unfortunately doesn't work for us since it is missing SSL support, thus we stick with Qt 5.14.2 for now.
=> CI: Update to latest runners and Docker images

libs/librepcb/common/geometry/cmd/cmdcircleedit.cpp, libs/librepcb/common/geometry/cmd/cmdcircleedit.h, libs/librepcb/common/geometry/cmd/cmdholeedit.cpp, libs/librepcb/common/geometry/cmd/cmdholeedit.h, libs/librepcb/common/geometry/cmd/cmdpolygonedit.cpp, libs/librepcb/common/geometry/cmd/cmdpolygonedit.h, libs/librepcb/common/geometry/cmd/cmdstroketextedit.cpp, libs/librepcb/common/geometry/cmd/cmdstroketextedit.h, libs/librepcb/common/geometry/cmd/cmdtextedit.cpp, libs/librepcb/common/geometry/cmd/cmdtextedit.h, libs/librepcb/common/geometry/path.cpp, libs/librepcb/common/geometry/path.h, libs/librepcb/library/pkg/cmd/cmdfootprintpadedit.cpp, libs/librepcb/library/pkg/cmd/cmdfootprintpadedit.h, libs/librepcb/library/sym/cmd/cmdsymbolpinedit.cpp, libs/librepcb/library/sym/cmd/cmdsymbolpinedit.h, libs/librepcb/libraryeditor/pkg/fsm/cmd/cmddragselectedfootprintitems.cpp, libs/librepcb/libraryeditor/pkg/fsm/cmd/cmddragselectedfootprintitems.h, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_select.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_select.h, libs/librepcb/libraryeditor/sym/fsm/cmd/cmddragselectedsymbolitems.cpp, libs/librepcb/libraryeditor/sym/fsm/cmd/cmddragselectedsymbolitems.h, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_select.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_select.h
In the package- and symbol editors, provide a "snap to grid" context menu item when selecting elements which are not aligned to the grid (if aligned, the menu item is not shown since it would do nothing). Just like already present in the board editor.
Fixes #860.
=> Library editor: Provide "snap to grid" context menu item

ci/azure-jobs-linux.yml, ci/azure-jobs-macos.yml, ci/azure-jobs-windows.yml, tests/funq/requirements.txt, tests/unittests/common/sqlitedatabasetest.cpp
After several years of annoying issues with this unit test on Windows (because Windows cannot reliably remove files, run multiple threads at the same time, and because Windows is incredibly slow), I have no more nerves to maintain this unittest. So I heavily simplified it to use only a single thread in addition to the main thread. This is actually the main use-case for SQLiteDatabase, so I think we don't loose a lot of important test coverage.
I really hope this finally fixes the constantly failing CI pipelines. It is a huge pain to have so many CI failures.
=> SQLiteDatabaseTest: Simplify flaky concurrency test case

apps/librepcb/controlpanel/controlpanel.cpp, apps/librepcb/main.cpp, libs/librepcb/common/common.pro, libs/librepcb/common/dialogs/directorylockhandlerdialog.cpp, libs/librepcb/common/dialogs/directorylockhandlerdialog.h, libs/librepcb/common/dialogs/directorylockhandlerdialog.ui, libs/librepcb/common/fileio/directorylock.cpp, libs/librepcb/common/fileio/directorylock.h, libs/librepcb/common/fileio/transactionalfilesystem.cpp, libs/librepcb/common/fileio/transactionalfilesystem.h, libs/librepcb/libraryeditor/common/editorwidgetbase.cpp, libs/librepcb/libraryeditor/lib/libraryoverviewwidget.cpp, libs/librepcb/libraryeditor/lib/libraryoverviewwidget.h, libs/librepcb/libraryeditor/libraryeditor.cpp, libs/librepcb/workspace/workspace.cpp, libs/librepcb/workspace/workspace.h, tests/unittests/common/fileio/directorylocktest.cpp
If a workspace, project or library directory is locked by a `.lock` file but we are not 100% sure if the lock is still valid, the error message dialog now provides the ability to discard the lock and open the directory anyway:
This is especially useful when running LibrePCB as a Flatpak since due to PID namespacing we are not able to check if the application holding a lock is still running or not.
But if we are absolutely sure the lock is still valid, this option is not available since generally it could be dangerous to discard file locks.
Fixes #734
=> Allow opening locked workspace/project/library in some cases

libs/librepcb/libraryeditor/cmp/componentsignallistmodel.cpp
Removed the text of the component signal checkbox for choosing "required" or "optional" to avoid confusion what state the checkbox actually has. Instead, the column title "Connection" is now changed to "Required" and the tooltip is more descriptive.
It's a bit ugly now since the checkbox is not centered. I tried to center it but found no reliable, simple way to do so...
Fixes #475
=> Component editor: Remove checkbox text "required/optional"

libs/librepcb/library/library.pro, libs/librepcb/library/pkg/msg/msgpadclearanceviolation.cpp, libs/librepcb/library/pkg/msg/msgpadclearanceviolation.h, libs/librepcb/library/pkg/packagecheck.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_addholes.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_addholes.h, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_addpads.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_addpads.h
In the package editor, it was not possible to place two consecutive pads at the same position, see #836. This was strange behavior since after leaving and re-entering the "place pad" tool it was possible. The same applied to the "add hole" tool. To fix this strange behavior, I removed this limitation, so it is now possible to place to consecutive pads or holes at the same position.
However, now it's easier to accidentally place multiple pads at the same position without realizing it. Thus I implemented a package check which shows a warning if the clearance between two pads is <200um (so it also warns about overlapping pads). For holes I didn't implement such a warning since there might be situations where this is intended, and overlapping holes cannot lead in short circuits, in contrast …
=> Package editor: Stop rejecting but warn about overlapping pads

libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorfsm.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorfsm.h, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate.h, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate_drawwire.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate_drawwire.h, libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp
When drawing wires in the schematic editor, snap the wire even to symbol pins or junctions not located on the grid. When pressing the SHIFT key while drawing, snapping is temporarily disabled.
Fixes #371.
=> Schematic editor: Snap wires to pins/junctions off the grid

libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate_addvia.cpp, libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate_addvia.h
In the "add via" tool, do not reject placing the via anymore if there are pads or vias at the cursor position, or traces of other net signals. It could be annoying usability if the tool rejects to place a via in some situations. For example placing a via in a high density area might not be possible without creating short circuits. But often you still want to place the via (temporarily creating a short circuit) and move traces away afterwards. The tool should not reject you from doing this. If you do it and don't realize that you created a short circuit, the DRC will raise an error anyway when running the next time.
In addition, I made another change related to this feature: When placing a via with the "auto net" feature, so far only traces were taken into account to determine the net at …
=> Board editor: Do not reject placing vias on top of other items

dev/format_code.sh
Allow the `CLANGFORMAT` environmental variable to override `clang-format`
=> Allow overriding clang-format with environment variable

libs/librepcb/common/geometry/netlabel.cpp, libs/librepcb/common/geometry/netlabel.h, libs/librepcb/project/schematics/cmd/cmdschematicnetlabeladd.cpp, libs/librepcb/project/schematics/cmd/cmdschematicnetlabeladd.h, libs/librepcb/project/schematics/cmd/cmdschematicnetlabeledit.cpp, libs/librepcb/project/schematics/cmd/cmdschematicnetlabeledit.h, libs/librepcb/project/schematics/graphicsitems/sgi_netlabel.cpp, libs/librepcb/project/schematics/items/si_netlabel.cpp, libs/librepcb/project/schematics/items/si_netlabel.h, libs/librepcb/projecteditor/cmd/cmdcombineschematicnetsegments.cpp, libs/librepcb/projecteditor/cmd/cmdmirrorselectedschematicitems.cpp, libs/librepcb/projecteditor/cmd/cmdpasteschematicitems.cpp, libs/librepcb/projecteditor/cmd/cmdremoveselectedschematicitems.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate_addnetlabel.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate_addnetlabel.h, tests/unittests/projecteditor/schematiceditor/schematicclipboarddatatest.cpp
Allow the NetLabel(s) to be aligned based on the standard 9 position Alignment.
Works with the CmdMirrorSelectedSchematicItems command.
=> Support mirroring alignment of schematic net labels

README.md, apps/librepcb/controlpanel/controlpanel.cpp, apps/librepcb/projectlibraryupdater/projectlibraryupdater.cpp, ci/azure-jobs-linux.yml, common.pri, dev/doxygen/pages/code_style_guide.md, libs/librepcb/common/debug.cpp, libs/librepcb/common/dialogs/aboutdialog.cpp, libs/librepcb/common/geometry/path.h, libs/librepcb/common/graphics/graphicsview.cpp, libs/librepcb/common/network/networkrequestbase.cpp, libs/librepcb/libraryeditor/common/editorwidgetbase.cpp, libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_select.cpp, libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_select.cpp, libs/librepcb/projecteditor/boardeditor/boardeditor.cpp, libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate_select.cpp, libs/librepcb/projecteditor/projecteditor.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate_addcomponent.cpp, libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorstate_select.cpp, libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp, tests/unittests/common/fileio/directorylocktest.cpp, tests/unittests/common/systeminfotest.cpp
Now it seems to be time to get rid of the Ubuntu 14.04 CI job since it suddenly stopped working due to https://github.com/pypa/pypi-support/issues/978 :wink:
As explained in #766, both Ubuntu and Debian do no longer provide support for distributions shipping a Qt version older than 5.5, so it should be totally fine to drop support for Qt 5.2, 5.3 and 5.4.
This might even make @rnestler happy! :smiley: However, probably he now wants to drop support for Qt5.5 as well...
=> Drop support for Qt < 5.5

libs/librepcb/projecteditor/dialogs/bomgeneratordialog.cpp, libs/librepcb/projecteditor/dialogs/bomgeneratordialog.ui
As explained in #584, it can happen that one adds a device to the board which is different to the device pre-selected in the schematic. Currently it's very hard to detect such inconsistencies.
Maybe we should raise ERC warnings in this situation, I'm still thinking about what would be the best solution. Anyway, I think it makes sense to show a message in the BOM export dialog about the consistency of devices between board and schematic, since this information is most relevant when generating the BOM.
This is how it looks now when all devices are in sync with the schematic:
Or when there are inconsistencies:
And if no board is selected at all, there is a note that no devices will be exported at all:
=> BOM Export: Show whether devices are in sync with schematic

libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_deviceproperties.ui
Remove spurious ampersand.
Fixes #844
=> Library Editor: fix typo

libs/librepcb/projecteditor/boardeditor/unplacedcomponentsdock.cpp, libs/librepcb/projecteditor/boardeditor/unplacedcomponentsdock.h, libs/librepcb/projecteditor/boardeditor/unplacedcomponentsdock.ui
Heavily refactoring and improving the `UnplacedComponentsDock` widget of the board editor:
- Sort component list and device dropdown items numerically (e.g. "R2" before "R10") for a more intuitive order
- Mark components with a pre-selected device (in the schematic) by ✔ in the list to see which components don't need to manually choose a device
- Support adding components to board by double-click on a list item
- Support adding devices/packages even if they do not exist in the workspace library, but are already contained in the project library.
- Add checkbox to view and even edit the device which is pre-selected in the schematic to avoid needing to switch to the schematic editor to change the pre-selected devices
- Support adding all components with pre-selected device (in the schematic) …
=> Board editor: Refactor and improve "Place Devices" dock

libs/librepcb/common/fileio/asynccopyoperation.cpp, tests/unittests/common/fileio/asynccopyoperationtest.cpp, tests/unittests/unittests.pro
Due to several issues in `AsyncCopyOperation`, migrating a workspace from v0.1 to v0.2 might have failed or even crashed in some cases -> fixed these issues and added corresponding unit tests.
Fixes #893.
=> Fix potential errors or crash when migrating workspace file format

libs/librepcb/projecteditor/docks/ercmsgdock.cpp
Hide empty root nodes (with the error or warning symbol) in the ERC messages dock to avoid potential confusion.
Fixes #28.
=> ERC messages dock: Hide empty root nodes (categories)

libs/librepcb/libraryeditor/lib/libraryoverviewwidget.cpp, tests/funq/libraryeditor/test_overview_tab.py
Currently, the "delete" action has shown a message box to confirm deleting the selected items, even though there were no items selected (i.e. no library elements will be deleted). Now this message box is only shown if there are really some items selected.
In addition, I adjusted the corresponding functional test to explicitly select the items to delete. This is the annoying flaky test on CI, let's hope this change makes it more reliable...
=> Library editor: Ignore delete command if no items selected

libs/librepcb/projecteditor/boardeditor/boardeditor.cpp
To avoid wasting space, especially since most projects have only one board anyway. The tab bar is now automatically shown if there are two or more boards, and hidden otherwise.
Fixes #886.
=> Board editor: Hide tabs if there are less than two boards

apps/librepcb/firstrunwizard/firstrunwizardpage_workspacepath.cpp
By default, the workspace path suggested by the first run wizard is `$HOME/LibrePCB-Workspace`. However, depending on the deployment method, `$HOME` might be some kind of sandboxed folder, possibly even deleted when uninstalling LibrePCB (e.g. like Snap packages), which would be a horrible location to store the workspace (risk of loosing all libraries and projects!).
This patch now allows to override the default workspace path with the environment variable `LIBREPCB_DEFAULT_WORKSPACE_PATH`, which the Snap package can (and should) set to a more reasonable folder (probably `$SNAP_REAL_HOME/LibrePCB-Workspace`).
=> Allow overriding default workspace path by env variable

apps/librepcb/main.cpp
If the workspace path to open (e.g. loaded from user settings) does not point to a valid workspace, an error message will be shown now. Previously, the "first run"-wizard has been shown silently in this case, so the user didn't notice that there was something wrong with the specified workspace path.
If the workspace path was valid, but still failed to open for some reason (e.g. not writable), now the "first run"-wizard will be shown as well after the error message so the user is able to choose another workspace directory. Previously, the application just closed with an error message in this case, and the user had to manually reset the workspace path stored in the user settings (`$HOME/.config/LibrePCB/`) to get LibrePCB running again.
Both changes do not affect the normal behavior of …
=> Ask for new workspace path if workspace failed to open

libs/librepcb/project/boards/drc/boarddesignrulecheck.cpp, libs/librepcb/project/boards/drc/boarddesignrulecheck.h, libs/librepcb/projecteditor/boardeditor/boarddesignrulecheckdialog.cpp, libs/librepcb/projecteditor/boardeditor/boarddesignrulecheckdialog.ui, libs/librepcb/projecteditor/boardeditor/boarddesignrulecheckmessagesdock.cpp, libs/librepcb/projecteditor/boardeditor/boarddesignrulecheckmessagesdock.h, libs/librepcb/projecteditor/boardeditor/boarddesignrulecheckmessagesdock.ui, libs/librepcb/projecteditor/boardeditor/boardeditor.cpp, libs/librepcb/projecteditor/boardeditor/boardeditor.h
Restore the last dialog window position and size instead of using defaults every time opening the dialog.
- Remove status list widget on the left side of the dialog
- Display status messages as tooltip of progress bar (mouse hover)
- Display last status message as text of progress bar
- Hide progress bar until the DRC is started
- Move run button into button box (next to the close button)
- Remove yellow background of hint text, use italic font instead
By default, all checks are enabled. But now the user can disable specific checks to focus on specific things. For example, it might be useful to disable the check for missing connections if the layout is not finished yet. Or the rebuild of planes can be disabled since this can consume quite some time, even though the user might know they …
=> DRC: Support partial checks & quick re-run from dock widget

libs/librepcb/common/undostack.cpp, libs/librepcb/common/undostack.h, libs/librepcb/projecteditor/projecteditor.cpp, libs/librepcb/projecteditor/projecteditor.h
Only create a new autosave backup if there are any changes compared to the last autosave backup. Saves disk space and avoids the lagging UI during autosave, if not really needed.
Fixes #895
=> Project editor: Only autosave project if there were changes

libs/librepcb/libraryeditor/libraryeditor.ui, libs/librepcb/projecteditor/boardeditor/boardeditor.cpp
On MacOS, so far the tab bars in the library- and board editors had the look of a settings dialog or so:
But actually the tab items represent the currently opened "documents". With the "document mode" enabled, now it looks like this:
Unfortunately the tab titles are still cropped too much, they are almost not readable but I don't know why this happens :sob:
I guess other operating systems are not affected by this change since most systems don't distinguish between these two styles.
=> Library/board editors: Set tab bars to document mode

CMakeLists.txt
Although for development we usually work with out-of-source builds to not cluttering up the whole source directory with output files, there are situations where in-source builds are totally fine, or even much easier to use than out-of-source builds.
For example, Snapcraft uses in-source builds and it would be a nightmare to manually override the build commands to use out-of-source builds. Maybe there are also other packaging systems which have some kind of pre-defined CMake build workflow where out-of-source builds are not supported. You can also imagine building LibrePCB in a Docker container where it is just irrelevant if the output files are created in-source (but it's simpler, since no mkdir && cd is needed).
I think the risk of annoying developers by accidentally doing an in-source …
=> CMake: Allow in-source builds

cmake/MacOSXBundleInfo.plist.in
Seems to fix the HiDPI issue on macOS, see #944.
Closes #944.
=> MacOS: Enable HiDPI support in Info.plist

libs/librepcb/editor/project/addcomponentdialog.cpp, libs/librepcb/editor/project/addcomponentdialog.h, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_addcomponent.cpp, libs/librepcb/editor/workspace/categorytreemodel.cpp, libs/librepcb/editor/workspace/categorytreemodel.h, tests/unittests/CMakeLists.txt, tests/unittests/editor/project/addcomponentdialogtest.cpp, tests/unittests/editor/workspace/categorytreemodeltest.cpp
I got the feedback that it is counterintuitive that the "Add Component"-dialog automatically appears again when aborting placement (e.g. with the escape key), in particular when you only want to add one component to the schematic. Generally I agree, but still think that in most cases this is handy since it avoids to manually open the dialog many times.
Thus I made this behavior configurable with a checkbox:
The checkbox is checked by default (i.e. current behavior is kept) but its state is memorized in the user settings and automatically restored the next time. So if you don't like the auto-open feature, just disable it once and it will never open again automatically.
Additional improvements:
- The window size is now saved and restored automatically as well.
- The dialog selection is no …
=> Schematic editor: Keep state of "Add Component"-dialog and make auto-open optional

libs/librepcb/editor/project/boardeditor/boardviapropertiesdialog.cpp, libs/librepcb/editor/project/boardeditor/boardviapropertiesdialog.h, libs/librepcb/editor/project/boardeditor/boardviapropertiesdialog.ui, libs/librepcb/editor/project/cmd/cmdboardviaedit.cpp, libs/librepcb/editor/project/schematiceditor/symbolinstancepropertiesdialog.cpp, libs/librepcb/editor/project/schematiceditor/symbolinstancepropertiesdialog.h, libs/librepcb/editor/project/schematiceditor/symbolinstancepropertiesdialog.ui
Almost all property dialogs already have an "apply" button (which is sometimes quite useful to see the result of the change without closing the dialog), but the "Via Properties" (board editor) and "Component Properties" (schematic editor) dialogs didn't have that button. This PR adds an apply button to these dialogs as well.
=> Add "apply" button to via- and component properties dialog

libs/librepcb/core/geometry/path.cpp, libs/librepcb/core/geometry/path.h, libs/librepcb/core/geometry/vertex.cpp, libs/librepcb/core/geometry/vertex.h, libs/librepcb/core/types/point.cpp, tests/unittests/core/geometry/pathtest.cpp, tests/unittests/core/project/board/boardplanefragmentsbuildertest.cpp, tests/unittests/core/types/pointtest.cpp
When rotating points around another point with an angle other than a multiple of 90°, currently the result was not rounded to the nearest integer. This lead to small deviations in plane calculations and therefore also affected the Gerber output.
The issue is not critical at all since most PCBs only place devices with 90° angles and the deviations were very small, but still this issue should be fixed ;) Also added a unit test to check the rounding behavior.
=> Fix missing rounding in Point::rotate()

libs/librepcb/editor/project/cmd/cmddeviceinstanceeditall.cpp
When manually entering a new rotation value for a device in the device properties dialog, the a wrong rotation was applied for mirrored (bottom side) devices. Only for non-mirrored (top side) devices the rotation worked properly.
Fixed by considering the inverted rotation behavior for mirrored devices in the corresponding undo command.
=> Board editor: Fix modifying rotation of mirrored devices

libs/librepcb/editor/project/addcomponentdialog.cpp, libs/librepcb/editor/project/addcomponentdialog.h, libs/librepcb/editor/project/addcomponentdialog.ui, tests/unittests/editor/project/addcomponentdialogtest.cpp
The "Add more" checkbox (introduced in #951) placement position was managed by `QDialogButtonBox` and was therefore depending on the operating system. On Windows, it was placed between the "Ok" and "Cancel" buttons, which is very strange.
Now managing the layout manually with `QLayout` to ensure the checkbox is always on the left side of both buttons.
=> AddComponentDialog: Fix placement of "Add more" checkbox

libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp
- Fix opening 2 projects when double-clicking on a recent project (see #293). This is done by delaying the update of `QListView` by 500ms (a bit ugly, but fixes the problem and doesn't really matter since during this delayed update, the ControlPanel is in background anyway since a project was just opened).
- Set "wait cursor" while opening project - when clicking on a project, this gives immediate feedback that the application is busy with loading the project. The cursor is reset to normal once the project is fully opened.
Fixes #293.
=> Control panel: Fix UX flaws due to blocking UI when opening project

libs/librepcb/core/types/angle.h, tests/unittests/core/types/angletest.cpp
Similar to #954, floats were not rounded to the nearest integer when converting floating point angles (degrees or radians) to `Angle` objects which use integers for the angle representation. Slightly improves accuracy of some operations (including Gerber output in some cases).
=> Fix inaccuracies in float<->integer angle conversions

libs/librepcb/editor/dialogs/dxfimportdialog.cpp, libs/librepcb/editor/dialogs/dxfimportdialog.h, libs/librepcb/editor/dialogs/dxfimportdialog.ui, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_select.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_select.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_select.cpp, tests/unittests/editor/dialogs/dxfimportdialogtest.cpp
Often DXF files contain multiple straight lines which are tangent instead of a single polyline consisting of multiple segments. When importing such DXF files, it sometimes causes problems. Especially board outlines will not work properly if it's not a single, closed polygon.
Now the DXF import dialog provides an option "Join tangent polylines". If checked (the default), tangent lines will automatically be joined and converted to polygons. This reduces the risk to import invalid board outlines.
=> DXF Import: Support joining tangent polylines

libs/librepcb/core/project/board/boardplanefragmentsbuilder.cpp
Non-closed plane outlines (i.e. last vertex position != first vertex position) make no sense so lat's implicitly consider them as closed paths. This way they are filled properly even if the outline is not a closed path.
Fixes #948.
=> Fix half-filled plane if outline is not a closed path

libs/librepcb/core/project/board/graphicsitems/bgi_footprintpad.cpp, libs/librepcb/core/project/board/graphicsitems/bgi_footprintpad.h, libs/librepcb/core/project/board/graphicsitems/bgi_netline.cpp, libs/librepcb/core/project/board/graphicsitems/bgi_netline.h, libs/librepcb/core/project/board/graphicsitems/bgi_netpoint.cpp, libs/librepcb/core/project/board/graphicsitems/bgi_netpoint.h, libs/librepcb/core/project/board/graphicsitems/bgi_plane.cpp, libs/librepcb/core/project/board/graphicsitems/bgi_plane.h, libs/librepcb/core/project/board/graphicsitems/bgi_via.cpp, libs/librepcb/core/project/board/graphicsitems/bgi_via.h
The tooltip of footprint pads, vias and traces were shown on hover even if the item was actually not visible (layer disabled), which is strange. Now `QGraphicsItem::setVisible()` is called to ensure the tooltips are only enabled if the item is visible.
Fixes #938
=> Board editor: Fix tooltips for invisible items

libs/librepcb/core/geometry/via.cpp, libs/librepcb/editor/project/boardeditor/boardviapropertiesdialog.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_addvia.cpp
Automatically increase the via size or decrease the drill diameter to avoid creating vias with a drill diameter larger than the size:
Fixes #946.
=> Board editor: Avoid creating vias with drill>size

libs/librepcb/core/geometry/stroketext.cpp, libs/librepcb/core/graphics/graphicspainter.cpp, libs/librepcb/core/graphics/graphicspainter.h, libs/librepcb/core/graphics/primitivetextgraphicsitem.cpp, libs/librepcb/core/graphics/primitivetextgraphicsitem.h, libs/librepcb/core/graphics/textgraphicsitem.cpp, libs/librepcb/core/graphics/textgraphicsitem.h, libs/librepcb/core/library/pkg/footprintpadgraphicsitem.cpp, libs/librepcb/core/library/pkg/footprintpainter.cpp, libs/librepcb/core/library/sym/symbolpainter.cpp, libs/librepcb/core/library/sym/symbolpin.h, libs/librepcb/core/library/sym/symbolpingraphicsitem.cpp, libs/librepcb/core/library/sym/symbolpingraphicsitem.h, libs/librepcb/core/project/board/boardpainter.cpp, libs/librepcb/core/project/schematic/graphicsitems/sgi_netlabel.cpp, libs/librepcb/core/project/schematic/graphicsitems/sgi_symbol.cpp, libs/librepcb/core/project/schematic/graphicsitems/sgi_symbolpin.cpp, libs/librepcb/core/project/schematic/schematicpainter.cpp, libs/librepcb/core/project/schematic/schematicpainter.h, libs/librepcb/core/utils/toolbox.cpp, libs/librepcb/core/utils/toolbox.h, libs/librepcb/editor/library/sym/symbolpinpreviewgraphicsitem.cpp, libs/librepcb/editor/library/sym/symbolpreviewgraphicsitem.cpp, tests/unittests/core/utils/toolboxtest.cpp
- Fix possibly wrong symbol/pin text auto-rotations in some cases
- Fix inconsistent height of symbol texts between symbol editor and schematic editor
Fixes #534
Replaces #556
=> Fix rotation & height of some symbol / pin texts

libs/librepcb/core/project/projectlibrary.cpp
Nothing critical since in fact this code path is most probably never taken, but it's still a bug and could also lead to a compiler warning.
=> ProjectLibrary: Fix nullpointer dereference in error handler

cmake/FindMuParser.cmake
Building LibrePCB with unbundled MuParser on Arch Linux currently fails,
because the target `MuParser::MuParser` is not defined. Because this
used to work before, I assume the target was renamed from
`MuParser::MuParser` to `muparser::muparser` some time ago.
To fix this, add an alias if the CMake package was found, but the pascal
case alias isn't defined yet.
=> CMake: Add alias for muparser target

libs/librepcb/editor/dialogs/graphicsexportdialog.cpp
Some operations of the board editor graphics export dialog were very
slow due to unintended recurions. Fixed by blocking the corresponding
Qt signals.
=> GraphicsExportDialog: Fix slow UI due to recursion

libs/librepcb/core/project/board/graphicsitems/bgi_footprint.cpp, libs/librepcb/core/project/board/graphicsitems/bgi_footprint.h, libs/librepcb/core/project/schematic/graphicsitems/sgi_symbol.cpp
Zooming to a footprint was broken in #975 due to empty graphics items bounding rect...
=> Board editor: Fix broken "go to device" zoom

libs/librepcb/editor/library/pkg/footprintpadpropertiesdialog.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorfsm.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorfsm.h, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_addholes.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_addpads.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_drawcircle.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_drawpolygonbase.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_drawtextbase.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorfsm.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorfsm.h, libs/librepcb/editor/library/sym/fsm/symboleditorstate_addpins.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_drawcircle.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_drawpolygonbase.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_drawtextbase.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorfsm.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_addhole.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_addstroketext.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_addvia.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawplane.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawplane.h, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawpolygon.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawpolygon.h, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawtrace.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorfsm.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_addcomponent.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_addnetlabel.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_addtext.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_drawpolygon.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_drawpolygon.h, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_drawwire.cpp
- Implement consistent right-click behavior in all editors
- Fix inconsistent cursors of some tools
- Avoid creating vias and pads with drill>size everywhere (#963 didn't fix it everywhere)
=> Fix some inconsistent behavior in editors

libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_addcomponent.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_addcomponent.h
The component chooser dialog (AddComponentDialog) was shown after
adding a standard component from the component toolbar (e.g. resistor)
if previously a component was added with the component chooser dialog.
Regression from #951.
=> Schematic editor: Fix opening component chooser dialog

libs/librepcb/editor/library/libraryeditor.cpp, libs/librepcb/editor/library/libraryeditor.h, libs/librepcb/editor/library/libraryeditor.ui, libs/librepcb/editor/project/boardeditor/boardeditor.cpp, libs/librepcb/editor/project/boardeditor/boardeditor.h, libs/librepcb/editor/project/boardeditor/boardeditor.ui, libs/librepcb/editor/project/schematiceditor/schematiceditor.cpp, libs/librepcb/editor/project/schematiceditor/schematiceditor.h, libs/librepcb/editor/project/schematiceditor/schematiceditor.ui, libs/librepcb/editor/widgets/searchtoolbar.cpp, libs/librepcb/editor/widgets/searchtoolbar.h
The "search" toolbar was already added to all editors some time ago. However, so far you had to manually move the cursor into that toolbar to start searching, go to the next result (pressing Enter again) or to clear the search keyword. This PR adds several improvements to this feature:
- Add "Find" entry to the menus of all editors, with the keyboard shortcut Ctrl+F. So in any editor you can now press Ctrl+F to move the focus to the search field, then just start typing the term to search for.
- Add "Find Next" and "Find Previous" entries to the menu of the schematic- and board editor, with keyboard shortcuts F3 resp. Shift+F3. These allow to navigate to the next/previous search result even if the focus is not in the search toolbar anymore.
- Fix non-numeric order of search results (e.g. …
=> Implement "Find" and "Find Next/Previous" in editors

libs/librepcb/editor/project/schematiceditor/schematicclipboarddata.h, libs/librepcb/editor/project/schematiceditor/schematicclipboarddatabuilder.cpp
Components with multiple symbols (gates) were added multiple times
to the circuit after copy&paste, leading in stale components which
could not be removed anymore since they had no symbol in the schematic.
See
https://librepcb.discourse.group/t/removed-components-devices-still-in-project/472
=> Schematic editor: Fix copy&paste of multi-symbol components

libs/librepcb/core/utils/toolbox.cpp, tests/unittests/CMakeLists.txt, tests/unittests/core/geometry/pathtest.cpp, tests/unittests/core/utils/clipperhelperstest.cpp, tests/unittests/core/utils/toolboxtest.cpp
Due to potential numeric inaccuracy which was observed with "-march=haswell" (see #974), the argument passed to `qSqrt()` could be a tiny negative number instead of zero, which leads to NaN return value and thus various problems, for example broken plane fragment calculations. Probably it is caused by floating-point optimizations. Fixed it by clipping negative numbers to zero.
Fixes #974
=> Fix potential numeric issues with "-march=haswell"

libs/librepcb/core/workspace/workspacesettings.cpp, libs/librepcb/core/workspace/workspacesettings.h, libs/librepcb/editor/library/pkg/packageeditorwidget.cpp, libs/librepcb/editor/library/sym/symboleditorwidget.cpp, libs/librepcb/editor/project/boardeditor/boardeditor.cpp, libs/librepcb/editor/project/boardeditor/fabricationoutputdialog.cpp, libs/librepcb/editor/project/boardeditor/fabricationoutputdialog.h, libs/librepcb/editor/project/bomgeneratordialog.cpp, libs/librepcb/editor/project/bomgeneratordialog.h, libs/librepcb/editor/project/orderpcbdialog.cpp, libs/librepcb/editor/project/orderpcbdialog.h, libs/librepcb/editor/project/projecteditor.cpp, libs/librepcb/editor/project/schematiceditor/schematiceditor.cpp, libs/librepcb/editor/utils/editortoolbox.cpp, libs/librepcb/editor/utils/standardeditorcommandhandler.cpp, libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp, libs/librepcb/editor/workspace/desktopservices.cpp, libs/librepcb/editor/workspace/desktopservices.h, libs/librepcb/editor/workspace/workspacesettingsdialog.cpp, libs/librepcb/editor/workspace/workspacesettingsdialog.h, libs/librepcb/editor/workspace/workspacesettingsdialog.ui, tests/unittests/core/workspace/workspacesettingstest.cpp, tests/unittests/editor/project/orderpcbdialogtest.cpp
- Rework external PDF reader config:
- Allow configuring *multiple* custom commands instead of only one. LibrePCB will iterate through the list of custom commands until one of them succeeds. This is important because the workspace is intended to be platform independent, but configuring only one PDF reader command is not portable. Now you can add the PDF reader of *each* of your computers, which makes it much more portable.
- Remove setting "use custom PDF reader" - I'm not sure if this is really needed. If you don't want a custom PDF reader, just don't configure custom commands...
- Remove setting "PDF open behavior [always/never/ask]" since it was not used anymore. Export dialogs contain a checkbox to choose whether to open the PDF or not.
- Make the web browser and file manager commands …
=> Workspace setting: Extend external applications config

ci/azure-jobs-macos.yml
The macOS 10.15 image is not working anymore because it's deprecated.
=> CI: Update macOS job to macOS 11 Big Sur

libs/librepcb/core/project/board/boardpickplacegenerator.cpp, libs/librepcb/core/project/board/items/bi_device.cpp, libs/librepcb/core/project/board/items/bi_device.h, libs/librepcb/core/project/bomgenerator.cpp
Currently, exported pick&place and BOM files contained even devices like the "LibrePCB Logo" which makes no sense since this is not a real device you need to mount. Often such devices do not have any pads, while real devices do have pads. Thus let's skip devices without pads in the pick&place and BOM export.
However, if this auto-detection fails in some edge cases, an attribute `MOUNT_TYPE` could be added to these devices, set to `THT`, `SMT`, `FIDUCIAL` or `NONE`. This overrides the auto-detection. These values will also be used later in the Gerber X3 pick&place export since Gerber specifies these values.
Note that this is just a quick temporary solution (without file format changes) until a more explicit solution is implemented as described in #1001. I think this is good enough for now.
=> By default, skip devices without pads in BOM/pick&place export

apps/librepcb-cli/commandlineinterface.cpp, libs/librepcb/core/export/gerberaperturelist.cpp, libs/librepcb/core/export/gerberaperturelist.h, libs/librepcb/core/export/gerberattribute.cpp, libs/librepcb/core/export/gerberattribute.h, libs/librepcb/core/export/gerbergenerator.cpp, libs/librepcb/core/export/gerbergenerator.h, libs/librepcb/core/project/board/boardgerberexport.cpp, libs/librepcb/core/project/board/boardgerberexport.h, libs/librepcb/editor/project/boardeditor/boardeditor.cpp, libs/librepcb/editor/project/boardeditor/boardpickplacegeneratordialog.cpp, libs/librepcb/editor/project/boardeditor/boardpickplacegeneratordialog.h, libs/librepcb/editor/project/boardeditor/boardpickplacegeneratordialog.ui, libs/librepcb/editor/project/boardeditor/fabricationoutputdialog.cpp, tests/unittests/core/export/gerberaperturelisttest.cpp, tests/unittests/core/export/gerberattributetest.cpp, tests/unittests/core/export/gerbergeneratortest.cpp, tests/unittests/core/project/board/boardgerberexporttest.cpp
In addition to the existing CSV pick&place export, this PR adds a Gerber X3 pick&place export which is especially useful for automated assembly because it's a standardized format (in contrast to the CSV).
Closes #830
=> Implement Gerber X3 pick&place export

apps/librepcb-cli/commandlineinterface.cpp, apps/librepcb-cli/commandlineinterface.h, tests/cli/open-project/test_export_pnp.py
Adding the CLI flags `--export-pnp-top` and `--export-pnp-bottom` with support for file endings `csv` and `gbr` (Gerber X3):
```
$ librepcb-cli open-project \
--export-pnp-top="./output/{{VERSION}}/assembly/{{PROJECT}}_PnP-TOP.gbr" \
--export-pnp-bottom="./output/{{VERSION}}/assembly/{{PROJECT}}_PnP-BOT.csv" \
can2usb.lpp
Open project 'can2usb.lpp'...
Export top assembly data to './output/{{VERSION}}/assembly/{{PROJECT}}_PnP-TOP.gbr'...
- 'default' => 'output/v1/assembly/can2usb_PnP-TOP.gbr'
Export bottom assembly data to './output/{{VERSION}}/assembly/{{PROJECT}}_PnP-BOT.csv'...
- 'default' => 'output/v1/assembly/can2usb_PnP-BOT.csv'
SUCCESS
```
Implements parts of #999
=> CLI: Add support for pick&place export

libs/librepcb/editor/library/pkg/fsm/packageeditorstate_drawpolygonbase.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_drawpolygonbase.h, libs/librepcb/editor/library/sym/fsm/symboleditorstate_drawpolygonbase.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_drawpolygonbase.h
In all symbol- and package editor polygon tools (draw line, rectangle or polygon):
- Disable snapping to grid with Shift key
- Display overlay with information about the drawn element (e.g. coordinates)
- Display usage hints in status bar
Preparation for #354
=> Library editor: Improve polygon tools with Shift modifier, overlay and status messages

libs/librepcb/editor/library/newelementwizard/newelementwizardpage_packagepads.cpp, libs/librepcb/editor/library/pkg/footprintlisteditorwidget.cpp, libs/librepcb/editor/library/pkg/footprintlisteditorwidget.h, libs/librepcb/editor/library/pkg/packageeditorwidget.cpp, libs/librepcb/editor/library/pkg/packageeditorwidget.h, libs/librepcb/editor/library/pkg/packagepadlisteditorwidget.cpp, libs/librepcb/editor/library/pkg/packagepadlisteditorwidget.h, libs/librepcb/editor/library/sym/symboleditorwidget.cpp, libs/librepcb/editor/library/sym/symboleditorwidget.h
If a command was active while closing a library editor tab, in some cases it could lead to a crash due to unintended recursion during object destruction (at least in the symbol editor). Fixed by a more explicit cleanup procedure.
=> Library editor: Fix possible crash when closing tabs

libs/librepcb/core/project/board/boardgerberexport.cpp, tests/cli/open-project/test_everything.py, tests/cli/open-project/test_export_pcb_fabrication_data.py
Always generate the NPTH drill file, even if there are no NPTH drills. This avoids possibly outdated NPTH drill files after removing drills from the board. If the separate drill file causes issues with PCB manufacturers, the "merge PTH and NPTH drill files" option should be used. See #998.
Fixes #998.
=> Gerber export: Generate NPTH drill file even if empty

libs/librepcb/core/project/board/board.cpp, tests/cli/open_project/test_export_pcb_fabrication_data.py
These new built-in attributes of boards are especially useful as placeholders in output filepaths passed to the CLI. The currently often used placeholder `{{BOARD}}` is not absolutely guaranteed to be unique across all boards because board names might contain characters not allowed in filepaths, which are then removed or replaced. So theoretically it could lead to conflicting output files when exporting multiple boards (e.g. Gerber export).
With the new attributes, the placeholders `{{BOARD_INDEX}}` and `{{BOARD_DIRNAME}}` are guaranteed to be unique and do not contain illegal filepath characters, so they allow to export boards without the risk of conflicts.
Helps to make the fab.librepcb.org webservice implementation simpler, more robust and faster.
=> Implement attributes "BOARD_INDEX" and "BOARD_DIRNAME"

apps/librepcb-cli/commandlineinterface.cpp, apps/librepcb-cli/commandlineinterface.h, tests/cli/open_project/test_board_filter.py, tests/cli/open_project/test_parser.py
Just like the existing `--board` option, but allows to filter boards by index instead of by name. It's often much simpler to know the index of the board to export (e.g. `0` if the first board is desired) than the name of the board.
```
--board <name>                     The name of the board(s) to export. Can be
given multiple times. If not set, all
boards are exported.
--board-index <index>              Same as '--board', but allows to specify
boards by index instead of by name.
```
This will make the implementation of the fab.librepcb.org webservice simpler.
See #999.
=> CLI: Add open-project option "--board-index"

apps/librepcb-cli/commandlineinterface.cpp, apps/librepcb-cli/commandlineinterface.h, tests/cli/open_project/test_parser.py, tests/cli/open_project/test_remove_other_boards.py
If this flag is passed to the `open-project` command, all boards not specified with `--board` or `--board-index` will be removed from the project. The modified project might then be saved with `--save` to persist the modification.
This feature is probably a bit specific for the fab.librepcb.org use-case, but the implementation is very trivial and helps a lot to make the webservice faster and more robust. So I'd say it's worth to add it to the CLI.
See #999.
=> CLI: Add open-project option "--remove-other-boards"

ci/azure-jobs-linux.yml, ci/build_linux_portables.sh
Patching our official AppImage binaries with an experimental version of `appimagetool` which now uses a statically linked runtime not depending on `libfuse2` anymore. This makes the AppImages running on Ubuntu 22.04 without needing to install `libfuse2`, and while still working on older distributions. See details in https://github.com/AppImage/AppImageKit/issues/877.
Tested on Ubuntu 22.04, Ubuntu 16.04 and Manjaro - seems to work fine :muscle: 
Docker image update: https://github.com/LibrePCB/docker-librepcb-dev/pull/22
Fixes #980
=> CI: Patch AppImages with static runtime appimagetool

libs/librepcb/editor/workspace/librarymanager/addlibrarywidget.cpp, libs/librepcb/editor/workspace/librarymanager/librarymanager.cpp, libs/librepcb/editor/workspace/librarymanager/repositorylibrarylistwidgetitem.cpp, libs/librepcb/editor/workspace/librarymanager/repositorylibrarylistwidgetitem.h
Support finding libraries in the library manager by typing their name on the keyboard.
Fixes #780
=> Library manager: Support keyboard navigation in library lists

libs/librepcb/editor/library/eaglelibraryimportwizard/eaglelibraryimportwizardpage_result.ui, libs/librepcb/editor/project/boardeditor/boarddesignrulecheckdialog.ui, libs/librepcb/editor/project/boardeditor/boarddesignrulecheckmessagesdock.ui, libs/librepcb/editor/project/orderpcbdialog.ui, libs/librepcb/editor/widgets/statusbar.cpp, libs/librepcb/editor/workspace/librarymanager/addlibrarywidget.ui, libs/librepcb/editor/workspace/librarymanager/repositorylibrarylistwidgetitem.ui
At least on Windows (not on my Linux system) the status text of each `QProgressBar` was shown *beside* the bar, making the bar smaller than expected. Let's explicitly center the texts with `QProgressBar::setAlignment()` since this looks way better.
=> Center text in all progress bars

libs/librepcb/core/graphics/polygongraphicsitem.cpp, libs/librepcb/core/graphics/polygongraphicsitem.h, libs/librepcb/core/graphics/primitivepathgraphicsitem.cpp, libs/librepcb/core/graphics/primitivepathgraphicsitem.h, libs/librepcb/core/project/board/graphicsitems/bgi_plane.cpp, libs/librepcb/core/project/board/graphicsitems/bgi_plane.h, libs/librepcb/core/project/board/items/bi_plane.cpp
- Keep polygon/plane vertex handle size constant in terms of screen size instead of scene size, i.e. they are no longer scaled when zooming.
- Reduce size of vertex handled which are close to each other, without affecting the (invisible) area where the vertices can be grabbed. This avoids overlapping handles (which look ugly) while still allow easy dragging.
- When clicking in between two vertices which are very close to each other, do no longer grab *both* vertices (which would merge them together), but only grab the vertex which is closer to the cursor.
- Since the visual handles do no longer always correspond to the actual grab areas, the handles are now drawn blurry. This makes it clear to the user that the grab area is not always just a simple circle, but rather suggests "the nearer, …
=> Make polygon/plane vertex handle size independent of zoom

libs/librepcb/core/project/board/graphicsitems/bgi_plane.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawplane.cpp
...and in addition, also improve the "no net" error message when adding planes while there is no net available (see #828).
Fixes #828.
=> Board editor: Fix adding vertices to last plane edge

libs/librepcb/editor/library/pkg/fsm/packageeditorstate_addholes.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_addpads.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_drawcircle.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_drawpolygonbase.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_drawtextbase.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_select.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_addpins.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_drawcircle.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_drawpolygonbase.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_drawtextbase.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_select.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_addhole.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_addstroketext.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_addvia.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawplane.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawpolygon.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawtrace.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_select.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_addtext.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_drawpolygon.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_drawwire.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_select.cpp
I think it's convenient and intuitive to clear the selection with the "abort" command ('Esc' key by default). Many other software out there do this as well. At least I think it shouldn't hurt to add this.
In addition: Clear selection when leaving "select" tool
In all editors, the selection was currently cleared when *entering* any tool since selection makes no sense in any tool other than the "select" tool. However, in some tools this code was missing. Fixed by clearing the selection now when *leaving* the "select" tool and removing the corresponding code from all the other tools -> less code, less error-prone.
=> Clear selection with 'Esc' key (all editors)

ci/azure-jobs-linux.yml, cmake/FindGTest.cmake, dev/doxygen/pages/building.md, dev/doxygen/pages/mainpage.md
Adding `CONFIG` to the `find_package()` seems to fix the endless recursion which was reported in #933. I don't understand what `CONFIG` means exactly, but at least [in this](https://chromium.googlesource.com/external/github.com/pwnall/googletest/+/HEAD/googletest/README.md) documentation they also do it this way. And local testing shows that this seems to fix the problem.
In addition, I adjusted `FindGTest.cmake` to proceed even if `find_package(GMock)` failed - `find_package(GTest)` should be sufficient since GTest usually also contains GMock, so no separate package is needed for GMock.
I also extended CI to test unbundling of GTest/GMock. However, since Ubuntu doesn't provide a cmake config, I extended `FindGTest.cmake` to also search with `pkg-config` which is then used on Ubuntu. I …
=> CMake: Fix & improve unbundling of GTest/GMock

libs/librepcb/editor/workspace/projectlibraryupdater/projectlibraryupdater.cpp, libs/librepcb/editor/workspace/projectlibraryupdater/projectlibraryupdater.h, libs/librepcb/editor/workspace/projectlibraryupdater/projectlibraryupdater.ui
It was derived from `QMainWindow` although it is used like a dialog. Thus now changed its base class to `QDialog`.
Fixes #1030 (at least I ope so...)
=> Make project library updater a real dialog

libs/librepcb/editor/project/boardeditor/deviceinstancepropertiesdialog.cpp, libs/librepcb/editor/project/boardeditor/deviceinstancepropertiesdialog.h, libs/librepcb/editor/project/boardeditor/deviceinstancepropertiesdialog.ui, libs/librepcb/editor/project/boardeditor/fabricationoutputdialog.cpp, libs/librepcb/editor/project/boardeditor/fabricationoutputdialog.ui, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_select.cpp, libs/librepcb/editor/project/newprojectwizard/newprojectwizardpage_metadata.cpp, libs/librepcb/editor/project/newprojectwizard/newprojectwizardpage_metadata.h, libs/librepcb/editor/project/newprojectwizard/newprojectwizardpage_metadata.ui, libs/librepcb/editor/project/orderpcbdialog.cpp, libs/librepcb/editor/project/orderpcbdialog.ui, libs/librepcb/editor/project/schematiceditor/symbolinstancepropertiesdialog.cpp, libs/librepcb/editor/project/schematiceditor/symbolinstancepropertiesdialog.ui, libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp, libs/librepcb/editor/workspace/controlpanel/controlpanel.ui, libs/librepcb/editor/workspace/librarymanager/addlibrarywidget.cpp, libs/librepcb/editor/workspace/librarymanager/addlibrarywidget.ui, libs/librepcb/editor/workspace/librarymanager/libraryinfowidget.cpp, libs/librepcb/editor/workspace/librarymanager/libraryinfowidget.ui, libs/librepcb/editor/workspace/projectlibraryupdater/projectlibraryupdater.ui, libs/librepcb/editor/workspace/workspacesettingsdialog.cpp, libs/librepcb/editor/workspace/workspacesettingsdialog.ui
There were many hyperlinks created with `QLabel` widgets with the property `openExternalLinks` set to `true` to let Qt handle opening the hyperlinks. However, this way the links were opened with `QDesktopServices`, which does not respect the external application settings from the workspace.
Fixed by disabling `openExternalLinks` and handle the `linkActivated()` signal to open the links with our own `DesktopServices` class, and thus taking the workspace settings into account.
=> Respect external applications settings for hyperlinks

libs/librepcb/editor/project/boardeditor/boardeditor.cpp, libs/librepcb/editor/project/boardeditor/fabricationoutputdialog.cpp, libs/librepcb/editor/project/boardeditor/fabricationoutputdialog.h, libs/librepcb/editor/project/boardeditor/fabricationoutputdialog.ui
- Remove the note that the Gerber generator is experimental as it seems to be working fine for quite a long time now.
- Mention the "Order PCB" feature as a possible alternative.
- Remove yellow background color (probably less ugly, and consistent with other dialogs).
- Move buttons to button bar at the bottom, to make it more compact and consistent with other dialogs.
- Memorize & restore window size and position.
=> Polish PCB fabrication output dialog

libs/librepcb/editor/project/newprojectwizard/newprojectwizardpage_metadata.cpp
When creating a new project, the wizard provided the following entries in the license selector dropdown:
```
- No License (not recommended)
- CC0-1.0 (no restrictions, recommended for open hardware projects)
- CC-BY-4.0 (requires attribution)
- CC-BY-SA-4.0 (requires attribution + share alike)
```
With the first entry set as default. However, it is strange to use a default value which is actually not recommended (already got that feedback from users, and I agree). In addition, choosing no license is probably the typical use-case and totally fine for non-public projects (both private and commercial).
To avoid users struggling with the license selection, let's simply remove our personal recommendations and rename the dropdown entries to:
```
- None
- CC0-1.0 (no restrictions)
- CC-BY-4.0 …
```
=> New project wizard: Remove recommendation about licenses

libs/librepcb/core/workspace/workspacesettings.cpp, libs/librepcb/core/workspace/workspacesettings.h, libs/librepcb/core/workspace/workspacesettingsitem_genericvaluelist.h, libs/librepcb/editor/CMakeLists.txt, libs/librepcb/editor/widgets/messagewidget.cpp, libs/librepcb/editor/widgets/messagewidget.h, libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp, libs/librepcb/editor/workspace/controlpanel/controlpanel.h, libs/librepcb/editor/workspace/controlpanel/controlpanel.ui, libs/librepcb/editor/workspace/workspacesettingsdialog.cpp, libs/librepcb/editor/workspace/workspacesettingsdialog.h, libs/librepcb/editor/workspace/workspacesettingsdialog.ui, tests/unittests/core/workspace/workspacesettingstest.cpp
The banners can be quite annoying, so let's allow to either temporarily or permanently hide them. Added this feature to the workspace settings to store dismissed messages, and allowing to reset them all with a new button in the workspace settings dialog:
=> Control panel: Allow to hide/dismiss message banners

libs/librepcb/core/workspace/workspacelibrarydb.cpp, libs/librepcb/core/workspace/workspacelibrarydb.h, libs/librepcb/core/workspace/workspacelibraryscanner.cpp, libs/librepcb/core/workspace/workspacelibraryscanner.h, libs/librepcb/editor/CMakeLists.txt, libs/librepcb/editor/library/cat/categorychooserdialog.cpp, libs/librepcb/editor/library/cmp/componentchooserdialog.cpp, libs/librepcb/editor/library/lib/libraryoverviewwidget.cpp, libs/librepcb/editor/library/lib/libraryoverviewwidget.h, libs/librepcb/editor/library/libraryeditor.cpp, libs/librepcb/editor/library/pkg/packagechooserdialog.cpp, libs/librepcb/editor/library/sym/symbolchooserdialog.cpp, libs/librepcb/editor/project/addcomponentdialog.cpp, libs/librepcb/editor/project/boardeditor/boardeditor.cpp, libs/librepcb/editor/project/schematiceditor/schematiceditor.cpp, libs/librepcb/editor/widgets/waitingspinnerwidget.cpp, libs/librepcb/editor/widgets/waitingspinnerwidget.h, libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp, libs/librepcb/editor/workspace/librarymanager/addlibrarywidget.cpp
In all tree views and list views which show content from the workspace library database (e.g. categories, symbols, components, ...), show a spinner during the scan to indicate that the content might be outdated and will be updated soon.
This should help to avoid confusion when users add libraries or library elements, but then can't find those things in the tree/list views. Especially after installing a new library, the whole library seems to be empty for quite some time - with the spinner, it should be clear that some update is in progress:
In addition, another similar improvement: If the workspace library background scan is in progress while a new window is opened, the progress bar in the status bar did not appear immediately but only on the next progress update event (could be several …
=> Show waiting spinner in tree/list views during library scan

libs/librepcb/core/project/schematic/schematic.cpp, libs/librepcb/core/project/schematic/schematic.h, libs/librepcb/editor/project/addcomponentdialog.cpp, libs/librepcb/editor/project/addcomponentdialog.h, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorfsm.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorfsm.h, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate.h, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_addcomponent.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_addcomponent.h, libs/librepcb/editor/project/schematiceditor/schematiceditor.cpp, libs/librepcb/editor/project/schematiceditor/schematiceditor.h, libs/librepcb/editor/project/schematiceditor/schematiceditor.ui
When opened an empty schematic (which is the case after creating a new project), show a banner in the schematic editor with a hint how to add components to the schematic. The banner sugests to first add a schematic frame and provides a hyperlink to directly open the "Add Component" dialog with components filtered by the term "schematic frame". If the official base library is installed, the user will directly see the available schematic frames.
Intended to help users getting started with LibrePCB.
See also #1039 which might some day provide a better solution for adding a frame, but for now I think this banner is already very helpful.
=> Schematic editor: Show info banner if schematic is empty

apps/librepcb/main.cpp, libs/librepcb/editor/editorcommand.cpp, libs/librepcb/editor/editorcommand.h, libs/librepcb/editor/editorcommandcategory.h, libs/librepcb/editor/editorcommandset.h
Fixes a regression of #1043 which lead to missing translations of menu/toolbar entries.
=> Force applying locale to editor commands text/description

libs/librepcb/editor/library/cmp/componentchooserdialog.cpp, libs/librepcb/editor/library/cmp/componentchooserdialog.h, libs/librepcb/editor/library/newelementwizard/newelementwizardpage_copyfrom.cpp, libs/librepcb/editor/library/pkg/packagechooserdialog.cpp, libs/librepcb/editor/library/pkg/packagechooserdialog.h, libs/librepcb/editor/library/sym/symbolchooserdialog.cpp, libs/librepcb/editor/library/sym/symbolchooserdialog.h
The symbol-, component- and package search dialogs in the library editor by accident listed all library elements without a category when typing a search keyword, i.e. there were too many, unrelated search results. This was caused by using `nullopt` for representing "no category" and for "without category", so it was ambiguous.
=> Library editor: Fix possibly unrelated search results

apps/librepcb-cli/commandlineinterface.cpp, tests/cli/open_library/test_parser.py, tests/cli/open_project/test_parser.py, tests/cli/test_help.py
Use -v for --verbose instead of --version.
Added -V for --version.
This is my first pull request for this project. Let me know if I missed something :)
Fixes #1008
=> CLI: Use -v for --verbose instead of --version.

libs/librepcb/core/workspace/workspacesettings.cpp, libs/librepcb/core/workspace/workspacesettings.h, tests/unittests/core/workspace/workspacesettingstest.cpp
Remove obsolete workspace settings after upgrading the workspace to a higher major file format version. This avoids having entries in the `settings.lp` file where we have no clue what file format version they have. And it simply helps to keep that file clean instead of cluttering it up with obsolete entries.
=> Remove obsolete workspace settings after file format upgrade

tests/unittests/core/fileio/asynccopyoperationtest.cpp
Seems to fix a unittest failure on some systems.
Fixes #1061.
=> AsyncCopyOperationTest: Call processEvents() twice

libs/librepcb/core/graphics/graphicslayer.cpp, libs/librepcb/core/library/sym/symbolpainter.cpp, libs/librepcb/core/project/schematic/graphicsitems/sgi_symbol.cpp, libs/librepcb/core/project/schematic/schematicpainter.cpp
Changing the symbol grab area alpha value to 255 (no transparency) while keeping exactly the same color as currently with white background. This ensures the schematic grid is not visible anymore within symbols, which looks better in my opinion (feedback about your opinion welcome!).
With transparency (old):
Without transparency (new):
It also helps to implement #515 since an anchor line from the text origin to the symbol origin can be put *behind* the symbol to avoid an ugly overlap with the symbol.
However, unfortunately this reminded me about a weakness of the current symbol graphics items concept: So far we do not have a user-defined z-order of symbol graphics items, it is completely hardcoded (determined by item type & UUID). As the grab area is no longer transparent, some graphics …
=> Remove transparency of symbol grab areas

libs/librepcb/core/export/gerberaperturelist.cpp, libs/librepcb/core/export/gerberaperturelist.h, libs/librepcb/core/export/gerbergenerator.cpp, libs/librepcb/core/export/gerbergenerator.h, libs/librepcb/core/geometry/path.cpp, libs/librepcb/core/geometry/path.h, libs/librepcb/core/geometry/via.cpp, libs/librepcb/core/library/pkg/footprintpad.cpp, libs/librepcb/core/project/board/boardgerberexport.cpp, tests/unittests/core/export/gerberaperturelisttest.cpp, tests/unittests/core/export/gerbergeneratortest.cpp, tests/unittests/core/geometry/pathtest.cpp
Instead of expanding pad/via shapes by keeping the same shape (i.e. sharp corners), this will expand them by maintaining a constant clearance around the whole shape (i.e. make corners rounded). It affects vias and pads with either a rectangular or octagon shape, in particular:
- Cutouts of vias/pads in copper planes (see #597).
- Stop mask / cream mask via/pad shapes if their expansion is > 0.
- Both of these things will have an effect on the Gerber output.
It's not a big thing, but it is slightly more space efficient (useful for dense boards) and ensures the plane area is as large as possible. A drawback is that the generated Gerber apertures are quite some more complicated now (there are no builtin apertures for rounded rects/octagons) but I think that should not be an issue.
Closes …
=> Use rounded corners for all expanded pad/via shapes

apps/librepcb-cli/commandlineinterface.cpp, libs/librepcb/core/project/projectloader.cpp, libs/librepcb/core/project/projectloader.h, libs/librepcb/core/serialization/fileformatmigration.cpp, libs/librepcb/core/serialization/fileformatmigration.h, libs/librepcb/core/serialization/fileformatmigrationv01.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.h, libs/librepcb/editor/project/projecteditor.cpp, libs/librepcb/editor/project/projecteditor.h, libs/librepcb/editor/project/schematiceditor/schematiceditor.cpp, libs/librepcb/editor/project/schematiceditor/schematiceditor.h, libs/librepcb/editor/project/schematiceditor/schematiceditor.ui, libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp, libs/librepcb/editor/workspace/controlpanel/controlpanel.h
The file format upgrade procedure can affect projects in several ways (e.g. modifying plane calculations, conversions due to obsolete features, ...) so it would be important to inform the user about such changes.
Thus the file format upgrade mechanism is now able to build upgrade notes for each particular project and the schematic editor shows a banner to inform the user about the upgrade. A hyperlink then opens the detailed list of messages:
The banner automatically disappears when saving the project since the upgrade is non-reversible then (before saving, the user could decide to close the project, effectively keeping the old file format).
In addition, the CLI now also prints these messages to stdout.
=> Build and show list of project file format upgrade messages

libs/librepcb/core/geometry/via.cpp, libs/librepcb/core/geometry/via.h, libs/librepcb/core/project/board/boardgerberexport.cpp, libs/librepcb/core/project/board/items/bi_via.cpp, libs/librepcb/core/project/board/items/bi_via.h, libs/librepcb/core/serialization/fileformatmigrationv01.cpp, libs/librepcb/editor/project/boardeditor/boardviapropertiesdialog.cpp, libs/librepcb/editor/project/boardeditor/boardviapropertiesdialog.ui, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_addvia.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_addvia.h, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawtrace.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawtrace.h, libs/librepcb/editor/project/cmd/cmdboardviaedit.cpp, libs/librepcb/editor/project/cmd/cmdboardviaedit.h, libs/librepcb/editor/project/cmd/cmdpasteboarditems.cpp, tests/unittests/core/geometry/viatest.cpp, tests/unittests/editor/project/boardeditor/boardclipboarddatatest.cpp
So far it was possible to add vias with circular, square or octagon shape. However, vias did not support a rotation parameter so square and octagon vias could not be rotated like everything else in a board which was kind of inconsistent (for circular vias, rotation is not needed of course).
However, I think square and octagon vias do not make sense at all anyway. The only reasonable (because most space efficient) via shape is circular. In contrast to pads, no soldering is done so the shape doesn't matter (and is usually covered with soldermask anyway). So to keep things simple and intuitive, I decided to remove support for square and octagon vias. Btw, KiCad also doesn't support via shapes other than circular.
During the 0.1->0.2 file format upgrade, all non-circular vias will be …
=> Remove support for non-circular vias

libs/librepcb/core/CMakeLists.txt, libs/librepcb/core/library/pkg/msg/msgpadannularringviolation.cpp, libs/librepcb/core/library/pkg/msg/msgpadannularringviolation.h, libs/librepcb/core/library/pkg/packagecheck.cpp, libs/librepcb/core/library/pkg/packagecheck.h, libs/librepcb/core/project/board/boarddesignrules.cpp, libs/librepcb/core/project/board/boarddesignrules.h, libs/librepcb/core/project/board/boardgerberexport.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheck.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheck.h, libs/librepcb/core/project/board/graphicsitems/bgi_footprintpad.cpp, libs/librepcb/core/project/board/graphicsitems/bgi_footprintpad.h, libs/librepcb/core/project/board/graphicsitems/bgi_via.h, libs/librepcb/core/serialization/fileformatmigrationunstable.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.h, libs/librepcb/core/serialization/sexpression.cpp, libs/librepcb/core/serialization/sexpression.h, libs/librepcb/editor/project/boardeditor/boarddesignrulecheckdialog.cpp, libs/librepcb/editor/project/boardeditor/boarddesignrulecheckdialog.ui, libs/librepcb/editor/project/boardeditor/boarddesignrulesdialog.cpp, libs/librepcb/editor/project/boardeditor/boarddesignrulesdialog.ui, tests/unittests/core/project/board/boarddesignrulestest.cpp
In my experience these attributes are not really useful but just clutter up the GUI, so let's get rid of them. If we ever need a place for such user-defined text, I'd rather add a general purpose description field to the board itself.
The term annular ring seems to be used much more commonly than restring (e.g. in PCB manufacturers capabilities sheets), so let's use it in LibrePCB as well.
For consistency and to avoid confusion due to different terms for the same thing.
Just slightly rearranging the S-Expressions of the board design rules to make them logically grouped and more compact...
=> Cleanup board design rules

CMakeLists.txt
Set `CMAKE_OSX_DEPLOYMENT_TARGET` to macOS 10.14 to make our official binaries running on older macOS versions again.
Closes #1091
=> Support older macOS versions (>=10.14)

libs/librepcb/core/project/board/boardplanefragmentsbuilder.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.cpp
The 'connect style' property of planes is no longer respected for vias since isolating vias from the planes makes no sense. Isolating only makes sense for pads due to heat dissipation. See discussion in https://github.com/LibrePCB/LibrePCB/issues/454#issuecomment-1373402172.
Since this change affects projects during the v0.1 -> v0.2 migration, an upgrade message is shown to the user if there are any planes with connect style set to 'none'.
=> Always connect vias to planes, regardless of connect style

libs/librepcb/core/project/board/boardfabricationoutputsettings.cpp, libs/librepcb/editor/project/boardeditor/fabricationoutputdialog.ui
If you forget to enable the top/bottom solder paste export in the Gerber export settings but still want to order a stencil, there's a risk that the PCB manufacturer auto-generates the stencil from the stop mask layer (or from the copper layer?). But the other way around, if you don't need a stencil but forget to disable exporting these layers, I think there's no risk at all (just two unnecessary files generated). So changing from opt-in to opt-out is probably the safer option.
Also fixed some inconsistent layer naming in the UI.
=> Gerber export: Enable solder paste export by default

libs/librepcb/core/CMakeLists.txt, libs/librepcb/core/library/pkg/msg/msgoverlappingpads.cpp, libs/librepcb/core/library/pkg/msg/msgoverlappingpads.h, libs/librepcb/core/library/pkg/packagecheck.cpp
So far there was only a clearance warning if the clearance between two footprint pads was too small - even if they actually overlapped. Now an overlap is handled separately and turned into an error (instead of warning) since this can cause serious trouble.
=> Package check: Turn overlapping pads into an error

CMakeLists.txt, apps/librepcb-cli/commandlineinterface.h, libs/librepcb/core/export/graphicsexport.cpp, libs/librepcb/core/fileio/filepath.h, libs/librepcb/core/serialization/fileformatmigrationv01.h, libs/librepcb/editor/library/pkg/footprintgraphicsitem.cpp, libs/librepcb/editor/library/sym/symbolgraphicsitem.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate.cpp, libs/librepcb/editor/widgets/statusbar.h, libs/librepcb/editor/workspace/categorytreemodel.h, tests/unittests/core/fileio/filepathtest.cpp
Just because it shouldn't hurt to enforce writing more portable code...
Fixed all the warnings caused by `-Wpedantic`.
=> CMake: Compile with '-Wpedantic' flag

apps/librepcb-cli/commandlineinterface.cpp, libs/librepcb/core/project/board/board.cpp, libs/librepcb/core/project/board/board.h, libs/librepcb/core/project/board/drc/boarddesignrulecheck.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheck.h, libs/librepcb/core/project/board/items/bi_netpoint.cpp, libs/librepcb/core/project/board/items/bi_netpoint.h, libs/librepcb/core/project/erc/ercmsg.h, libs/librepcb/core/serialization/fileformatmigrationv01.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.h, libs/librepcb/editor/project/boardeditor/boardeditor.cpp, libs/librepcb/editor/project/erc/ercmsgdock.cpp
Although the ERC is nicer than the DRC because it is instantly updated, board related messages (e.g. unplaced component) are usually not of interest in the schematic editor. And in the board editor, probably nobody checks the ERC messages. So let's move these messages to the DRC to strictly distinguish between board issues (-> DRC) and schematic/circuit issues (-> ERC).
=> Move board related messages from ERC to DRC

libs/librepcb/core/project/board/drc/boarddesignrulecheck.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheck.h, libs/librepcb/core/project/board/drc/boarddesignrulecheckmessages.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheckmessages.h
Warn about devices which are different to the device configured in the schematics. For example when adding a capacitor with 0603 package to the schematics but then using 0805 in the board, the warning appears.
Closes #584
=> DRC: Warn about devices which differ from schematic

libs/librepcb/core/export/pickplacecsvwriter.cpp, libs/librepcb/core/export/pickplacedata.h, libs/librepcb/core/project/board/boardpickplacegenerator.cpp, tests/unittests/core/export/pickplacecsvwritertest.cpp
Add a new column named "Type" to pick&place files to indicate whether a device is THT, SMT, Fiducial or something else. Required by assembly services to calculate the price.
```
#
Designator,Value,Device,Package,Position X,Position Y,Rotation,Side,Type
LED1,LED 3mm Green,LED 3mm,LED 3mm,81.5,50.0,270.0,Top,THT
```
=> Add mount type column to pick&place CSV files

libs/librepcb/core/project/schematic/schematicpainter.cpp, libs/librepcb/core/project/schematic/schematicpainter.h, libs/librepcb/editor/project/schematiceditor/schematiceditor.cpp, libs/librepcb/editor/project/schematiceditor/schematicpagesdock.cpp, libs/librepcb/editor/project/schematiceditor/schematicpagesdock.h
The schematic thumbnails/previews of the "Pages" dock in the schematic editor were not updated after modifying schematics, mainly due to performance reasons since the update is a (more or less) heavy operation which would block the UI thread.
But thanks to #947 we have now the class `GraphicsExport` which allows to generate images of schematics in a worker thread, i.e. without blocking the UI. This PR now makes use of that class to generate the schematic thumbnails, which are now updated automatically after modifying schematics (for simplicity, only after adding or removing symbols).
=> Schematic editor: Live update for schematic thumbnails

apps/librepcb-cli/commandlineinterface.cpp, apps/librepcb-cli/commandlineinterface.h, tests/cli/open_project/test_parser.py, tests/cli/open_project/test_run_drc.py
Adding a new flag `--drc` to the CLI to run the DRC, exactly the same way as already implemented for the ERC. In addition, DRC settings can be overridden by passing a configuration file path with `--drc-settings=<FILE>`.
Closes #997
=> CLI: Support "--drc" flag to run the design rule check

apps/librepcb-cli/commandlineinterface.cpp, apps/librepcb-cli/commandlineinterface.h, dev/README.md, libs/librepcb/core/CMakeLists.txt, libs/librepcb/core/export/d356netlistgenerator.cpp, libs/librepcb/core/export/d356netlistgenerator.h, libs/librepcb/core/project/board/boardd356netlistexport.cpp, libs/librepcb/core/project/board/boardd356netlistexport.h, libs/librepcb/core/types/length.h, libs/librepcb/editor/editorcommandset.h, libs/librepcb/editor/project/boardeditor/boardeditor.cpp, libs/librepcb/editor/project/boardeditor/boardeditor.h, tests/cli/open_project/test_export_netlist.py, tests/cli/open_project/test_parser.py, tests/unittests/CMakeLists.txt, tests/unittests/core/export/d356netlistgeneratortest.cpp, tests/unittests/core/project/board/boardd356netlistexporttest.cpp
- In the board editor, a new menu item *File > Production Data > Generate IPC-D-356A Netlist...* has been added. It just opens a file save dialog to specify the output file (no export options needed).
- For the CLI, the option `--export-netlist=FILE` has been added to export the netlist to the given filepath. The file extension needs to be `d356` (implemented an export format auto-detection as already done for exporting schematics etc.).
How the generated file looks:
```
C  IPC-D-356A Netlist
C  
C  Project Name:        test_project
C  Project Version:     v1
C  Board Name:          default
C  Generation Software: LibrePCB 0.2-unstable
C  Generation Date:     2023-01-10T10:30:05+01:00
C  
C  Note that due to limitations of this file format, LibrePCB
C  applies the following operations …
```
=> Implement IPC-D-356A netlist export for boards

apps/librepcb-cli/commandlineinterface.cpp, libs/librepcb/core/project/project.cpp, libs/librepcb/core/project/project.h, libs/librepcb/core/project/projectloader.cpp, libs/librepcb/core/serialization/fileformatmigrationunstable.cpp, libs/librepcb/core/serialization/fileformatmigrationunstable.h, libs/librepcb/core/serialization/fileformatmigrationv01.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.h, libs/librepcb/editor/project/boardeditor/boardeditor.cpp, libs/librepcb/editor/project/bomgeneratordialog.cpp, libs/librepcb/editor/project/bomgeneratordialog.h, libs/librepcb/editor/project/schematiceditor/schematiceditor.cpp
Persistently store the configured custom BOM attributes in the project file `project/settings.lp`. Not sure if this will still be needed once #1000 is implemented, but it was easy and allows to close #624 now :see_no_evil: 
Closes #624
=> BOM export: Store custom BOM attributes in project files

libs/librepcb/core/library/pkg/footprintpad.cpp, libs/librepcb/core/library/pkg/footprintpad.h, libs/librepcb/core/library/pkg/packagecheck.cpp, libs/librepcb/core/library/pkg/packagecheck.h, libs/librepcb/core/library/pkg/packagecheckmessages.cpp, libs/librepcb/core/library/pkg/packagecheckmessages.h, libs/librepcb/core/project/board/boardplanefragmentsbuilder.cpp, libs/librepcb/core/project/board/drc/boardclipperpathgenerator.cpp, libs/librepcb/core/project/board/drc/boardclipperpathgenerator.h, libs/librepcb/core/project/board/drc/boarddesignrulecheck.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheckmessages.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheckmessages.h, libs/librepcb/core/serialization/fileformatmigrationunstable.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.cpp, libs/librepcb/eagleimport/eagletypeconverter.cpp, libs/librepcb/editor/graphics/primitivefootprintpadgraphicsitem.cpp, libs/librepcb/editor/graphics/primitivefootprintpadgraphicsitem.h, libs/librepcb/editor/library/cmd/cmdfootprintpadedit.cpp, libs/librepcb/editor/library/cmd/cmdfootprintpadedit.h, libs/librepcb/editor/library/cmd/cmdpastefootprintitems.cpp, libs/librepcb/editor/library/newelementwizard/newelementwizardcontext.cpp, libs/librepcb/editor/library/pkg/footprintpadgraphicsitem.cpp, libs/librepcb/editor/library/pkg/footprintpadpropertiesdialog.cpp, libs/librepcb/editor/library/pkg/footprintpadpropertiesdialog.ui, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_addpads.cpp, libs/librepcb/editor/library/pkg/packageeditorwidget.cpp, libs/librepcb/editor/project/boardeditor/graphicsitems/bgi_footprintpad.cpp, tests/unittests/core/library/pkg/footprintpadtest.cpp, tests/unittests/editor/library/pkg/footprintclipboarddatatest.cpp
Adding a property 'copper clearance' to footprint pads to allow specifying a custom clearance value for particular pads. Intended mainly for fiducials to keep the area around their copper circle clear of copper. In particular, planes will keep this area clear and the DRC will warn if there are copper objects within it.
The clearance is visualized with a thin line around the copper area, and the value is configurable in the pad properties dialog:
New node `clearance`:
```
(pad 474059df-640b-4b17-98b2-148e340a7152 (side top) (shape roundrect)
(position 2.54 0.0) (rotation 90.0) (size 4.064 2.032) (radius 1.0)
(stop_mask auto) (solder_paste off) (clearance 0.0) (function unspecified)
(package_pad 474059df-640b-4b17-98b2-148e340a7152)
(hole 474059df-640b-4b17-98b2-148e340a7152 (diameter …
```
=> Add copper clearance property to footprint pads

apps/librepcb-cli/CMakeLists.txt, apps/librepcb-cli/Info.plist.in, apps/librepcb/CMakeLists.txt, apps/librepcb/Info.plist.in, ci/build_mac_bundle.sh, libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp, libs/librepcb/editor/workspace/controlpanel/controlpanel.h
This associates the *.lpp file extension on macOS with LibrePCB, done by adding the corresponding entries to the `Info.plist` file. Since this is not needed for the CLI, there are now two different `Info.plist` files.
Also fixed the ugly names of the mounted DMG volume and the application shortcut, now they are displayed as "LibrePCB".
Tested on macOS 11.7, seems to work fine so far. Unfortunately I needed to use the deprecated key `CFBundleTypeExtensions` because I was not able to get it working with the newer key `LSItemContentTypes` :-/
See also the related issue #1058.
=> MacOS: Register *.lpp file extension

CMakeLists.txt, share/applications/org.librepcb.LibrePCB.desktop
The `*.desktop` file to integrate LibrePCB into Linux desktop environments contains a comment string which is intended to be translated into multiple languages, but there was only a single translation hardcoded so far. I extended our i18n automation script to also push the string from the `*.desktop` file to Transifex to allow translating it by translators. The translated file will then show up within the `i18n` directory. This PR makes sure this file (if it exists) gets installed with `make install`.
=> Linux: Support translating desktop entry comment

libs/librepcb/core/project/project.cpp, libs/librepcb/core/project/project.h, libs/librepcb/core/serialization/fileformatmigrationunstable.cpp, libs/librepcb/core/serialization/fileformatmigrationunstable.h, libs/librepcb/core/serialization/fileformatmigrationv01.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.h, libs/librepcb/core/serialization/sexpression.cpp, libs/librepcb/core/serialization/sexpression.h, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_drawtextbase.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_drawtextbase.cpp, libs/librepcb/editor/project/projectsetupdialog.cpp, libs/librepcb/editor/project/projectsetupdialog.ui, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_addtext.cpp, tests/unittests/core/project/projecttest.cpp
Renaming attribute `MODIFIED_DATE` to `DATE` and `MODIFIED_TIME` to `TIME` to fix the misleading name. See details in #1130.
Any of these strings within symbol/schematic texts or component attributes will be replaced accordingly during the file format upgrade procedure, thus no user interaction is needed.
Closes #1130.
=> Rename attributes 'MODIFIED_DATE/TIME' to 'DATE/TIME'

CMakeLists.txt, ci/azure-jobs-linux.yml, ci/azure-jobs-windows.yml, ci/build_librepcb.sh, ci/build_windows_archive.sh, tests/unittests/editor/workspace/categorytreemodeltest.cpp
Update to our latest Docker images for Windows and Linux.
On Linux, also reduce the number of pipelines from 4 to 3 (one pipeline per Ubuntu version: 18.04, 20.04, 22.04). Ubuntu 16.04 is no longer used, the official binaries are now built on Ubuntu 18.04 as the contained glibc version should be compatible with any still supported Linux distribution.
Windows is now building with Ninja instead of Make from MinGW.
=> CI: Update Docker images & build matrix

libs/librepcb/core/CMakeLists.txt, libs/librepcb/core/project/board/board.cpp, libs/librepcb/core/project/board/board.h, libs/librepcb/core/project/board/boardfabricationoutputsettings.cpp, libs/librepcb/core/project/board/boardfabricationoutputsettings.h, libs/librepcb/core/project/board/boardgerberexport.cpp, libs/librepcb/core/project/projectloader.cpp, libs/librepcb/core/serialization/fileformatmigrationunstable.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.cpp, libs/librepcb/core/types/pcbcolor.cpp, libs/librepcb/core/types/pcbcolor.h, libs/librepcb/editor/project/boardeditor/boardsetupdialog.cpp, libs/librepcb/editor/project/boardeditor/boardsetupdialog.h, libs/librepcb/editor/project/boardeditor/boardsetupdialog.ui, libs/librepcb/editor/project/boardeditor/fabricationoutputdialog.cpp, libs/librepcb/editor/project/boardeditor/fabricationoutputdialog.h, libs/librepcb/editor/project/boardeditor/fabricationoutputdialog.ui, libs/librepcb/editor/project/cmd/cmdboardedit.cpp, libs/librepcb/editor/project/cmd/cmdboardedit.h, tests/unittests/core/project/board/boardfabricationoutputsettingstest.cpp
- Support specifying PCB thickness
- Support specifying solder resist as one of:
```
None (bare copper) --> stop mask Gerber files will not be generated
Black
Black Matte
Blue
Green
Green Matte
Purple
Red
White
Yellow
Other
```
- Support specifying silkscreen color as one of:
```
Black
Blue
Red
White
Yellow
Other
```
- Move silkscreen layer selection from fabrication settings to board setup, i.e. making them a property of the board instead of an export configuration.
This allows us to make the upcoming 3D board viewer taking these properties into account for rendering, to get the same colors as the ordered PCB will have. In addition, in future we might be able to include these properties in the exported production data to avoid manual specification of these values (e.g. our fab service …
=> Extend board setup with more PCB properties

libs/librepcb/core/project/board/boardgerberexport.cpp, libs/librepcb/core/project/board/boardgerberexport.h
For example when generating Gerber files with solder paste (stencil) enabled first, and then with solder paste disabled, the old files are left over in the output directory and thus might be sent to the manufacturer by accident.
Thus any non-generated file is now explicitly deleted if it exists. It's not perfect since it only works if the output file names have not changed, but at least it's much safer than before.
Some day #1000 might improve this situation further.
=> Gerber export: Delete files left over from previous run

libs/librepcb/core/project/board/items/bi_device.cpp, libs/librepcb/core/project/projectloader.cpp, libs/librepcb/core/serialization/fileformatmigrationunstable.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.cpp, libs/librepcb/editor/project/boardeditor/boardclipboarddata.h, libs/librepcb/editor/project/boardeditor/deviceinstancepropertiesdialog.ui
For consistent terminology with the "Flip" action (Ctrl+F) in the board editor, rename the property "mirror" of devices to "flip". This is more intuitive because flip is not the same as mirror (in contrast to schematics, where mirror is indeed just a graphical operation).
However, in the source code it's still called "mirror" for compatibility with the `Transform` template constructor.
=> Rename board device property "mirror" to "flip"

libs/librepcb/core/types/circuitidentifier.h, tests/unittests/core/types/circuitidentifiertest.cpp
Allow the characters `.`, `&`, `(` and `)` in symbol pin names, package pad names, component signal names, net names and component names (designators). They should not cause any issues within production output files (IPC-D356, Gerber, ...).
There might be more characters useful in some cases, e.g. `:`, `;`, `*`, `%`, `~`, `[` and `]` which are still rejected because some of them could cause problems in production data and others I want to keep reserved for future extensions (e.g. `[]` might be useful for buses, and `~` for overline).
Closes #1074
Closes #642
=> Allow characters .&() in identifiers

libs/librepcb/core/project/board/board.cpp, libs/librepcb/core/project/board/boardplanefragmentsbuilder.cpp, libs/librepcb/core/project/board/boardplanefragmentsbuilder.h, libs/librepcb/core/project/board/items/bi_plane.cpp, libs/librepcb/core/project/board/items/bi_plane.h, libs/librepcb/core/project/projectloader.cpp, libs/librepcb/core/serialization/fileformatmigrationunstable.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.cpp, libs/librepcb/editor/project/boardeditor/boardclipboarddata.h, libs/librepcb/editor/project/boardeditor/boardclipboarddatabuilder.cpp, libs/librepcb/editor/project/boardeditor/boardplanepropertiesdialog.cpp, libs/librepcb/editor/project/boardeditor/boardplanepropertiesdialog.ui, libs/librepcb/editor/project/cmd/cmdboardplaneedit.cpp, libs/librepcb/editor/project/cmd/cmdboardplaneedit.h, libs/librepcb/editor/project/cmd/cmdpasteboarditems.cpp
I think the term "island" is more intuitive than "orphan" (unconnected plane areas), thus renaming it in the file format and in the UI.
=> Terminology: Rename plane "orphans" to "islands"

libs/librepcb/core/geometry/via.cpp, libs/librepcb/core/geometry/via.h, libs/librepcb/core/project/board/items/bi_via.cpp, libs/librepcb/core/project/board/items/bi_via.h, libs/librepcb/core/serialization/fileformatmigrationunstable.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.cpp, libs/librepcb/editor/project/boardeditor/boardviapropertiesdialog.cpp, libs/librepcb/editor/project/boardeditor/boardviapropertiesdialog.ui, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_addvia.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawtrace.cpp, libs/librepcb/editor/project/cmd/cmdboardviaedit.cpp, libs/librepcb/editor/project/cmd/cmdboardviaedit.h, libs/librepcb/editor/project/cmd/cmdpasteboarditems.cpp, tests/unittests/core/geometry/viatest.cpp, tests/unittests/editor/project/boardeditor/boardclipboarddatatest.cpp
So far, all vias with a drill up to a certain diameter (as specified in design rules) were fully tented with solder resist, and vias with a larger drill were fully exposed (with automatic stop mask clearance). However, in some cases it's useful to manually expose smaller vias (to use them as test pads) or to use a smaller stop mask clearance for a more compact layout.
Thus the via tenting behavior is now changed this way:
- The automatic tenting/exposing of vias depending on their drill diameter still applies, but it exposes only the drill instead of the full via. So the hole in the stop mask is now the drill diameter plus clearance, not via diameter plus clearance. This reduces the amount of exposed copper and thus also the risk of short circuits e.g. due to unintended solder bridges.
- …
=> Make exposure of vias configurable

libs/librepcb/core/project/board/boardgerberexport.cpp, libs/librepcb/core/project/board/boardplanefragmentsbuilder.cpp, libs/librepcb/core/project/board/boardplanefragmentsbuilder.h, libs/librepcb/core/project/board/drc/boardclipperpathgenerator.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheck.cpp, libs/librepcb/core/project/board/items/bi_plane.cpp, libs/librepcb/core/project/board/items/bi_plane.h, libs/librepcb/core/project/projectloader.cpp, libs/librepcb/editor/project/boardeditor/boardclipboarddata.h, libs/librepcb/editor/project/boardeditor/boardclipboarddatabuilder.cpp, libs/librepcb/editor/project/boardeditor/boardplanepropertiesdialog.cpp, libs/librepcb/editor/project/boardeditor/boardplanepropertiesdialog.ui, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_addvia.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawplane.cpp, libs/librepcb/editor/project/boardeditor/graphicsitems/bgi_plane.cpp, libs/librepcb/editor/project/cmd/cmdboardplaneedit.cpp, libs/librepcb/editor/project/cmd/cmdboardplaneedit.h, libs/librepcb/editor/project/cmd/cmdcombinenetsignals.cpp, libs/librepcb/editor/project/cmd/cmdpasteboarditems.cpp
So far, it was mandatory to specify an existing net for each plane. But I think there are cases where one wants to keep as much copper on the PCB as possible, even without connecting those copper areas to any net. And since that's only a small change in the implementation, let's allow creating planes not connected to a net.
=> Support creating planes without a net

libs/librepcb/core/CMakeLists.txt, libs/librepcb/core/export/graphicspainter.cpp, libs/librepcb/core/export/graphicspainter.h, libs/librepcb/core/library/pkg/footprintpainter.cpp, libs/librepcb/core/library/sym/symbolpainter.cpp, libs/librepcb/core/project/board/boardpainter.cpp, libs/librepcb/core/project/schematic/schematicpainter.cpp, libs/librepcb/core/utils/overlinemarkupparser.cpp, libs/librepcb/core/utils/overlinemarkupparser.h, libs/librepcb/editor/graphics/primitivefootprintpadgraphicsitem.cpp, libs/librepcb/editor/graphics/primitivetextgraphicsitem.cpp, libs/librepcb/editor/graphics/primitivetextgraphicsitem.h, libs/librepcb/editor/library/sym/symbolpingraphicsitem.cpp, libs/librepcb/editor/project/schematiceditor/graphicsitems/sgi_netlabel.cpp, libs/librepcb/editor/project/schematiceditor/graphicsitems/sgi_netlabel.h, libs/librepcb/editor/project/schematiceditor/graphicsitems/sgi_symbolpin.cpp, libs/librepcb/editor/widgets/graphicsview.cpp, tests/unittests/CMakeLists.txt, tests/unittests/core/utils/overlinemarkupparsertest.cpp
Support rendering overlines by adding `!` to pin-, pad-, or net names. The exact rules as described in https://github.com/LibrePCB/LibrePCB/issues/660#issuecomment-1590891734:
1. A single `!` toggles the overline on/off, depending on its previous state (initial state is off).
2. The character `/` implicitly switches off the overline before rendering. This can be prevented by prefixing it with `!`.
3. A double `!!` has no effect on overlines, they are rendered as a single `!`. In case of an odd number of `!` (e.g. `!!!`), the **last** one toggles overline on/off.
4. Any trailing `!` have no effect, they are rendered as-is (bypassing rules 1 and 3).
Examples:
| Input | Rendering |
|---|---|
| `!RESET/SHDN` | `R̅E̅S̅E̅T̅/SHDN` |
| `RESET/!SHDN` | `RESET/S̅H̅D̅N̅` |
| `!D+` | `D̅+̅ ` |
| …
=> Render '!' in pin-, pad- and net names as overlines

libs/librepcb/editor/widgets/graphicsview.cpp, libs/librepcb/editor/widgets/graphicsview.h, libs/librepcb/editor/widgets/openglview.cpp
In addition to the middle mouse button, panning now also works with the right mouse button. This is especially useful on notebooks which don't have a dedicated middle mouse button. Also it should not have any negative impact (context menu still works if the cursor was more-or-less steady while pressing the right mouse button).
=> Support panning with right mouse button in all editors

libs/librepcb/core/library/cmp/componentcheck.cpp, libs/librepcb/core/library/cmp/componentcheck.h, libs/librepcb/core/library/cmp/componentcheckmessages.cpp, libs/librepcb/core/library/cmp/componentcheckmessages.h, libs/librepcb/core/library/sym/symbolcheck.cpp, libs/librepcb/core/library/sym/symbolcheck.h, libs/librepcb/core/library/sym/symbolcheckmessages.cpp, libs/librepcb/core/library/sym/symbolcheckmessages.h, libs/librepcb/core/serialization/fileformatmigrationunstable.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.h, libs/librepcb/editor/library/cmp/componenteditorwidget.cpp, libs/librepcb/editor/library/sym/symboleditorwidget.cpp
Addendum to #1172: For convenience, the widely used inversion character `/` at the beginning of pin names and component signal names is automatically converted to `!` to make it appearing as an overline. So this migration in libraries does not need to be applied by hand.
However, net names in projects are not automatically migrated since I don't like to make possibly unintended changes in existing projects. It's no harm to stay with `/` so it's probably the safer option.
EDIT: In addition, also added library checks to show a hint if non-functional inversion signs are used.
=> Automatically migrate obsolete inversion sign '/' to '!'

libs/librepcb/core/CMakeLists.txt, libs/librepcb/core/library/libraryelement.h, libs/librepcb/core/library/resource.cpp, libs/librepcb/core/library/resource.h
As suggested in #706, it would be useful to have links to datasheets etc. available right in the schematic editor (e.g. in the context menu of symbols). One option might be to "abuse" the attributes system (e.g. by adding a `DATASHEET` attribute). However, I think it makes sense to implement this as a dedicated feature - especially because many ICs require links to several documents, not just a single datasheet.
This PR does not yet implement this feature, but extends the file format to allow implementing it in a later minor release. I called the documents "resources", but I'm open for suggestions of another naming. In the file format they look like this:
```scheme
(resource "Datasheet" (mediatype "application/pdf")
(url "https://example.com/datasheet.pdf")
)
```
The `mediatype` key is …
=> Prepare file format for adding resources to library elements

libs/librepcb/core/project/board/boardgerberexport.cpp, libs/librepcb/core/project/board/boardgerberexport.h
As kindly reported by Ucamco, zero-width outlines of filled polygons are currently exported to Gerber files even though Gerber states that zero-width apertures shall not be used. This PR omits such outlines in the Gerber output as they have no purpose anyway if the polygon is filled.
=> Gerber export: Omit zero-width outlines of filled polygons

libs/librepcb/editor/library/cmp/componentsymbolvariantlistwidget.cpp, libs/librepcb/editor/library/cmp/componentsymbolvariantlistwidget.h, libs/librepcb/editor/widgets/editabletablewidget.cpp, libs/librepcb/editor/widgets/editabletablewidget.h
In most table widgets, the keyboard shortcut *Enter* now adds a new row (as requested in #848) and *Delete* now removes the selected row. However, *Enter* often needs to be pressed twice because while a cell is in edit mode, the first *Enter* exits the edit mode (so you could move the focus to another table cell then).
Usability is much better now especially because *Enter* first adds a new row instead of (accidentally) closing a modal dialog.
Closes #848.
=> Support enter/delete shortcuts in table widgets

libs/librepcb/core/project/erc/electricalrulecheck.cpp, libs/librepcb/core/project/erc/electricalrulecheck.h, libs/librepcb/core/project/erc/electricalrulecheckmessages.cpp, libs/librepcb/core/project/erc/electricalrulecheckmessages.h, libs/librepcb/core/project/schematic/items/si_netline.h, libs/librepcb/core/project/schematic/items/si_netpoint.h, libs/librepcb/core/project/schematic/items/si_symbolpin.h
As requested in #1054, this adds an ERC check for open wires in the schematic, i.e. wires with an unconnected end and no net label:
Note that this warning is suppressed if the "Less than two pins in net" warning is raised on the same net segment because these two warnings are very similar and thus annoying to get both of them in many cases. The new warning is only raised if the wire *does* connect multiple pins and has no net label attached.
Fixes #1054
=> ERC: Warn about schematic wires with open end

libs/librepcb/editor/workspace/initializeworkspacewizard/initializeworkspacewizard.cpp, libs/librepcb/editor/workspace/initializeworkspacewizard/initializeworkspacewizard_upgrade.cpp
Adding a button to allow choosing a different workspace if an upgrade is required on the default workspace:
Fixes #1044
=> Workpace upgrade wizard: Allow switching workspace

libs/librepcb/core/fileio/fileutils.cpp, libs/librepcb/core/fileio/fileutils.h, libs/librepcb/core/fileio/transactionalfilesystem.cpp, libs/librepcb/core/fileio/transactionalfilesystem.h, libs/librepcb/core/library/cat/componentcategory.cpp, libs/librepcb/core/library/cat/componentcategory.h, libs/librepcb/core/library/cat/packagecategory.cpp, libs/librepcb/core/library/cat/packagecategory.h, libs/librepcb/core/library/cmp/component.cpp, libs/librepcb/core/library/cmp/component.h, libs/librepcb/core/library/dev/device.cpp, libs/librepcb/core/library/dev/device.h, libs/librepcb/core/library/library.cpp, libs/librepcb/core/library/library.h, libs/librepcb/core/library/pkg/package.cpp, libs/librepcb/core/library/pkg/package.h, libs/librepcb/core/library/sym/symbol.cpp, libs/librepcb/core/library/sym/symbol.h, libs/librepcb/core/project/projectloader.cpp, libs/librepcb/core/workspace/workspacelibraryscanner.cpp, libs/librepcb/core/workspace/workspacelibraryscanner.h, libs/librepcb/editor/workspace/initializeworkspacewizard/initializeworkspacewizard_upgrade.ui, tests/unittests/core/fileio/transactionalfilesystemtest.cpp
So far, libraries and their contained elements were not upgraded to the latest file format unless the user opened and saved them manually. Basically this works fine, but for long term it means there are lots of outdated files in the workspace which requires us to keep backwards compatibility forever. In addition , the background scan takes *ages* longer because it temporarily upgrades each element in memory before it can be added to the cache database.
To avoid these two problems, the background library scan now automatically upgrades any outdated library element in the workspace to the latest file format. This takes long on the first scan, but any further scan in massively faster then. In addition, it ensures that all files in the workspace are stored in the latest file format.
=> Upgrade all libraries file format during background scan

CMakeLists.txt, apps/librepcb/main.cpp, ci/azure-jobs-macos.yml, ci/build_linux_portables.sh, ci/build_mac_bundle.sh, ci/build_windows_archive.sh, dev/doxygen/pages/building.md, libs/librepcb/core/build_env.h.in, libs/librepcb/editor/CMakeLists.txt, libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp, libs/librepcb/editor/workspace/controlpanel/controlpanel.h, share/librepcb/qml/testwindow.qml
Due to many limitations of the QtWidgets GUI framework, I think we need to evaluate other options some day - of course QtQuick/QML would be the most obvious choice. I don't know whether we will ever use it or not, but we should at least do some serious evaluation. One of the potential problems might be the deployment and runtime issues since AFAIK it relies on OpenGL which we cannot bundle with LibrePCB. So my idea is to add QtQuick as an *optional* dependency to LibrePCB now to get some experience about it before the dependency may get mandatory some day.
For that, I just added a menu item *Help -> QtQuick Test Window* to the Control Panel which opens this window:
This allows us to easily check if it works properly on various platforms / operating systems and I think the menu item …
=> Add a QtQuick test window

libs/librepcb/core/library/libraryelement.cpp, libs/librepcb/core/library/libraryelement.h, libs/librepcb/core/serialization/fileformatmigrationunstable.cpp, libs/librepcb/core/serialization/fileformatmigrationv01.cpp
Just adding the node `(generated_by "")` to symbol/package/component/device files to allow marking library elements which were generated by a script like `librepcb-parts-generator`. The property is not used yet by LibrePCB, but in future we could show a note in the UI to make it clear when a library element is generated.
I think this helps to avoid modifying or duplicating such elements manually although adjusting the generator makes more sense. A custom UI warning can be made much more visible than the current "Generated by ..." sentence in the description of library elements (which is then no longer needed).
=> Add "generated by" property to library elements

libs/librepcb/editor/utils/shortcutsreferencegenerator.cpp, libs/librepcb/editor/utils/shortcutsreferencegenerator.h, tests/unittests/editor/utils/shortcutsreferencegeneratortest.cpp
Fixes the shortcuts reference PDF layout overflow (see #1120) and now makes the unit test fail if an overflow happens again in future when more shortcuts are added.
Fixes #1120.
=> ShortcutsReferenceGenerator: Fix layout overflow

libs/librepcb/core/library/pkg/package.cpp, libs/librepcb/core/library/pkg/package.h, libs/librepcb/core/workspace/workspacelibrarydb.cpp, libs/librepcb/core/workspace/workspacelibrarydb.h, libs/librepcb/core/workspace/workspacelibrarydbwriter.cpp, libs/librepcb/core/workspace/workspacelibrarydbwriter.h, libs/librepcb/core/workspace/workspacelibraryscanner.cpp
The naming of packages already lead to several discussions (IPC naming vs. JEDEC/EIAJ vs. manufacturer names) and is probably confusing users since the IPC names are not (yet) as well known as names like "SOT-23". So far, our only solution is to add these well known names to the package description (for clarity) and keywords (for the search function).
However, maybe it makes sense to explicitly specify these alternative names in packages, so that the UI can somehow make them more visible than just a description. We might consider listing packages multiple times in list views, once for each name so the user will find it for sure, no matter which name he looks for. Or maybe just show the alternative names within the list views next to the main (IPC) names.
I didn't implement anything in the …
=> Add alternative names to packages file format

dist/installer/packages/librepcb.registerfileextensions/meta/installscript.qs, libs/librepcb/editor/project/boardeditor/boardeditor.cpp, libs/librepcb/editor/project/schematiceditor/schematiceditor.cpp, libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp, libs/librepcb/editor/workspace/controlpanel/fileiconprovider.cpp, share/icons/hicolor/scalable/mimetypes/org.librepcb.LibrePCB-archive.svg, share/mime/packages/org.librepcb.LibrePCB.xml, tests/funq/commandline/test_open_project.py
So far, the GUI only allowed to open *.lpp project files, but not zipped *.lppz projects. But since *.lppz projects can now very easily be generated for every PCB version with the output files generator, users may start creating *.lppz project snapshots to allow opening previous PCB versions without checking out a different Git tag or so.
But so far, *.lppz projects could only be opened with the CLI, not with the GUI. This PR changes that. *.lppz projects are now opened read-only and the *.lppz file extension is registered to the desktop environment the same way as *.lpp projects.
=> Support opening *.lppz projects with the editor

libs/librepcb/core/library/cmp/componentcheckmessages.cpp, libs/librepcb/eagleimport/eaglelibraryimport.cpp, libs/librepcb/editor/library/cmp/componenteditorwidget.cpp
The attribute `PARTNUMBER` has been renamed to `MPN` in v1.0, but the library editor still recommended it as the default component value. Replacing it by `MPN` now.
=> Fix using legacy 'PARTNUMBER' attribute as default value

libs/librepcb/core/library/library.cpp, libs/librepcb/core/workspace/workspacelibraryscanner.cpp
So far, the background library scanner emitted warnings to `stderr` for each directory within workspace libraries not containing a valid library element. This is useful to locate issues if a library element does not appear in the library editor for some reason.
However, especially when working with Git it happens often that empty directories are left over, leading to such warnings although there's nothing bad going on. Thus now only emitting these warnings on **non-empty** directories which do not contain valid library elements.
An alternative would be to automatically delete empty directories (tidying up the workspace), but this might be a little bit dangerous (e.g. causing race conditions with another operation just creating a new directory in a different thread or outside of LibrePCB) …
=> WorkspaceLibraryScanner: Do not warn about empty directories

libs/librepcb/editor/library/cmp/componenteditorwidget.ui, libs/librepcb/editor/library/pkg/packageeditorwidget.ui, libs/librepcb/editor/library/sym/symboleditorwidget.ui
On some systems the yellow warning banner in the library editor was too large, caused by a wrong layout stretch factor.
=> Library editor: Fix possible layout issue of banner

libs/librepcb/editor/library/pkg/footprintclipboarddata.cpp, libs/librepcb/editor/library/sym/symbolclipboarddata.cpp, libs/librepcb/editor/project/boardeditor/boardclipboarddata.cpp, libs/librepcb/editor/project/schematiceditor/schematicclipboarddata.cpp
At least on one system the clipboard didn't work if no text was set, so let's also copy the `SExpression` as `text/plain` (beside the binary data) into the clipboard as a workaround. Might even be just a temporary bug in the clipboard manager of my system but it's hard to find the root cause and being able to paste the `SExpression` into a text editor might be useful anyway, e.g. for debugging purposes.
=> Fix possibly broken copy&paste in editors on some systems

ci/build_mac_bundle.sh
It seems on Apple Silicon all binaries need to be signed, otherwise they won't run. Thus adjusted the bundle build script to create somehow signed binaries. Although that's not yet needed on CI (since we don't have an arm64 runner), it allows to run the script locally on Apple Silicon.
=> CI: Make build_mac_bundle.sh working on Apple Silicon

libs/librepcb/editor/widgets/openglview.cpp
Manually adding some OpenGL defines not available on some targets. I doubt this is the right way to fix it, but I didn't find a better solution yet...
Fixes #1205
=> OpenGlView: Fix compile error on missing OpenGL defines

libs/librepcb/editor/library/dev/partlistmodel.cpp, libs/librepcb/editor/project/componentassemblyoptionlisteditorwidget.cpp
Because @dbrgn was scared by the strong red color :grin:
=> Use lighter red/yellow background colors in parts table

libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp, libs/librepcb/editor/workspace/controlpanel/controlpanel.h
LibrePCB tries to open all project files passed as arguments to the process. Arguments with an extension other than `.lpp` or `.lppz` are ignored and a warning is printed on `stderr` (useful for debugging issues if opening projects does not work).
However, `argv[0]` usually (but not absolutely always) contains the path to the application executable, causing such a warning to be printed every time which is a bit ugly. Thus now suppressing the warning on `argv[0]`, but still printing it on any additional argument.
=> Suppress warning on stderr caused by argv[0]

libs/librepcb/editor/library/cmp/componentchooserdialog.cpp, libs/librepcb/editor/library/lib/libraryoverviewwidget.cpp, libs/librepcb/editor/library/pkg/packagechooserdialog.cpp, libs/librepcb/editor/library/sym/symbolchooserdialog.cpp, libs/librepcb/editor/project/addcomponentdialog.cpp, libs/librepcb/editor/project/addcomponentdialog.h
In most list views, draw deprecated library elements with red color. Otherwise the user has no chance to know these library elements should no longer be used. By far not perfect yet, but still much better than nothing...
=> Show deprecated library elements with red color

apps/librepcb-cli/commandlineinterface.cpp, apps/librepcb-cli/commandlineinterface.h, libs/librepcb/core/3d/occmodel.cpp, libs/librepcb/core/3d/occmodel.h, tests/cli/conftest.py, tests/cli/open_step/test_minify.py, tests/cli/open_step/test_open.py, tests/cli/open_step/test_parser.py, tests/cli/open_step/test_tesselate.py, tests/cli/test_help.py
Add a new CLI command to minify and validate individual STEP files without requiring to open a whole LibrePCB library. This is intended mainly for `librepcb-parts-generator` to post-process generated STEP files.
```
Usage: ./librepcb-cli [options] open-step [command_options] file
LibrePCB Command Line Interface
Options:
-h, --help        Print this message.
-V, --version     Displays version information.
-v, --verbose     Verbose output.
--minify          Minify the STEP model before validating it. Use in
conjunction with '--save-to' to save the output of the
operation.
--tesselate       Tesselate the loaded STEP model to check if LibrePCB is
able to render it. Reports failure (exit code = 1) if no
content is detected.
--save-to <file>  Write the (modified) STEP file to this output …
```
=> CLI: Implement new command 'open-step'

libs/librepcb/core/3d/occmodel.cpp, tests/cli/open_step/test_tesselate.py
Fixes possibly missing colors and/or wrong location of shapes loaded from STEP files in the 3D viewer, mainly observed on STEP models which consist of multiple shapes which are not fused.
=> 3D view: Fix location and color of some STEP solids

libs/librepcb/editor/project/boardeditor/boardgraphicsscene.cpp, libs/librepcb/editor/project/boardeditor/graphicsitems/bgi_footprintpad.cpp, libs/librepcb/editor/project/boardeditor/graphicsitems/bgi_footprintpad.h
Pads of the same net were not highlighted while drawing traces in the board editor.
=> Board editor: Fix highlighting pads while drawing traces

libs/librepcb/core/3d/occmodel.cpp, tests/unittests/core/3d/occmodeltest.cpp
STEP files consisting of multiple shapes (not fused) were partially broken after minification (some shapes not rendered, and FreeCAD displaying an unexpected object tree). Fixed by disabling merging of some specific STEP file data entries.
=> Fix possibly broken STEP files after minification

AUTHORS.md, dev/list_tests.py
It took me a while, until I noticed the script is not broken, but rather intended to be executed from the directory above.
`./dev/list_tests.py`
The changes intend to allow usage from within the subdirectory:
```
cd dev
python ./list_test.py
```
and/or
```
cd dev
python list_test.py
```
and/or
```
cd dev
./list_test.py
```
=> Make list_tests.py callable from within subfolder

dev/capture_overview_screenshot.sh, dev/capture_screenshots.sh, dev/diagrams/convert.sh, dev/doxygen/make.sh, dev/format_code.sh, dev/generate_db_schema_diagram.sh, dev/graphics/convert.sh
Hi
According to [Stackoverflow](https://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang#10383546) it looks like the portability of the development scripts could be improved by having this new style for the bash shebang.
What do you think?
If possible, verify the line 58 of "dev/format_code.sh" as I did not test this inside docker yet. :(
=> Use bash from env for better portability

dev/capture_overview_screenshot.sh, dev/capture_screenshots.sh, dev/diagrams/convert.sh, dev/graphics/convert.sh
According [Stackoverflow](https://stackoverflow.com/questions/9449778/what-is-the-benefit-of-using-instead-of-backticks-in-shell-scripts) the backticks are legacy, so I think it would be stylish to have this new syntax.
=> Change backticks to POSIX style

libs/librepcb/core/fileio/fileutils.cpp
This PR fixes bug found in #1234 during creating tests in #121
=> Fix FileUtils::getFilesInDirectory() reveal nested hidden files

libs/librepcb/core/types/point.h, tests/unittests/core/types/pointtest.cpp
The Testsuite for #1204 revealed maximum value of Point +/- 2m without losing precision
When the qt function `qSqrt` get out and using `std::hypot` instead, The point can be 1e15nm (100km) large in size without loss of precision and any overflow (test on that succeeded)
Amazing that there is no `qHypot` function on my PC (compiler says undefined external, but I can see it in header of some version of Qt found on internet). Standard c++ function `std::hypot` exists so I used that.
by the way, is there reason to stick on c++11 standard in this app ?
=> Use std::hypot() for Point::getLength() calculation

libs/librepcb/core/fileio/fileutils.cpp
This is the fix for issue #1236 
In original scenario, the output list has been filtered for directory names same way as for files.
This is the correction that filter is applied only on files, not on directories.
=> Stop FileUtils::getFilesInDirectory() filtering folders by name

libs/librepcb/core/workspace/theme.cpp
The colors of Documentation layer and inner layers has not been visually differentiated.
This PR uses recommended colors by doom-fr in LibrePCB#707 and LibrePCB#608
therefore fully resolves both issues.
Resolves LibrePCB#707 
Resolves LibrePCB#608
=> Visually separate colors in board layers

tests/unittests/CMakeLists.txt, tests/unittests/core/fileio/fileutilstest.cpp
This PR realizes issue #121 
During testing, I found two bugs inside `FileUtils::getFilesInDirectory` functions. 
I created issues #1234 and #1236 for them.
One of them is simple copy-paste mistake inside `FileUtils::getFilesInDirectory` and can be simply corrected in #1234. 
But the second needs deeper examination and testing under different OS or discussion on API used.
=> Add unit test for FileUtils

libs/librepcb/editor/widgets/openglview.cpp, share/librepcb/opengl/3d-fragment-shader.glsl, share/librepcb/opengl/3d-vertex-shader.glsl
Instead of hardcoding OpenGl shader programs as strings, now storing them in files loaded at runtime as this provides some advantages:
- They are much more readable without the C++ syntax
- They are easier to write since some editors provide syntax highlighting and auto-formatting
- Development iterations are shorter because no recompiling is needed after modifying shader programs
=> OpenGlView: Factor out shader programs into files

dev/format_code.sh, share/librepcb/qml/testwindow.qml
In **first commit** of series, the QML formatter is added so programmer could autoformat modified QML files before submitting pull request
In **second commit** of series, there was plenty copy-pasted code inside that script. Adding new formatters and options can introduce new bugs. Proposed refactoring shortened all copied code to two bash function calls.
The `search_files` function searches for all intended files with specified extensions
they should be checked in the concrete linter.
The `update_file` checks, if the file content has been modified by linter tool and if
it's true, updates file and logs about the change on screen
**NOTE:** The `NEW_CONTENT` is transferred to the `update_file` via global variable, but it can be read from stdin until eof so the linter calls can be one-liners …
=> Refactor format_code.sh and add QML formatter

libs/librepcb/core/job/gerberexcellonoutputjob.cpp
The Protel-style suffix for the board outlines layer was "gml" instead of "gm1". Very nasty bug, I hope it doesn't lead to serious issues for users :sob:
=> Fix file extension in Protel-style Gerber output job

libs/librepcb/editor/project/bomgeneratordialog.cpp
The default window size of the BOM export dialog is quite small to also fit on smaller screens. But due to lots of content, probably most users will increase its window size so it's much more convenient if the window size is memorized.
=> BOM export dialog: Save & restore window size

libs/librepcb/editor/project/bomgeneratordialog.cpp, libs/librepcb/editor/project/bomgeneratordialog.ui
Currently the width of most columns in the BOM export dialog was scaled with the window width to avoid a horizontal scrollbar to appear. However, usually this caused cropped text in columns with long texts and unused space in columns with short texts. Thus now changed the behavior to always fit all columns to their content and showing a horizontal scrollbar if not all columns fit into the window. In addition, the columns can now manually be resized when needed (not memorized though since the optimal width depends on the content).
=> BOM export dialog: Don't scale columns with window width

libs/librepcb/editor/workspace/desktopservices.cpp, libs/librepcb/editor/workspace/desktopservices.h
After triggering an external application from within LibrePCB (web browser, PDF viewer, ...), change the cursor to a waiting spinner for a moment to give immediate feedback that the operation has been successfully triggered. This is a much better user experience than silently waiting seconds for the requested application to appear.
=> Show waiting spinner while opening external applications

libs/librepcb/core/library/cmp/componentprefix.h, libs/librepcb/core/types/boundedunsignedratio.cpp, libs/librepcb/eagleimport/CMakeLists.txt, libs/librepcb/eagleimport/eaglelibraryconverter.cpp, libs/librepcb/eagleimport/eaglelibraryconverter.h, libs/librepcb/eagleimport/eaglelibraryimport.cpp, libs/librepcb/eagleimport/eaglelibraryimport.h, libs/librepcb/eagleimport/eagletypeconverter.cpp, libs/librepcb/eagleimport/eagletypeconverter.h, tests/unittests/core/library/cmp/componentprefixtest.cpp, tests/unittests/eagleimport/eagletypeconvertertest.cpp
For #1268, imported EAGLE library elements need to be much more accurate and respecting as many EAGLE properties as possible, otherwise we'll get too many problems in schematics and boards. Thus as a preparation, this PR heavily extends the EAGLE library import and fixes some issues:
- Fix failure in case of invalid component prefix
- Fix gate suffix on single-gate components
- Fix conversion of text inversion syntax
- Set more reasonable component default value
- Detect and mark schematic-only components
- Convert board outlines/cutouts to zero width
- Support many more text element properties
- Support sheet frames in symbols
- Support keepout zones in footprints
- Support more pin & pad properties
The EAGLE parser has been extended accordingly in …
=> Heavily improve EAGLE library import

apps/librepcb/main.cpp, libs/librepcb/core/application.cpp, libs/librepcb/core/application.h, libs/librepcb/core/fileio/filepath.cpp, libs/librepcb/core/network/networkaccessmanager.cpp, libs/librepcb/core/network/networkaccessmanager.h, libs/librepcb/core/network/networkrequestbase.cpp, libs/librepcb/core/network/networkrequestbase.h, libs/librepcb/editor/workspace/librarymanager/onlinelibrarylistwidgetitem.cpp, tests/funq/conftest.py, tests/unittests/core/applicationtest.cpp
Using `QNetworkDiskCache` to support the standard HTTP cache mechanisms, reducing the overall network load of LibrePCB. The cache is set up at the default, platform-specific cache location provided by Qt, with subdirectory "http" (seems to be "/home/user/.ccache/LibrePCB/LibrePCB/http/" on Linux) with Qt's default cache size limit (50MB in total, according docs).
However, since not all accessed URLs are under our control (e.g. the library manager downloads library icons directly from GitHub), the `Cache-Control` response header may or may not be set to sensible values. GitHub uses `max-age=300`, which is way too conservative for uncritical things like library icons. Therefore I implemented the option to enforce a longer caching for particular URLs, which is now set to 1 day for library …
=> Globally enable HTTP caching

libs/librepcb/editor/library/cat/categorylisteditorwidget.ui, libs/librepcb/editor/library/cmp/componenteditorwidget.cpp, libs/librepcb/editor/library/cmp/componenteditorwidget.ui, libs/librepcb/editor/library/cmp/componentsignallisteditorwidget.cpp, libs/librepcb/editor/library/cmp/componentsignallisteditorwidget.h, libs/librepcb/editor/library/cmp/componentsymbolvariantlistwidget.cpp, libs/librepcb/editor/library/cmp/componentsymbolvariantlistwidget.h, libs/librepcb/editor/library/lib/libraryoverviewwidget.ui
Slightly polish the library editor UI to reduce the required minimum window height.
Closes #1056.
=> Library editor: Reduce minimum window height

libs/librepcb/editor/graphics/circlegraphicsitem.cpp, libs/librepcb/editor/graphics/circlegraphicsitem.h, libs/librepcb/editor/graphics/polygongraphicsitem.cpp, libs/librepcb/editor/graphics/polygongraphicsitem.h, libs/librepcb/editor/library/pkg/footprintgraphicsitem.cpp, libs/librepcb/editor/library/sym/symbolgraphicsitem.cpp, libs/librepcb/editor/project/schematiceditor/graphicsitems/sgi_symbol.cpp
Always paint grab area polygons/circles in background and pure outlines (not filled or grab area) in foreground to avoid hiding lines behind filled graphics items.
Fixes #1278.
=> Improve stacking order of graphics items

libs/librepcb/core/library/pkg/packagecheck.cpp, libs/librepcb/core/library/pkg/packagecheck.h, libs/librepcb/core/library/pkg/packagecheckmessages.cpp, libs/librepcb/core/library/pkg/packagecheckmessages.h
I saw the situation where some footprint pads have been assigned to package pad UUIDs which actually didn't exist, but the package editor didn't warn about this situation. Now an error is shown in that case.
=> Package check: Warn about invalid pad connections

libs/librepcb/editor/widgets/openglview.cpp, libs/librepcb/editor/widgets/openglview.h
Heavily improve the behavior of zoom/pan/rotate in the 3D viewers, which is now **way** more intuitive:
- While panning, *exactly* keep the grabbed position below the cursor (no slip anymore).
- Zoom exactly to the point below the cursor (instead of PCB center).
- Implement zoom by modifying camera FOV angle instead of camera Z-position to avoid collision with surfaces at high zoom levels (no longer possible to look into a PCB).
- Allow rotating around Z-axis by pressing Shift.
The original idea of rotating around the point which is in the center of the screen is not implemented unfortunately because I didn't find a working solution - allowing arbitrary rotation centers would break the constant camera Z-position, probably leading to strange/non-deterministic behavior of the view …
=> 3D Viewer: Improve behavior of zoom/pan/rotate

libs/librepcb/editor/project/newprojectwizard/newprojectwizard.cpp, libs/librepcb/editor/project/newprojectwizard/newprojectwizard.h, libs/librepcb/editor/project/newprojectwizard/newprojectwizard.ui, libs/librepcb/editor/project/newprojectwizard/newprojectwizardpage_metadata.cpp, libs/librepcb/editor/project/newprojectwizard/newprojectwizardpage_metadata.h, libs/librepcb/editor/project/newprojectwizard/newprojectwizardpage_metadata.ui, libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp, tests/funq/aliases, tests/funq/controlpanel/test_create_project.py
Support changing the filename and directory name when creating a new project. This also allows to create a project within an already existing, empty directory.
In addition, memorize and restore the window size of the wizard and the entered project file location for convenience.
Fixes #1029
=> "New Project"-wizard: Allow modifying project directory & filename

libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp, libs/librepcb/editor/workspace/controlpanel/controlpanel.h
Support the *delete* keyboard shortcut in the projects tree view of the Control Panel to avoid needing the context menu for this very basic functionality.
=> Control Panel: Support delete shortcut in projects tree

libs/librepcb/core/CMakeLists.txt, libs/librepcb/core/job/graphicsoutputjob.h, libs/librepcb/core/project/board/realisticboardpainter.cpp, libs/librepcb/core/project/board/realisticboardpainter.h, libs/librepcb/core/project/outputjobrunner.cpp
The graphics export (PDF/PNG/...) so far only supported to render boards the same way as on screen. This PR adds the option to render boards in a realistic mode, with proper clipping of objects to the board area etc. We'll need this feature on the LibrePCB Fab website to generate the preview pictures since our current solution of using a 3rd-party Python library has some problems.
Example output of this new feature:
I didn't add this option to the GUI yet because the data structure needs to be changed a bit for file format v2 anyway, which can be done together then. If someone still wants to use it already, just add these S-Expression nodes to the desired output job in `project/jobs.lp`:
```scheme
(content (type board) (title "Rendering Top")
(paper auto) (orientation auto) (rotate false) …
```
=> Graphics output job: Add support for realistic PCB rendering

libs/librepcb/core/project/schematic/items/si_symbolpin.cpp
Hide pin numbers which are identical to the pin names shown on the schematic. This avoids cluttering the schematic with redundant information, mainly for components like connectors where pin names and pad names are just numbers (1, 2, 3, ...). In such cases, hiding pin numbers also reduces the risk of overlaps in case of non-standard pin lengths (also often the case for connectors).
=> Schematic editor: Hide redundant pin numbers

libs/librepcb/editor/project/boardeditor/boardeditor.cpp, libs/librepcb/editor/project/schematiceditor/schematiceditor.cpp
When searching a device in the schematic- or board editor and using the "go to device" auto-zoom, limit the margin around the device to 10mm to avoid zooming out too much for large devices.
Fixes #849
=> Limit search result auto-zoom to a certain margin

libs/librepcb/core/serialization/serializableobjectlist.h, libs/librepcb/editor/library/dev/deviceeditorwidget.cpp, libs/librepcb/editor/library/dev/padsignalmapeditorwidget.cpp, libs/librepcb/editor/library/dev/padsignalmapeditorwidget.h, libs/librepcb/editor/modelview/comboboxdelegate.cpp, tests/unittests/core/serialization/serializableobjectlisttest.cpp
Adding some tools to the device editor to assign pads to signals in much more efficient ways:
- **Auto-connection tool** to assign pads to signals by matching names. Only exact matches (but case-insensitive) are taken into account, no magic going on at all.
- **Interactive tool** to connect any remaining (i.e. unconnected) pad one by one, by providing a list of signals which is sorted in a sophisticated way (numerically, best matches at top, already connected signals at bottom). In addition, the list can be filtered by typing. The interactive mode can be used either 100% by keyboard navigation, 100% mouse navigation (double-click) or a mix of both. Actually it is almost fun to define the pinout with this tool :smiley: 
- **CSV import** to assign many pads to signals in some programmatic …
=> Device editor: Add tools to help defining the pinout

libs/librepcb/eagleimport/eaglelibraryconverter.cpp, libs/librepcb/eagleimport/eaglelibraryconverter.h, libs/librepcb/eagleimport/eaglelibraryimport.cpp, libs/librepcb/eagleimport/eagleprojectimport.cpp
Fixes importing EAGLE projects which contain multiple libraries with the same name, but different URNs. Reported in https://www.mikrocontroller.net/topic/565050#7614223.
=> EAGLE Import: Fix ignoring library URNs

CMakeLists.txt, cmake/FindDxflib.cmake, cmake/FindMuParser.cmake
- Remove global `-Wno-deprecated-declarations` compile flag which was used for Qt 5.15 and thus completely disabled deprecation warnings on our macOS and Windows CI jobs.
- Completely disable Qt features which were already marked as deprecated in the oldest Qt version we support, so we're enforced to get rid of very legacy Qt features.
- Suppress any Qt deprecations added in more recent version since they are not useful for us (backward compatibility is more important than forward compatibility).
- Suppress any deprecation warnings in 3rd-party libraries since they are not under our control.
=> CMake: Improve suppression of deprecation warnings

libs/librepcb/core/3d/occmodel.cpp, libs/librepcb/core/export/excellongenerator.cpp, libs/librepcb/core/export/gerbergenerator.cpp, libs/librepcb/core/geometry/path.cpp, libs/librepcb/core/project/board/boardgerberexport.cpp, libs/librepcb/core/types/angle.h, libs/librepcb/core/types/length.cpp, libs/librepcb/core/types/length.h, libs/librepcb/core/types/point.cpp, libs/librepcb/core/utils/toolbox.cpp, libs/librepcb/core/utils/toolbox.h, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_drawpolygonbase.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_drawzone.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_drawpolygonbase.cpp, libs/librepcb/editor/utils/measuretool.cpp, libs/librepcb/editor/widgets/graphicsview.cpp, tests/unittests/core/geometry/pathtest.cpp, tests/unittests/core/types/lengthtest.cpp, tests/unittests/core/utils/toolboxtest.cpp
Initially started this change because I observed small differences of the result of some calculations (e.g. arc center) between Qt5 and Qt6, which made some unit tests fail. During investigation, I decided to slightly rewrite some of the mathematical calculations, so I split it into this separate PR:
- Toolbox: Make arc calculations more robust by returning `tl::optional` in case of invalid results (e.g. division by zero on arcs with a center way too far away). For example the Gerber generator will now export a straight line segment instead of an invalid arc segment.
- Replace Qt math functions by C++ std functions whenever possible (no reason to use Qt functions anymore if they are available in C++11).
- Replace `qRound()` and `qRound64()` with own implementation because it returns …
=> Slightly improve robustness of some math functions

cmake/FindOpenCascade.cmake
Verified locally on Linux that with this change LibrePCB builds & links successfully with OCCT 7.8.0. Later this will be verified on CI (including Windows) as well when newer Docker images are available (https://github.com/LibrePCB/docker-librepcb-dev/pull/43).
Fixes #1315
=> CMake: Fix linking with OCCT 7.8.x

libs/librepcb/editor/library/libraryeditor.cpp, libs/librepcb/editor/project/boardeditor/boardeditor.cpp
I think for new users it's not so clear how to open the 3D mode (or that it even exists!) because the thin vertical buttons can easily be overlooked. Thus now also adding a toggle button to the toolbar, next to the zoom buttons (library editor & board editor).
=> Add "toggle 2D/3D" button to toolbars

libs/librepcb/editor/editorcommandset.h, libs/librepcb/editor/project/addcomponentdialog.cpp, libs/librepcb/editor/project/addcomponentdialog.h
Adding a context menu to parts in the "Add Component"-dialog:
The last two menu entries (and a third one "Open Product Website") open the web browser and are only shown if the corresponding URL is available (retrieved through the part information API).
Copying the MPN is also possible directly with Ctrl+C, i.e. without opening the context menu.
Closes #1330
=> Add component dialog: Add context menu to parts

libs/librepcb/editor/editorcommandset.h, libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp, libs/librepcb/editor/workspace/controlpanel/controlpanel.h, libs/librepcb/editor/workspace/initializeworkspacewizard/initializeworkspacewizard_choosesettings.ui, libs/librepcb/editor/workspace/initializeworkspacewizard/initializeworkspacewizardcontext.cpp, libs/librepcb/editor/workspace/initializeworkspacewizard/initializeworkspacewizardcontext.h
So far, new workspaces didn't contain any projects after their initial creation so the Control Panel project tree was completely empty. However, as suggested in #1267 it would be useful to have some example projects available to help new users evaluating LibrePCB. Thus this PR implements this feature in two ways:
The initial idea was actually to provide a way to open example projects, for example through a menu item *File -> Open -> Example Project*. However, the question was where they will be opened from and if they are read-only or writable. Also the menu option might not be visible and convenient enough for new users to make them actually using this feature.
Now I decided to go with a different approach. When creating a new workspace, just automatically add some example projects in a …
=> Initialize new workspace with some example projects

libs/librepcb/core/3d/occmodel.cpp, tests/cli/open_step/test_minify.py, tests/unittests/core/3d/occmodeltest.cpp
Seems that too many STEP nodes were merged, thus now blacklisting all nodes containing the term "REPRESENTATION". Slightly increases the size of the resulting STEP models, but I think there's no way to avoid that...
Also added a unit test to avoid regression.
Fixes #1286
=> Fix possibly wrong colors after STEP minification

libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate.h
Currently it was not possible to add polygons or texts on inner copper layers because these layers didn't show up in the layer dropdown, although this is totally valid. Fixed by adding inner copper layers to the dropdowns.
=> Board editor: Fix missing inner layers in dropdowns

libs/librepcb/core/project/board/drc/boarddesignrulecheck.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheck.h, libs/librepcb/core/project/board/drc/boarddesignrulecheckmessages.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheckmessages.h
Add two new DRC warnings:
- Inner copper layers which are enabled, but contain no copper objects. Especially useful if users think that inner layers act as planes, i.e. are automatically filled with copper which is not the case. Also PCB manufacturers might be confused about empty layers (got a report that PCBWay asked the user which polarity the layer has).
- Inner copper layers which are disabled, but contain copper objects, as this looks like a wrong board setup.
=> DRC: Add checks for unused or disabled layers

libs/librepcb/editor/library/lib/libraryoverviewwidget.cpp, libs/librepcb/editor/library/lib/libraryoverviewwidget.h, libs/librepcb/editor/utils/menubuilder.cpp, libs/librepcb/editor/utils/menubuilder.h
Remove the "Copy to other library" context menu item because it was misleading (users could think this feature allows to create a new library element which will cause serious trouble, see #1321). Now only the "Move to other library" option is available in the context menu, but its confirmation dialog contains a checkbox to keep the elements in the current library (effectively making a copy):
It might still not be a perfect solution but I didn't find a better one and I think this should now be much less "dangerous".
Note that this checkbox will be checked but read-only for remote libraries as their filesystem is read-only.
Closes #1321
=> Library editor: Refactor "copy to other library"

libs/librepcb/editor/project/outputjobsdialog/outputjobsdialog.cpp, libs/librepcb/editor/project/outputjobsdialog/outputjobsdialog.h, libs/librepcb/editor/project/outputjobsdialog/outputjobsdialog.ui
It already happened several times to myself that I close the output jobs dialog with "Cancel" or Escape instead of clicking "OK" to get the changes saved, so the changes were lost. This PR adds a confirmation message box when canceling this dialog while there are unsaved changes.
=> OutputJobsDialog: Ask for discarding changes

libs/librepcb/editor/library/pkg/fsm/packageeditorstate_select.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_select.cpp, libs/librepcb/editor/project/boardeditor/boardeditor.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_select.cpp, libs/librepcb/editor/project/projecteditor.cpp, libs/librepcb/editor/project/projecteditor.h, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_select.cpp, libs/librepcb/editor/project/schematiceditor/schematiceditor.cpp
- Saving a project can take a few seconds while the UI is not responsive. Now showing a waiting cursor during this operation to provide immediate feedback, making the user know when the operation starts and ends. Also print "Project saved!" in the status bar when the operation succeeded.
- Copying something to clipboard did not provide any visual feedback so far, thus now displaying "Copied to clipboard!" in the status bar to let the user know it worked.
=> Provide visual feedback on save & copy actions

libs/librepcb/editor/3d/openglscenebuilder.cpp
Fixes rendering artifacts caused by too small offset between surfaces.
=> 3D viewers: Fix flicker in PCB surface

ci/azure-jobs-macos.yml, ci/build_mac_bundle.sh
Avoid deploying two separate *.app bundles in separate *.dmg images - just include the `librepcb-cli` executable in the normal GUI application bundle.
Closes #1358
=> MacOS: Ship the CLI in the same bundle as the GUI app

ci/build_linux_portables.sh, dist/appimage/AppRun
Determine by `argv[0]` whether the CLI or the GUI shall be executed. This way we don't need to distribute two separate AppImages anymore, which simplifies deployment and even reduces disk usage and network traffic of release artifacts.
Downside is that for the CLI the AppImage either needs to be renamed (add "cli" to its filename) or a symlink (with "cli" in its name) needs to be created. But probably the CLI AppImage isn't used by many people anyway, so I think that's no problem at all (and of course will be documented accordingly in the user manual).
Similar to #1378 which was for macOS.
=> Linux: Ship the CLI in the same AppImage as the GUI app

libs/librepcb/core/CMakeLists.txt, libs/librepcb/core/systeminfo.cpp
This Windows API function seems to be handling encoding correctly, in contrast to the previously used "net user" command. For now the old way is still used as fallback in case `NetUserGetInfo()` does not work.
Fixes #1365
=> Windows: Use NetUserGetInfo() to get full user name

libs/librepcb/editor/utils/standardeditorcommandhandler.cpp
Unlike `/tmp`, it seems the cache directory is not sandboxed by Snap and Flatpak so let's save the keyboard shortcuts reference PDF there to allow opening it with an external PDF reader.
Fixes #1361.
=> Change keyboard shortcuts PDF location to cache directory

share/metainfo/org.librepcb.LibrePCB.metainfo.xml
Saw on Flathub that the "or later" is missing :see_no_evil:
=> Fix license identifier in AppStream Metainfo XML

CMakeLists.txt, README.md, apps/librepcb/main.cpp, dev/doxygen/pages/code_style_guide.md, libs/librepcb/core/geometry/path.cpp, libs/librepcb/core/network/orderpcbapirequest.cpp, libs/librepcb/core/serialization/serializableobjectlist.h, libs/librepcb/editor/editorcommand.cpp, libs/librepcb/editor/library/dev/padsignalmapeditorwidget.cpp, libs/librepcb/editor/project/schematiceditor/schematiceditor.cpp, libs/librepcb/editor/utils/editortoolbox.cpp, libs/librepcb/editor/workspace/workspacesettingsdialog.cpp, tests/unittests/editor/dialogs/graphicsexportdialogtest.cpp, tests/unittests/testhelpers.h
These old versions are not needed anymore and weren't tested on CI anyway so it's easy to get rid of them...
Qt5.12 and CMake 3.16 are the versions of the still supported Ubuntu 20.04 and are also still used on CI.
=> Drop support for Qt < 5.12 and CMake < 3.16

libs/librepcb/editor/project/boardeditor/boardpickplacegeneratordialog.cpp, libs/librepcb/editor/project/bomgeneratordialog.cpp
Rows of do-not-mount components were not readable well with dark theme, which is fixed by using the theme-dependent colors from QPalette.
=> Fix colors of BOM/PnP table rows with dark theme

apps/librepcb/main.cpp, libs/librepcb/core/network/networkaccessmanager.cpp, libs/librepcb/core/workspace/workspacelibraryscanner.cpp
In some experiments with QtQuick I observed significant lags in the GUI when the background library scanner was running, which seem to be fixed by giving the main thread (GUI) a higher priority than the library scanner. Though not sure if relevant with QtWidgets (not using QtQuick for now) and some systems might not support thread priorities, I think it makes sense anyway to assign thread priorities. Thus now also assigned the network thread a lower priority than the main thread.
=> Give GUI higher thread priority than background tasks

libs/librepcb/editor/graphics/circlegraphicsitem.h, libs/librepcb/editor/graphics/holegraphicsitem.h, libs/librepcb/editor/graphics/polygongraphicsitem.h, libs/librepcb/editor/graphics/stroketextgraphicsitem.h, libs/librepcb/editor/graphics/textgraphicsitem.h, libs/librepcb/editor/graphics/zonegraphicsitem.h, libs/librepcb/editor/library/cmd/cmddragselectedfootprintitems.cpp, libs/librepcb/editor/library/cmd/cmddragselectedsymbolitems.cpp, libs/librepcb/editor/library/cmd/cmdremoveselectedfootprintitems.cpp, libs/librepcb/editor/library/cmd/cmdremoveselectedsymbolitems.cpp, libs/librepcb/editor/library/pkg/footprintgraphicsitem.cpp, libs/librepcb/editor/library/pkg/footprintpadgraphicsitem.h, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_select.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_select.h, libs/librepcb/editor/library/sym/fsm/symboleditorstate_select.cpp, libs/librepcb/editor/library/sym/symbolgraphicsitem.cpp, libs/librepcb/editor/library/sym/symbolpingraphicsitem.h, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_select.cpp
In the package editor it is a common task to modify pad geometries (e.g. width, height or drill diameter) of already added pads. But for packages with a lot of pads, this is *very* annoying because each pad has to be edited individually. So it would be very helpful to allow modifying many pads at once.
I implemented this as a quite generic feature. After copying a single object of any type (pad, polygon, hole, ...) to the clipboard as usual, the context menu contains a new item "Paste Geometry" which applies only the geometry from the copied object to the selected objects. The usual keyboard shortcuts Ctrl+C and Ctrl+V work as well since Ctrl+V automatically detects whether only the geometry shall be applied or the normal paste operation takes place. With this feature, it is now very …
=> Package editor: Support copying properties to other objects

libs/librepcb/core/library/pkg/packagecheck.cpp, libs/librepcb/core/library/pkg/packagecheck.h, libs/librepcb/core/library/pkg/packagecheckmessages.cpp, libs/librepcb/core/library/pkg/packagecheckmessages.h, libs/librepcb/editor/library/pkg/packageeditorwidget.cpp
Emit warnings in the package editor if any lines (potentionally) drawn on silkscreen have a width less than 0.15mm as this could lead to manufacturing problems.
=> Package check: Warn about thin silkscreen lines

libs/librepcb/editor/library/pkg/packagemodellistmodel.cpp
Many STEP files downloaded from the internet have suffixes `STEP`, `STP` or even `Step` or `Stp`. But the "Select STEP file" dialog in the package editor did only allow selecting files with lowercase suffix `step` and `stp`, at least on some systems. Looks like a bug in Qt (or the desktop environment?) to me as the file suffix capitalization should not be relevant - anyway, it's easy to fix by explicitly accepting the uppercase variants.
=> Package editor: Support uppercase STEP file suffixes

libs/librepcb/editor/project/boardeditor/unplacedcomponentsdock.cpp
It seems a common problem that the message "No device or package for the selected component found in the library! Please add a suitable device and package to your workspace library." in the board editor confuses users, making them opening issues or forum threads explaining there's a problem with the software. So I appended a "See details here." note which points to a FAQ item I just created: https://librepcb.org/faq/#error-no-dev-or-pkg-found
Hope this makes it more clear for users what the message means and what they have to do.
=> Board editor: Link "no device or package found" message to FAQ

.reuse/dep5, img/actions/align_horizontally.svg, img/actions/align_vertically.svg, img/images.qrc, libs/librepcb/editor/CMakeLists.txt, libs/librepcb/editor/cmd/cmdholeedit.cpp, libs/librepcb/editor/cmd/cmdholeedit.h, libs/librepcb/editor/dialogs/movealigndialog.cpp, libs/librepcb/editor/dialogs/movealigndialog.h, libs/librepcb/editor/dialogs/movealigndialog.ui, libs/librepcb/editor/editorcommandset.h, libs/librepcb/editor/library/cmd/cmddragselectedfootprintitems.cpp, libs/librepcb/editor/library/cmd/cmddragselectedfootprintitems.h, libs/librepcb/editor/library/editorwidgetbase.h, libs/librepcb/editor/library/libraryeditor.cpp, libs/librepcb/editor/library/libraryeditor.h, libs/librepcb/editor/library/pkg/fsm/packageeditorfsm.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorfsm.h, libs/librepcb/editor/library/pkg/fsm/packageeditorstate.h, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_select.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_select.h, libs/librepcb/editor/library/pkg/packageeditorwidget.cpp, libs/librepcb/editor/library/pkg/packageeditorwidget.h
Finally a very handy tool to move and/or align objects (especially pads) in the package editor! Features:
- Move multiple objects together by specifying either relative or absolute coordinates for the first object
- Apply constant X and/or Y steps between selected objects
- Automatically center objects horizontally and/or vertically
- Live preview - every change in settings immediately shows how the result will look
- Works with pads, circles, holes and texts (but currently only in the package editor)
- Multiple objects at the exact same position are handled as a single object (e.g. to keep documentation circles around pads)
=> Package editor: Add tool to move & align objects

libs/librepcb/editor/CMakeLists.txt, libs/librepcb/editor/editorcommandset.h, libs/librepcb/editor/library/editorwidgetbase.h, libs/librepcb/editor/library/libraryeditor.cpp, libs/librepcb/editor/library/libraryeditor.h, libs/librepcb/editor/library/pkg/fsm/packageeditorfsm.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorfsm.h, libs/librepcb/editor/library/pkg/fsm/packageeditorstate.h, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_renumberpads.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_renumberpads.h, libs/librepcb/editor/library/pkg/packageeditorwidget.cpp
Especially after copy&pasting pads, one has to manually assign each of the pasted pads to the corresponding package pad. For many pads, this can be very cumbersome. This this PR adds a new tool to re-number all pads in a footprint:
Behavior:
- When starting the tool, all pad numbers are cleared
- Pads are assigned one-by-one by clicks on pads in the desired order
- When pressing SHIFT, auto-increment is disabled to allow assigning multiple pads to the same package pad
- If multiple pads are in the area between the last assigned pad and the currently highlighted, each of the pads in this area will be assigned at once
- The numbering direction X->Y vs. Y->X can be toggled by pressing SHIFT
- This multi-mode can be disabled by pressing CTRL to allow single selection
- The tool is left (and …
=> Package editor: Add tool to interactively re-number pads

ci/azure-jobs-macos.yml
Homebrew does not provide binaries for macOS 12 anymore, which broke CI. Thus we have to update to macOS 13. Even though macOS 12 is EOL now, probably many people still use it and won't be happy that our binary releases might not run there anymore, but there's not much we could do to avoid it... :slightly_frowning_face:
=> CI: Update to macOS 13

libs/librepcb/core/CMakeLists.txt, libs/librepcb/core/library/pkg/footprintpad.cpp, libs/librepcb/core/serialization/fileformatmigrationv1.cpp, libs/librepcb/core/serialization/fileformatmigrationv1.h, tests/unittests/core/library/pkg/footprintpadtest.cpp
Press-fit pads were incorrectly deserialized, leading in an error when opening the package :-/ Now support loading the incorrect value (to avoid the error) and make the v1->v2 file format migration restoring the correct value in files.
=> Fix deserialization of pressfit pads

libs/librepcb/editor/CMakeLists.txt, libs/librepcb/editor/dialogs/backgroundimagesetupdialog.cpp, libs/librepcb/editor/dialogs/backgroundimagesetupdialog.h, libs/librepcb/editor/dialogs/backgroundimagesetupdialog.ui, libs/librepcb/editor/editorcommandset.h, libs/librepcb/editor/library/editorwidgetbase.h, libs/librepcb/editor/library/libraryeditor.cpp, libs/librepcb/editor/library/libraryeditor.h, libs/librepcb/editor/library/pkg/packageeditorwidget.cpp, libs/librepcb/editor/library/pkg/packageeditorwidget.h, libs/librepcb/editor/utils/shortcutsreferencegenerator.cpp
This PR allows to set an image as a semi-transparent overlay in the footprint editor, to verify the footprint geometry with a package drawing (e.g. from a datasheet). Images can be loaded from several sources:
- Take screenshot directly from within LibrePCB (with 3 seconds delay to allow window switching)
- Paste from clipboard
- Load from file
Then the transform of the image needs to be set by a few steps:
1. Crop the image (optional)
2. Mirror & rotate the image, if required
3. Specify two points in the image with their corresponding target coordinates in the footprint. LibrePCB will then calculate X- and Y scale factors and offset for the actual image placement. A sanity check warns e.g. in case the distance in one direction is not large enough, thus would lead in inaccurate scaling. …
=> Package editor: Support displaying datasheet image overlay

libs/librepcb/core/utils/messagelogger.cpp, libs/librepcb/core/utils/messagelogger.h, libs/librepcb/editor/library/eaglelibraryimportwizard/eaglelibraryimportwizardpage_result.cpp, libs/librepcb/editor/project/newprojectwizard/newprojectwizardpage_eagleimport.cpp
Text colors were only suitable for light window background - now using better colors for dark windows.
=> Eagle import: Fix unreadable log messages with dark theme

apps/librepcb/main.cpp, libs/librepcb/core/application.cpp, libs/librepcb/core/application.h, libs/librepcb/core/fileio/filepath.cpp, libs/librepcb/core/fileio/filepath.h, tests/unittests/core/fileio/directorylocktest.cpp, tests/unittests/core/network/filedownloadtest.cpp, tests/unittests/core/sqlitedatabasetest.cpp
AFAIK the temporary directory on Windows is not cleaned automatically at reboot, thus might get bigger and bigger if LibrePCB does not clean it up either. So let's scan the temporary directory of LibrePCB during application startup and delete files older than 60 days. This is done in a thread to avoid delaying application startup.
=> Delete old temporary files at application startup

apps/librepcb-cli/commandlineinterface.cpp, libs/librepcb/core/CMakeLists.txt, libs/librepcb/core/geometry/via.cpp, libs/librepcb/core/geometry/via.h, libs/librepcb/core/project/board/boardplanefragmentsbuilder.cpp, libs/librepcb/core/project/board/boardplanefragmentsbuilder.h, libs/librepcb/core/project/board/drc/boardclipperpathgenerator.cpp, libs/librepcb/core/project/board/drc/boardclipperpathgenerator.h, libs/librepcb/core/project/board/drc/boarddesignrulecheck.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheck.h, libs/librepcb/core/project/board/drc/boarddesignrulecheckdata.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheckdata.h, libs/librepcb/core/project/board/drc/boarddesignrulecheckmessages.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheckmessages.h, libs/librepcb/core/types/layer.h, libs/librepcb/editor/project/boardeditor/boardeditor.cpp, libs/librepcb/editor/project/boardeditor/fabricationoutputdialog.cpp, tests/unittests/CMakeLists.txt, tests/unittests/core/project/board/boarddesignrulechecktest.cpp, tests/unittests/core/project/board/boardgerberexporttest.cpp, tests/unittests/core/project/board/boardplanefragmentsbuildertest.cpp
This PR refactors two CPU intensive operations to run them now with multiple threads:
- Plane fragment building
- Design rule check
Planes are now using a separate thread for each layer. So the more layers, the more time is saved now. In a real project with planes on 4 layers, I measured an improvement from ~170ms to ~95ms (44%), and with a complex 2-layer board I measured an improvement from 490ms to 330ms (33%). This makes the UI feeling more responsive while drawing traces etc.
For the DRC, it is more complicated since there are many different kinds of checks and some checks depend on CPU-intensive precalculated data. The concept is documented in the source code:
```
// - A subset of jobs, called "stage 1", is run in parallel to calculate data
//   which other jobs depend on (e.g. …
```
=> Refactor & speed up plane rebuilds & DRC with multithreading

libs/librepcb/core/network/networkrequestbase.cpp, libs/librepcb/core/network/networkrequestbase.h, libs/librepcb/core/workspace/workspacelibrarydb.cpp, libs/librepcb/core/workspace/workspacelibrarydb.h, libs/librepcb/core/workspace/workspacelibrarydbwriter.cpp, libs/librepcb/core/workspace/workspacelibrarydbwriter.h, libs/librepcb/core/workspace/workspacelibraryscanner.cpp, libs/librepcb/core/workspace/workspacelibraryscanner.h, libs/librepcb/editor/library/cmd/cmdlibraryelementedit.cpp, libs/librepcb/editor/library/cmd/cmdlibraryelementedit.h, libs/librepcb/editor/library/cmp/componenteditorwidget.cpp, libs/librepcb/editor/library/cmp/componenteditorwidget.ui, libs/librepcb/editor/library/dev/deviceeditorwidget.cpp, libs/librepcb/editor/library/dev/deviceeditorwidget.ui, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_select.cpp, libs/librepcb/editor/project/partinformationprovider.cpp, libs/librepcb/editor/project/partinformationprovider.h, libs/librepcb/editor/project/projecteditor.cpp, libs/librepcb/editor/project/projecteditor.h, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_select.cpp, libs/librepcb/editor/utils/menubuilder.cpp, libs/librepcb/editor/utils/menubuilder.h, libs/librepcb/editor/workspace/desktopservices.cpp, libs/librepcb/editor/workspace/desktopservices.h
The support for storing datasheet URLs in components and devices has already been implemented in the LibrePCB 1.0 file format (#1181), but it has not been not implemented in the UI yet. This PR implements the missing UI integration, consisting of several parts:
A new text field for components and devices in the library editor allows to enter a datasheet URL:
If a datasheet URL is set, the button next to the text field opens it. Useful for testing URLs but also when working on a library element to quickly access the datasheet.
Note that the file format actually allows to store multiple URLs, not just one. But to keep the UI simple, for now it only displays & modifies the first URL if there are multiple.
The background library scan now also stores any URLs on components and devices in the …
=> Support specifying & opening datasheets in editors

libs/librepcb/editor/library/cmp/componentsymbolvariantitemlistmodel.cpp, libs/librepcb/editor/library/cmp/componentsymbolvariantitemlistmodel.h
When creating or modifying a component, gate suffixes "A", "B", "C" etc. are now automatically added since it is a frequent source of confusion and it is not so intuitive that this should be done. For single-symbol components, no suffix is added.
Closes #1426
=> Library editor: Automatically set gate suffixes

libs/librepcb/editor/library/cmp/componentpinsignalmapmodel.cpp, libs/librepcb/editor/library/newelementwizard/newelementwizardpage_componentsignals.cpp, libs/librepcb/editor/library/newelementwizard/newelementwizardpage_componentsignals.h
When creating a new component in the library editor which consists of multiple gates, the automatically added component signals may have conflicting names (e.g. 2x "OUT" for a dual opamp). This change appends an incrementing number in this case (e.g. "OUT1" & "OUT2").
The "Automatically assign all signals by name" also takes this suffix into account to get a successful auto-assignment, no matter if the suffix is there or not.
Fixes #1425
=> Library editor: Fix conflicting component signal names

libs/librepcb/core/project/board/items/bi_footprintpad.cpp, libs/librepcb/editor/graphics/primitivefootprintpadgraphicsitem.cpp, libs/librepcb/editor/graphics/primitivefootprintpadgraphicsitem.h, libs/librepcb/editor/library/pkg/footprintpadgraphicsitem.cpp, libs/librepcb/editor/project/boardeditor/graphicsitems/bgi_footprintpad.cpp, libs/librepcb/editor/project/boardeditor/graphicsitems/bgi_footprintpad.h
So far, the board editor displayed the pad name and (if connected) the net name in the footprint pads. However, often both values are not very expressive (e.g. pad name is just a number, and net name is auto-generated "N#"). So, often the function of a pad is not clear. 
Since the component signal is always something expressive, it will now be displayed in pads too. In addition, the tooltip now contains the component signal name and the net name too.
=> Board editor: Display component signal names in pads

libs/librepcb/core/library/cmp/componentcheck.cpp, libs/librepcb/core/library/cmp/componentcheck.h, libs/librepcb/core/library/cmp/componentcheckmessages.cpp, libs/librepcb/core/library/cmp/componentcheckmessages.h, libs/librepcb/editor/library/cmp/componenteditorwidget.cpp, libs/librepcb/editor/library/cmp/componentsymbolvariantlistwidget.cpp, libs/librepcb/editor/library/cmp/componentsymbolvariantlistwidget.h
It seems to be a frequent issue that users forget to connect pins to their corresponding component signals in the component editor. The UI is also not so clear about this since the corresponding editor is located in a dialog.
Now the component editor warns clearly (error severity) if a component contains signals and pins, but no connections exist at all. And the "fix" button directly opens the dialog where the connections need to be made.
=> Component check: Warn about missing pin-signal connections

libs/librepcb/core/library/pkg/packagecheck.cpp, libs/librepcb/core/library/pkg/packagecheck.h, libs/librepcb/core/library/pkg/packagecheckmessages.cpp, libs/librepcb/core/library/pkg/packagecheckmessages.h, libs/librepcb/core/library/sym/symbolcheck.cpp, libs/librepcb/core/library/sym/symbolcheck.h, libs/librepcb/core/library/sym/symbolcheckmessages.cpp, libs/librepcb/core/library/sym/symbolcheckmessages.h, libs/librepcb/editor/library/pkg/fsm/packageeditorfsm.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorfsm.h, libs/librepcb/editor/library/pkg/fsm/packageeditorstate.h, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_select.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_select.h, libs/librepcb/editor/library/pkg/packageeditorwidget.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorfsm.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorfsm.h, libs/librepcb/editor/library/sym/fsm/symboleditorstate.h, libs/librepcb/editor/library/sym/fsm/symboleditorstate_select.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_select.h, libs/librepcb/editor/library/sym/symboleditorwidget.cpp
Our guidelines clearly say that symbols should be centered around the origin (0, 0). This is mainly for a consistent look&feel, but also because symbols can be grabbed at (0, 0) so it's important for usability that every symbol can be grabbed at the same position.
For packages, out guidelines also clearly say the body center must be at (0, 0) because this is the position where pick&place machines will pick the part. So it's really important to have it in the body center.
However, I saw many users do not follow these guidelines. Possibly because many symbols & packages in other EDA tools do not follow them either or have other guidelines. Especially in KiCad, many footprints have pin-1 at (0, 0).
To enforce this rule more strictly for LibrePCB users, the symbol- & package editors try to …
=> Library editor: Warn about non-centered symbols/packages

libs/librepcb/editor/widgets/openglview.cpp
Seems the shader program needs to be bound, though it worked without this call in older Qt versions...
=> Fix OpenGL 3D viewers for Qt > 6.6

CMakeLists.txt, cmake/FindMuParser.cmake, libs/librepcb/kicadimport/CMakeLists.txt, libs/librepcb/kicadimport/kicadlibraryconverter.cpp, libs/librepcb/kicadimport/kicadlibraryimport.cpp, libs/librepcb/kicadimport/kicadlibraryimport.h, libs/librepcb/kicadimport/kicadtypes.cpp
The CMake config for the muparser & kicadimport libraries were not correct, possibly leading to false-positive and false-negative compiler warnings in those libraries.
=> CMake: Fix compiler flags for muparser & kicadimport

libs/librepcb/core/project/board/boardnetsegmentsplitter.cpp, libs/librepcb/core/project/board/boardnetsegmentsplitter.h, libs/librepcb/core/project/schematic/schematicnetsegmentsplitter.cpp, libs/librepcb/core/project/schematic/schematicnetsegmentsplitter.h
Fixes a segfault which was detected on Alpine Linux, see https://github.com/LibrePCB/LibrePCB/issues/1476#issuecomment-2529918400.
=> Fix accessing dangling reference in net segment splitters

libs/librepcb/core/3d/occmodel.cpp, tests/unittests/core/3d/occmodeltest.cpp
The STEP export failed with an OpenCascade error in some cases when the board outline contained arcs. It seems to be a problem with numeric precision which makes OpenCascade failing to create some arcs.
This PR increases the tolerance of OpenCascade regarding numeric precision, but it does not entirely fix the problem. As a workaround, arcs are now automatically approximated by straight line segments in case of a failure, so STEP models can successfully be exported, just with reduced accuracy in these cases...
Open question in OpenCascade forum how to fix it properly: https://dev.opencascade.org/content/how-build-arc-wire-without-triggering-precision-errors
=> STEP export: Fix possible error with arcs in board outline

AUTHORS.md, libs/librepcb/core/project/board/drc/boarddesignrulecheck.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheck.h, libs/librepcb/core/project/board/drc/boarddesignrulecheckdata.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheckdata.h, libs/librepcb/core/project/board/drc/boarddesignrulecheckmessages.cpp, libs/librepcb/core/project/board/drc/boarddesignrulecheckmessages.h, tests/unittests/core/project/board/boarddesignrulechecktest.cpp
The previous implementation only detected vias as useless if they had no `drillLayerSpan`. Now they are also detected if there are traces from less than two layers connected. This identifies situations like below, where you may mistakenly have left a via:
<details><summary>Screenshot</summary>
<p>
</p>
</details>
=> DRC: Report vias as useless if connected on <2 layers

libs/librepcb/editor/widgets/graphicsview.cpp
Was a regression of some refactoring which caused the crosshairs of all measure tools and some polygon drawing tools to be invisible...
=> Fix missing crosshairs in some editor tools

libs/librepcb/editor/project/outputjobsdialog/outputjoblistwidgetitem.cpp, libs/librepcb/editor/project/outputjobsdialog/outputjoblistwidgetitem.h, libs/librepcb/editor/project/outputjobsdialog/outputjobsdialog.cpp, libs/librepcb/editor/widgets/rulechecklistwidget.cpp, libs/librepcb/editor/widgets/rulechecklistwidget.h
List items in the output jobs dialog and rule check docks had a wrong (badly readable) text color for selected list items when using the dark theme. This PR makes the text color theme-aware to fix it.
=> Fix some list view text colors for dark theme

libs/librepcb/kicadimport/kicadlibraryconverter.cpp, libs/librepcb/kicadimport/kicadlibraryconverter.h, libs/librepcb/kicadimport/kicadtypes.cpp, tests/unittests/kicadimport/kicadlibraryimporttest.cpp
KiCad v9 was released, with some small changes in the library file format. This PR adds compatibility with that format.
In addition, the KiCad libraries provided by Ultra Librarian seem to have an old format (KiCad v6) and also have a strange/invalid structure (footprints are in `footprints.pretty`, but symbols do not reference it properly with that namespace). This PR adds basic compatibility with the v6 format and an ugly hack that the illegal structure is supported anyway, for a better user experience if libraries from Ultra Librarian are imported.
=> KiCad Library Import: Add compatibility with KiCad v9 & Ultra Librarian

libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawplane.cpp, libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_drawplane.h
There was a leftover from old LibrePCB versions which didn't allow to add planes without a net, still rejecting adding planes if the project contains no nets (i.e. the schematic is empty). Removed that conditional since planes without a net are now allowed.
Also slightly improved the logic for preselecting the default net when adding a new plane.
=> Board editor: Fix rejecting planes if project has no nets

CMakeLists.txt, ci/azure-jobs-doxygen.yml, ci/azure-jobs-linux.yml, ci/azure-jobs-macos.yml, ci/azure-jobs-stylecheck.yml, ci/azure-jobs-windows.yml, ci/build_librepcb.sh, ci/build_linux_portables.sh, ci/install_dependencies.sh, ci/stylecheck.sh
Use new Docker images with the following updates:
- https://github.com/LibrePCB/docker-librepcb-dev/pull/56
- https://github.com/LibrePCB/docker-librepcb-dev/pull/57
- https://github.com/LibrePCB/docker-librepcb-dev/pull/58
- https://github.com/LibrePCB/docker-librepcb-dev/pull/59
- https://github.com/LibrePCB/docker-librepcb-dev/pull/60
- https://github.com/LibrePCB/docker-librepcb-dev/pull/63
In addition:
- Now build with Ninja on Linux and MacOS too, not using GNU Make anymore at all
- Enable ccache also for all Linux jobs
- Stop deploying unnecessary OpenSSL 1.x libs in Linux releases
- Run `appstream-util validate` on AppStream XML file
Fixes https://github.com/LibrePCB/LibrePCB/issues/1480
=> CI: Update Docker images, fix OpenSSL deployment on Linux

CMakeLists.txt, README.md, ci/azure-jobs-macos.yml, ci/build_linux_portables.sh, ci/build_mac_bundle.sh, ci/build_windows_archive.sh, ci/macdeployqt-dummy.qml, dev/doxygen/pages/building.md, dev/format_code.sh, libs/librepcb/core/build_env.h.in, libs/librepcb/editor/CMakeLists.txt, libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp, libs/librepcb/editor/workspace/controlpanel/controlpanel.h
It's pretty clear now we'll go with Slint, not QtQuick so we don't need this evaluation dependency anymore...
=> Remove QtQuick test window & dependency

ci/azure-jobs-linux.yml, ci/azure-jobs-macos.yml, ci/azure-jobs-windows.yml, ci/build_librepcb.sh, ci/build_linux_portables.sh, ci/build_mac_bundle.sh, ci/build_windows_archive.sh, ci/build_windows_installer.sh, dist/appimage/AppRun
That tool feels more mature, maybe it causes less troubles...
=> CI: Build AppImage with linuxdeploy instead of linuxdeployqt

.reuse/dep5
Fixes compatibility with the latest CMake release by bumping `cmake_minimum_required()` to 3.5 or higher.
=> Update submodules muparser, type_safe & googletest

libs/librepcb/editor/project/schematiceditor/schematicgraphicsscene.cpp
Unfortunately polygon vertices were not draggable with the cursor in the schematic editor due to a regression.
=> Schematic editor: Fix polygons not being editable

ci/azure-jobs-stylecheck-doxygen.yml, dev/format_code.sh, dev/format_code_helper.py, libs/librepcb/editor/library/librariesmodel.cpp, libs/librepcb/editor/notificationsmodel.cpp, libs/librepcb/editor/ui/aboutpanel.slint, libs/librepcb/editor/ui/api/data.slint, libs/librepcb/editor/ui/api/helpers.slint, libs/librepcb/editor/ui/appwindow.slint, libs/librepcb/editor/ui/homepanel.slint, libs/librepcb/editor/ui/hometab.slint, libs/librepcb/editor/ui/library/createlibrarytab.slint, libs/librepcb/editor/ui/library/downloadlibrarytab.slint, libs/librepcb/editor/ui/library/librariespanel.slint, libs/librepcb/editor/ui/mainmenubar.slint, libs/librepcb/editor/ui/notificationspopup.slint, libs/librepcb/editor/ui/sidebar.slint, libs/librepcb/editor/ui/statusbar.slint, libs/librepcb/editor/ui/widgets/treeview.slint, libs/librepcb/editor/ui/windowsection.slint, libs/librepcb/editor/utils/deriveduiobjectlistview.h, libs/librepcb/editor/utils/uiobjectlist.h, libs/librepcb/editor/workspace/filesystemmodel.cpp, libs/librepcb/editor/workspace/quickaccessmodel.cpp
Fixing deprecation warnings & make use of trailing commas in import statements, enforced by our own code formatter script.
=> Update to Slint 1.11.0

libs/librepcb/core/geometry/path.cpp, libs/librepcb/core/geometry/path.h, libs/librepcb/editor/project/cmd/cmddragselectedschematicitems.cpp, libs/librepcb/editor/project/cmd/cmddragselectedschematicitems.h, libs/librepcb/editor/project/cmd/cmdschematicnetlabeledit.cpp, libs/librepcb/editor/project/cmd/cmdschematicnetlabeledit.h, libs/librepcb/editor/project/cmd/cmdschematicnetpointedit.cpp, libs/librepcb/editor/project/cmd/cmdschematicnetpointedit.h, libs/librepcb/editor/project/cmd/cmdsymbolinstanceedit.cpp, libs/librepcb/editor/project/cmd/cmdsymbolinstanceedit.h, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorfsm.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorfsm.h, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate.h, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_select.cpp, libs/librepcb/editor/project/schematiceditor/fsm/schematiceditorstate_select.h, tests/unittests/core/geometry/pathtest.cpp
Just like in the board editor, allow moving off-grid objects to the grid with a command.
=> Schematic editor: Support snap to grid

libs/librepcb/core/utils/mathparser.cpp, libs/librepcb/core/utils/mathparser.h, tests/unittests/core/utils/mathparsertest.cpp
Especially in Germany one would expect the decimal point "." should be usable as the decimal separator even though officially it would be the comma. Thus now always accepting the decimal point *in addition* to the locale-dependent decimal separator.
As a downside, for locales with the decimal point as the *thousands* separator you can no longer enter thousands separators, e.g. "1.000,5" with de_DE is no longer a valid input because both separators are considered as the decimal separator. But I think this is an acceptable downside as probably nobody inserts thousands separator and we rarely have to write large numbers anyway.
Closes #1367.
=> Always accept decimal point as separator in input fields

libs/librepcb/editor/mainwindow.cpp
When opening LibrePCB (or additional main windows) the very first time, maximize the window because I think this is the most reasonable default window size.
Closes #355
=> Initially maximize new main windows

.github/workflows/main.yml, ci/azure-pipelines.yml, ci/build_mac_bundle.sh, ci/install_dependencies.sh, ci/upload_artifacts.sh, tests/cli/test_version.py, tests/unittests/core/project/board/boardgerberexporttest.cpp, tests/unittests/core/project/board/boardplanefragmentsbuildertest.cpp
Unfortunately Azure still doesn't provide Apple Silicon runners, but Github Actions does now. So let's add a CI job here to finally get Apple Silicon builds from CI.
EDIT: Tested the *.dmg coming out of this job on MacOS 13 and sadly it doesn't run, but this was kind of expected due to #1527 (CI builds with MacOS 14).
=> CI: Set up Apple Silicon job with Github Actions

libs/librepcb/core/project/outputjobrunner.cpp, libs/librepcb/core/project/outputjobrunner.h, libs/librepcb/editor/project/board/board2dtab.cpp, libs/librepcb/editor/project/outputjobsdialog/graphicsoutputjobwidget.cpp, tests/unittests/CMakeLists.txt, tests/unittests/core/project/outputjobrunnertest.cpp
Actually I thought we already do this, but it was not the case :sob: Usually planes were already up-to-date during Gerber/PDF/etc. exports because they were rendered on screen, but if they were not rendered (e.g. board editor closed, running output jobs from schematic editor) no planes were rebuilt for the data export. This is really dangerous, thus now fixing it.
=> Rebuild planes before exporting data which contains copper layers

apps/librepcb-cli/commandlineinterface.cpp, ci/build_linux_portables.sh, ci/build_mac_bundle.sh, ci/build_windows_archive.sh, ci/build_windows_installer.sh, libs/librepcb/core/CMakeLists.txt, libs/librepcb/core/application.cpp, libs/librepcb/core/application.h, libs/librepcb/core/build_env.h.in, tests/cli/test_version.py
Currently the build datetime is compiled into the executable and shown in the app version section:
```
LibrePCB Version: 1.3.1-unstable
Git Revision:     158544617
Build Date:       2025-06-29T23:38:52
[...]
```
But of course this clearly breaks reproducible builds. I don't want to completely omit the datetime as it is helpful for users to see how old their installed version is. But I think it makes more sense to include the *commit* date rather than the *build* date as it leads to more reproducible builds. Also I removed the output of the time, I think the date is enough:
```
LibrePCB Version: 1.3.1-unstable
Git Revision:     7032e481c (2025-06-29)
[...]
```
In addition, this PR makes CI printing out the sha256 sum of all build artifacts to allow public verification that our official …
=> Replace non-reproducible build date by Git commit date

apps/README.md, apps/librepcb/README.md
There were several broken links in /apps/README.md and  /apps/librepcb/README.md. The fault was that file types were mixed up, such as .png was meant to be .svg, and .svg was meant to be .drawio.svg.
=> Fix broken links of architecture diagrams

.github/workflows/main.yml
Now pulling the new image from GitHub container registry since the image is now built on CI, see https://github.com/LibrePCB/docker-librepcb-dev/pull/70.
And added a flag to `docker stop` to make it terminate the container if necessary.
=> CI: Update Windows docker image

.github/workflows/main.yml, ci/azure-jobs-linux.yml, ci/azure-jobs-macos.yml, ci/azure-jobs-stylecheck-doxygen.yml, ci/build_windows_archive.sh, ci/build_windows_installer.sh, ci/sign.ps1, ci/tar_artifacts.sh, ci/upload_artifacts.sh, dev/doxygen/pages/release_workflow.md, dist/innosetup/installer.iss
This configures CI & Inno Setup to perform code signing if credentials for AzureSignTool are available on CI. If those are not available, code signing is disabled. The actual signing will be done in the repository https://github.com/OSSign/LibrePCB--LibrePCB.
=> Set up code signing of Windows executables & installer

libs/librepcb/editor/graphics/slintgraphicsview.cpp, libs/librepcb/editor/graphics/slintgraphicsview.h, libs/librepcb/editor/library/sym/symboltab.cpp, libs/librepcb/editor/project/board/board2dtab.cpp, libs/librepcb/editor/project/schematic/schematictab.cpp
Support OpenGL 2D rendering, depending on workspace settings. We already had it in previous versions but it was dropped during the Slint migration because the 2D graphics view needed to be re-implemented in a different way.
=> SlintGraphicsView: Support rendering with OpenGL

libs/librepcb/core/library/pkg/package.cpp, libs/librepcb/core/library/pkg/package.h, libs/librepcb/core/library/sym/symbol.cpp, libs/librepcb/core/library/sym/symbol.h, libs/librepcb/core/project/schematic/schematic.h, libs/librepcb/core/serialization/fileformatmigrationunstable.cpp, libs/librepcb/core/serialization/fileformatmigrationv1.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorfsm.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorfsm.h, libs/librepcb/editor/library/pkg/fsm/packageeditorstate.h, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_select.cpp, libs/librepcb/editor/library/pkg/fsm/packageeditorstate_select.h, libs/librepcb/editor/library/pkg/packagetab.cpp, libs/librepcb/editor/library/pkg/packagetab.h, libs/librepcb/editor/library/sym/fsm/symboleditorfsm.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorfsm.h, libs/librepcb/editor/library/sym/fsm/symboleditorstate.h, libs/librepcb/editor/library/sym/fsm/symboleditorstate_select.cpp, libs/librepcb/editor/library/sym/fsm/symboleditorstate_select.h, libs/librepcb/editor/library/sym/symboltab.cpp, libs/librepcb/editor/library/sym/symboltab.h, libs/librepcb/editor/mainwindow.cpp, libs/librepcb/editor/project/schematic/fsm/schematiceditorfsm.cpp, libs/librepcb/editor/project/schematic/fsm/schematiceditorfsm.h, libs/librepcb/editor/project/schematic/fsm/schematiceditorstate.h, libs/librepcb/editor/project/schematic/fsm/schematiceditorstate_select.cpp, libs/librepcb/editor/project/schematic/fsm/schematiceditorstate_select.h
See ##1366. This PR will store the grid interval from the UI in the symbol & package files so that it is restored the next time you open those elements.
I'm not 100% sure this is a good idea. It does make sense for many cases for sure, but it might also lead to additional "noise" in version control of libraries when the grid interval is changed. However, I think if this happens, we could consider not storing the grid interval automatically on save, but only on request (like a "save grid interval" command). And in very worst case, we could revert this change in file format v3 :see_no_evil: 
Note that in contrast to schematics & boards, the grid *unit* is not stored as it is more a personal preference than a property of the library element.
Closes #1366
=> Store grid interval in symbols & packages

libs/librepcb/core/project/board/items/bi_netsegment.cpp, libs/librepcb/core/project/board/items/bi_netsegment.h, libs/librepcb/core/project/schematic/items/si_netsegment.cpp, libs/librepcb/core/project/schematic/items/si_netsegment.h
Net segments (either in schematics or in boards) which consist only of direct lines between pins or pads (i.e. contain no junctions or vias) were considered as valid even if those lines did not touch each other. I.e. this was a bug in the detection of non-cohesive segments.
Theoretically this change breaks loading existing projects if they contain such invalid segments. But generally the editors should have never created such invalid segments, therefore I consider this risk as very low. If anyone experiences this issue, please let me know. I put a "contact us" note into the corresponding error message.
=> Fix detection of cohesive net segments

libs/librepcb/core/CMakeLists.txt, libs/librepcb/core/algorithm/netsegmentsimplifier.cpp, libs/librepcb/core/algorithm/netsegmentsimplifier.h, libs/librepcb/editor/CMakeLists.txt, libs/librepcb/editor/project/board/fsm/boardeditorstate_drawtrace.cpp, libs/librepcb/editor/project/board/fsm/boardeditorstate_drawtrace.h, libs/librepcb/editor/project/board/fsm/boardeditorstate_select.cpp, libs/librepcb/editor/project/cmd/cmdremoveboarditems.cpp, libs/librepcb/editor/project/cmd/cmdremoveboarditems.h, libs/librepcb/editor/project/cmd/cmdremoveselectedboarditems.cpp, libs/librepcb/editor/project/cmd/cmdsimplifyboardnetsegments.cpp, libs/librepcb/editor/project/cmd/cmdsimplifyboardnetsegments.h, tests/unittests/CMakeLists.txt, tests/unittests/core/algorithm/netsegmentsimplifiertest.cpp
When drawing traces or deleting traces/vias in the board editor, the modified net segments will be automatically simplified in the following ways:
- Remove redundant junctions (same position, same layer)
- Remove redundant traces (same anchors, same layer), keeping only the thickest of them
- Remove zero-length traces
- Remove useless junctions within straight trace segments (join line segments into the same direction to a single trace)
- Split traces to connect with junctions on the path between start and end points
- Split intersecting traces, placing a new junction to connect them (only orthogonal intersections for now)
The simplification is added as a separate operation to the undo stack. If for any reason the user doesn't want the simplified result, just press Ctrl+Z and you'll have …
=> Board editor: Automatically simplify net segments

libs/librepcb/editor/library/lib/librarytab.cpp, libs/librepcb/editor/library/lib/librarytab.h, libs/librepcb/editor/ui/api.slint, libs/librepcb/editor/ui/api/types.slint, libs/librepcb/editor/ui/library/lib/librarytab.slint
Completely split the "move to other library" and "copy to other library" commands, see https://librepcb.discourse.group/t/copy-element-from-read-only-lib-to-local-lib/956.
=> Library editor: Split move/copy to other library

libs/librepcb/core/project/board/board.cpp, libs/librepcb/core/project/board/boardplanefragmentsbuilder.cpp, libs/librepcb/core/project/board/boardplanefragmentsbuilder.h, libs/librepcb/core/project/board/items/bi_plane.cpp, libs/librepcb/core/project/board/items/bi_plane.h, libs/librepcb/core/project/projectloader.cpp, libs/librepcb/core/serialization/fileformatmigrationunstable.cpp, libs/librepcb/core/serialization/fileformatmigrationv1.cpp, libs/librepcb/eagleimport/eagleprojectimport.cpp, libs/librepcb/editor/project/board/boardclipboarddata.h, libs/librepcb/editor/project/board/boardclipboarddatabuilder.cpp, libs/librepcb/editor/project/board/boardplanepropertiesdialog.cpp, libs/librepcb/editor/project/board/boardplanepropertiesdialog.ui, libs/librepcb/editor/project/cmd/cmdboardplaneedit.cpp, libs/librepcb/editor/project/cmd/cmdboardplaneedit.h, libs/librepcb/editor/project/cmd/cmdpasteboarditems.cpp, tests/unittests/editor/project/board/boardclipboarddatatest.cpp
As explained in #1435, this PR adds two more properties to planes to allow specifying individual clearances to the board outline and holes:
The plane fragments calculation algorithm has been adjusted accordingly to respect these new properties. And a clearance value of 0 is now handled differently to disable clipping the plane area to the board outlines, i.e. the plane will always fill up to its own outline, completely ignoring the board outlines and holes.
During project file format upgrade from v1, these properties are initialized with the value of the copper clearance to not introduce any change for existing planes. For new planes, the default copper clearance is now reduced from 300um to 250um. The two new properties are initialized with 300um.
Closes #1435
=> Planes: Support configuring clearance to board outline & holes

libs/librepcb/core/serialization/fileformatmigrationv01.cpp, libs/librepcb/core/serialization/fileformatmigrationv1.cpp, libs/librepcb/editor/project/projecteditor.cpp
Stale files in a project can lead to fatal upgrade errors (e.g. `schematic.lp` or `board.lp` which have actually been removed from the project, but still exist on the file system), therefore now ignoring them, i.e. no longer upgrade them.
In addition, change the sort order of upgrade messages to oldest at top, newest at bottom for a natural reading flow.
=> Ignore stale schematics/boards during file format upgrade

libs/librepcb/core/library/pkg/package.cpp, libs/librepcb/core/library/pkg/package.h, libs/librepcb/core/library/pkg/packagecheck.cpp, libs/librepcb/core/library/pkg/packagecheckmessages.cpp, libs/librepcb/core/serialization/fileformatmigrationunstable.cpp, libs/librepcb/core/serialization/fileformatmigrationv1.cpp, libs/librepcb/editor/library/cmd/cmdpackageedit.cpp, libs/librepcb/editor/library/cmd/cmdpackageedit.h, libs/librepcb/editor/library/pkg/packagetab.cpp, libs/librepcb/editor/library/pkg/packagetab.h, libs/librepcb/editor/mainwindow.cpp, libs/librepcb/editor/ui/api/types.slint, libs/librepcb/editor/ui/rulecheckpanel.slint
The new package-specific copper clearance can be configured in the rule check panel.
Closes #1529
=> Support specifying per-package copper clearance value

libs/librepcb/core/network/apiendpoint.cpp, libs/librepcb/core/network/apiendpoint.h, libs/librepcb/editor/library/librariesmodel.cpp, libs/librepcb/editor/library/librariesmodel.h, libs/librepcb/editor/mainwindow.cpp, libs/librepcb/editor/ui/api/types.slint, libs/librepcb/editor/ui/library/librariespanel.slint
The button fetches the remote libraries **bypassing the HTTP cache**. This is very handy when a library update was just published to allow users getting that update without waiting for the HTTP cache to become outdated.
=> Library manager: Add button to manually check for updates
